### ISSUE TITLE
iphone mirroring软件滑轮不能使用 [bug]

### ISSUE THREAD

**Issue by adam2266946** [noah-nuebling/Mac-Mouse-Fix#1018]
## Description

软件打开 滚动 以后，iphone mirroring软件鼠标滚轮上下就失效

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: 15.0 beta
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Thank you for your feedback! Please see #1015.
