### ISSUE TITLE
App is signed with an untrusted certificate and won't open on M1 mac [bug]

### ISSUE THREAD

**Issue by FraserEmbrey** [noah-nuebling/mac-mouse-fix#102]
## Description

The certificate is untrusted and macOS refuses to open it, saying it will damage the Mac.

## Steps to reproduce

Get M1 Mac
Download app
Open app
See error

## Context

Mac Mouse Fix Version: 2.0.0 Beta 7
macOS Version: 11.3.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey Fraser, thanks for reaching out about this.

New versions of the app which should fix these error messages are now available:

- [1.0.4](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/1.0.4)
- [2.0.0 Beta 8](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0-Beta-8)

Let me know if you have any more troubles with these.

For more info on what's going on see https://github.com/noah-nuebling/mac-mouse-fix/issues/95

**Comment by FraserEmbrey** [comment]
Thank you!
