### ISSUE TITLE
Mac Mouse Fix - Won't work with Iphone Mirroring (Sequioa Beta 2) [bug]

### ISSUE THREAD

**Issue by BreadstickFTW** [noah-nuebling/Mac-Mouse-Fix#1032]
## Description

Mac Mouse Fix - Won't work with Iphone Mirroring (Sequioa Beta 2). Scrolling does not work properly - as soon as you turn mac mouse fix off it works perfectly.

## Steps to reproduce

1. Use iphone mirroring on mac
2. Scroll 
3. Scrolling does not work

## Context

Mac Mouse Fix Version: 2.2.4
macOS Version: Mac OS Developer Beta 2
Mouse Model: Logitech G502 (and others (see reddit))

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by powerycz** [comment]
Same problem as you had. Waiting for answers.

**Comment by khodex-rei** [comment]
I'm having the same issue

**Comment by noah-nuebling** [comment]
Thanks for reaching out guys! Please see #1015.
