### ISSUE TITLE
Scrolling is not smooth with external displays [enhancement]

### ISSUE THREAD

**Issue by neel04** [noah-nuebling/Mac-Mouse-Fix#1036]
## Description
When using higher refresh monitors (I'm using a 1440p @ 165Hz monitor) the scrolling isn't smooth/seems to be locked at 60 fps. This is evident when you do scrolling through other means (such as page up/down key) and see how smooth the scrolling is there.

## Rationale
Smooth scrolling feels nice, and a paid product whose entire existence relies on smooth scrolling deserves this feature :]

## Additional info
–

**Comment by Pikachews** [comment]
What is your means of testing this? I don't seem to have any framerate/smoothness issues when scrolling.

Testing on the Mac Mouse Fix home page on Chrome with Frame Rendering Stats enabled, scrolling the page seems to render at my display's refresh rate (170 Hz).
![image](https://github.com/noah-nuebling/mac-mouse-fix/assets/5668416/0f8b3d1a-03bf-4743-b419-45300b425030)

When I move the window to my lower refresh rate display, it renders at the same FPS as the refresh rate (60 Hz).
![image](https://github.com/noah-nuebling/mac-mouse-fix/assets/5668416/4769ebf1-d1f5-4e2c-95ed-c7c4863c8bd4)

And on the MacBook's display:
<img width="287" alt="image" src="https://github.com/noah-nuebling/mac-mouse-fix/assets/5668416/d496d66a-d8de-46e2-8450-cb5716e8f865">

**Comment by neel04** [comment]
I don't have a quantitative way of measuring this unfortunately - but its highly visible. I think the problem is that somehow, the scrolling happens in discrete chunks rather than a smooth continous curve.

If I turn the smoothness down (from `High -> Off`) then the scrolling happens very smoothly, counterintuitively. 

Its as if with `High` smoothness, the interpolation itself isn't very continous - it feels discrete. Whereas switching smoothness to `Off` and relying on macOS to handle it feels very smooth, but lacks the scrolling inertia I'm used to.

**Comment by noah-nuebling** [comment]
Is this better under 3.0.3? 

It should fix a bug in the code for changing the refresh rate of the scroll animations when using multlple displays.

**Comment by neel04** [comment]
Just updated - that is *so* much better. Thank you so much! 🔥
