### ISSUE TITLE
Scroll wheel click issues in chrome

### ISSUE THREAD

**Issue by iklaww** [noah-nuebling/mac-mouse-fix#104]
Hi! I've recently had to update to a beta due to the certificate being removed and not being able to use the app anymore. I've noticed that the scroll wheel doesn't open and close links and tabs in chrome anymore. It used to work in older versions, is it intended?

Thanks!

**Comment by noah-nuebling** [comment]
Hi @iklaww, thanks for reaching out! 

Does it work when you choose ‘Middle Click’ as an action?

Middle clicks open links in a new tab in Safari and other browsers.

![image](https://user-images.githubusercontent.com/40808343/117326204-baa81280-ae91-11eb-97b0-e216c47e523f.png)

**Comment by iklaww** [comment]
Oh yeah! You're totally right. It does feel less responsive than the original though (i'm guessing the app is waiting a set amount of time for other types of inputs). Thank you!

**Comment by noah-nuebling** [comment]
Hey no problem glad to help! :)

Yes you're right in your thoughts and observations. There is an extra delay where it's waiting for you to double click. If you delete the "Double Click" action that should remove the delay.
