### ISSUE TITLE
Can you please add copy and paste support for the side buttons?  [enhancement]

### ISSUE THREAD

**Issue by samueljim** [noah-nuebling/mac-mouse-fix#105]
## Description
This is all I want man.
I have always used my mouse side buttons to copy and paste text and it's the only thing my mouse is missing.

## Rationale
This is the best mouse software on the mac. Is it possible to send keyboard commands? 

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi Sam thanks for reaching out. I'm happy that you think Mac Mouse Fix is the best mouse software for Macs! :) What do you like about it if you mind sharing?

Oh and regarding your question - you're in luck! You can remap to keyboard shortcuts in the [2.0.0 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases).

Does that solve your problem or do you have something different in mind?

**Comment by samueljim** [comment]
@noah-nuebling You are amazing

**Comment by noah-nuebling** [comment]
Aw I'm blushing, thank you!
