### ISSUE TITLE
After macos update scroll doesn't work [bug]

### ISSUE THREAD

**Issue by unepod** [noah-nuebling/Mac-Mouse-Fix#1065]
## Description

I've updated to Sonoma 14.6 (23G80) and the scroll stopped working when it'n checked in the app. If I uncheck it (back to macos control) - works fine.

## Steps to reproduce

1. Update to Sonoma 14.6 (23G80).
2. Try scrolling in Safari or Finder window.

## Context

Mac Mouse Fix Version: 2.2.4
macOS Version: Sonoma 14.6 (23G80)
Mouse Model: MX Anywhere 3 for Mac

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by Technojo01** [comment]
same as my #1062 ! I am using MOS for the moment, scrolling still work.

**Comment by unepod** [comment]
Seems to work now. Not sure what changed. Maybe re-start of MacOS was needed. Closing this.
