### ISSUE TITLE
Scroll stopped working since macOS 14.6.1 [bug]

### ISSUE THREAD

**Issue by patricorgi** [noah-nuebling/Mac-Mouse-Fix#1080]
## Description

When scroll is enabled in MMF, scrolling with mouse completely stops working.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.4
macOS Version: 14.6.1
Mouse Model: Logitech G502

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by spenrose** [comment]
Seeing the same thing. If I kill the app and scrolling works again.

Magic Mouse Fix Version: 3.0.2 (22635)
macOS Version: 14.6.1
Mouse Model: Logitech Pro Superlite

**Comment by tydia** [comment]
same

**Comment by xsd08tfu** [comment]
I am seeing the same problem, but have narrowed it down to only being when scrolling smoothness is enabled. All other settings work.

**Comment by noah-nuebling** [comment]
Hey guys, thanks for the feedback. Is anybody still experiencing this?

**Comment by patricorgi** [comment]
I'm no longer experiencing this. I'm also in macOS 15 now.
