### ISSUE TITLE
Unable to switch direction using mouse Middle Button to swap (drag) between Spaces. [bug]

### ISSUE THREAD

**Issue by jlnunez89** [noah-nuebling/Mac-Mouse-Fix#1087]
## Description

In new version 3.0.2 I set up a Middle Button Click and Drag gesture, set it up to Spaces and Mission Control and, while it does work, I'm unable to switch the direction of the drag.

I tried going into the Scrolling tab and switching there but it does nothing. 
Also looked for an option in the Options button but no luck.

## Steps to reproduce

1) Use a mouse with a middle button (I have a Logitech G602)
2) Add a middle Click and Drag gesture (hover over the   and click and drag).
3) Set up the added gesture to Spaces and Mission Control.
4) Click and drag with the middle button (on a screen that has 2 or more Spaces set up), notice the direction of the drag.
5) Try to change the direction by setting any of the current app's options... ? (none seem to be available or take effect).

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: Sonoma 14.6.1
Mouse Model: Logitech G602

## Additional Comments
In version 2.3.3 (I have another mac which I haven't updated to 3.0.2 yet), it seems like the direction wasn't configurable either, but the default direction was the opposite, making it painful to use the new version with the same gesture I'm used to.

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there, thanks for reaching out @jlnunez89! The direction of the Click-and-Drags in MMF can be set under:

System Settings > Mouse > Natural Scrolling

I totally understand that this is very confusing, and I plan to add a dedicated setting into MMF at some point.

**Comment by jlnunez89** [comment]
Thanks for the answer! I confirmed that actually works. However, if I do toggle that setting, my actual wheel scrolling also reverses, so now I have the opposite problem: the Click and Drag direction I wanted and not the scroll direction I wanted :/  

EDIT: Never mind, I see how I can make it work: enable the `Natural Scrolling` setting in the System Settings and then on MMF, toggle the `Reverse Scrolling` setting under Scrolling tab.

**Comment by jlnunez89** [comment]
Closing as workaround was found. Thanks!
