### ISSUE TITLE
Prefpane doesn't load on Catalina

### ISSUE THREAD

**Issue by saq1610** [noah-nuebling/mac-mouse-fix#11]
<img width="780" alt="Screen Shot 2019-10-03 at 10 34 12 PM" src="https://user-images.githubusercontent.com/10332349/66162151-12cfc080-e62e-11e9-9f50-39808ebf80ab.png">

This is what happens after installing the prefpane on the latest Catalina beta (19A587c), but after installing and trying to open it for the first time System Preferences force closed on me too

**Comment by saq1610** [comment]
Tried opening once more which led to another system preferences crash. Was able to get a [crash log](https://pastebin.com/tnDgiQXC) this time though so might help with pinpointing the issue

**Comment by kode54** [comment]
I, too, have logged a crash. Same location. It occurred when I installed it. It simply failed to load afterward, so I removed it.

https://gist.github.com/kode54/8284a238c418a676a02747849e05a809

E: It appears that `CFMessagePortCreateLocal` is failing, and returning an unchecked null pointer.

**Comment by w0lfschild** [comment]
Ditto
