### ISSUE TITLE
Mac Mouse Fix Click & Drag stops working out of no where [bug]

### ISSUE THREAD

**Issue by evkaw** [noah-nuebling/mac-mouse-fix#111]
## Description

Sometimes just out of no where, the click and drag feature specifically stops working but the others still work. Most of the time, I need to delete the feature with the (-) button because turning mac mouse fix on and off doesn't work. But sometimes, that doesn't work either. It started happening after the last update I think, but might not be the reason. Probably the reason isn't my mouse either because I tried another mouse but still happened.

## Context

Mac Mouse Fix Version: 2.0.0 Beta 9
macOS Version: macOS Big Sur 11.2.3
Mouse Model: Logitech M317

**Comment by noah-nuebling** [comment]
Hey @evka745, thanks for reaching out!
I just pushed a [new update](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0-Beta-10) where I addressed a possible reason for your issues. Does that improve anything for you?

**Comment by evulhotdog** [comment]
So this also happens with another mouse related app, SmoothScroll when the machine is under heavy load it just completely stops working until you restart the app.

**Comment by evkaw** [comment]
> Hey @evka745, thanks for reaching out!
> I just pushed a [new update](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0-Beta-10) where I addressed a possible reason for your issues. Does that improve anything for you?

I’ll try later and let you know, thank you

**Comment by noah-nuebling** [comment]
Hey guys, I'm closing this now, assuming it's been resolved for you. Just reopen it if you're still having issues. (Or leave comment telling me to reopen it if that's not possible)
