### ISSUE TITLE
The app doesn't work well with iPhone Mirroring [bug]

### ISSUE THREAD

**Issue by MapleLeaf14** [noah-nuebling/Mac-Mouse-Fix#1122]
## Description

The scrolling is a mess, unfortunately :(

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.4
macOS Version: Sequoia
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by chumion** [comment]
Also not working in `Settings -> Your account name -> iCloud -> Manage`

The issue persists on version 3.0.3

**Comment by noah-nuebling** [comment]
Thanks for the feedback. Please see #1015.
