### ISSUE TITLE
【Crash on first launch】Mac Mouse Fix crashes while launching for the first time. [bug]

### ISSUE THREAD

**Issue by huangwei4478** [noah-nuebling/Mac-Mouse-Fix#1143]
## Description

I just downloaded Mac Mouse Fix from Github and Gumroud, 
Should be latest 3.0.3 version

Then this app crashes while launching for the first time.

## Steps to reproduce

1. Download app from Github release page or Gumroud
2. Double click Mac Mouse Fix app from /Applications
3. It crashes.

## Context

Mac Mouse Fix Version: 3.0.3
macOS Version: 14.5
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Mac Mouse Fix [4899]
Path:                  /Applications/Mac Mouse Fix.app/Contents/MacOS/Mac Mouse Fix
Identifier:            com.nuebling.mac-mouse-fix
Version:               3.0.3 (22854)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-10-16 10:37:35.8752 +0800
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        D2C19B8B-C97A-2125-633A-563A2C2769AC

Sleep/Wake UUID:       0170A76E-8168-43A9-A633-837582B68596

Time Awake Since Boot: 3100 seconds
Time Since Wake:       3010 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Mac Mouse Fix [4899]

Application Specific Information:
abort() called

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18590aa60 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x185942c20 pthread_kill + 288
2   libsystem_c.dylib             	       0x18584fa30 abort + 180
3   libc++abi.dylib               	       0x1858f9d08 abort_message + 132
4   libc++abi.dylib               	       0x1858e9fc0 demangling_terminate_handler() + 348
5   libobjc.A.dylib               	       0x1855881d0 _objc_terminate() + 144
6   libc++abi.dylib               	       0x1858f90cc std::__terminate(void (*)()) + 16
7   libc++abi.dylib               	       0x1858fc5f8 __cxa_rethrow + 204
8   libobjc.A.dylib               	       0x1855a22d4 objc_exception_rethrow + 44
9   UIFoundation                  	       0x18a5e9468 UINibDecoderDecodeObjectForValue + 1364
10  UIFoundation                  	       0x18a5e8efc -[UINibDecoder decodeObjectForKey:] + 312
11  AppKit                        	       0x1892c9648 -[NSNib _instantiateNibWithExternalNameTable:options:] + 440
12  AppKit                        	       0x1892c93c8 -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 132
13  AppKit                        	       0x189c70194 -[NSStoryboard _instantiateMainMenu:] + 164
14  AppKit                        	       0x18924a1c8 NSApplicationMain + 600
15  dyld                          	       0x1855ba0e0 start + 2360

Thread 1:
0   libsystem_pthread.dylib       	       0x18593dd20 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18593dd20 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18593dd20 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x18593dd20 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x00000001858fe2cb   x5: 0x000000016f3d3410   x6: 0x000000000000006e   x7: 0x0000000000000000
    x8: 0x620943d4b2dd868a   x9: 0x620943d55faa4a8a  x10: 0x0000000000000200  x11: 0x000000000000000b
   x12: 0x0000000000000000  x13: 0x00000000001ff800  x14: 0x00000000000007fb  x15: 0x00000000b8210067
   x16: 0x0000000000000148  x17: 0x00000001f7b31928  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x00000001ed77cc00  x21: 0x0000000000000103  x22: 0x00000001ed77cce0  x23: 0x0000000000000001
   x24: 0x00000001ec56f000  x25: 0x00000001ef440000  x26: 0x00000001ec56f000  x27: 0x00000001ec56f000
   x28: 0x00000001ec56f000   fp: 0x000000016f3d3380   lr: 0x0000000185942c20
    sp: 0x000000016f3d3360   pc: 0x000000018590aa60 cpsr: 0x40001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x1012a4000 -        0x1012ebfff org.sparkle-project.Sparkle (1.27.3) <e3f78d09-18f1-3c35-9a93-0a05559979b9> /Applications/Mac Mouse Fix.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x100a2c000 -        0x100c4ffff com.nuebling.mac-mouse-fix (3.0.3) <167c1c95-5b0a-3972-bf03-fdcb8374fec0> /Applications/Mac Mouse Fix.app/Contents/MacOS/Mac Mouse Fix
       0x185901000 -        0x18593bffb libsystem_kernel.dylib (*) <9b8b53f9-e2b6-36df-98e9-28d8fca732f2> /usr/lib/system/libsystem_kernel.dylib
       0x18593c000 -        0x185948fff libsystem_pthread.dylib (*) <386b0fc1-7873-3328-8e71-43269fd1b2c7> /usr/lib/system/libsystem_pthread.dylib
       0x1857d9000 -        0x185857ff7 libsystem_c.dylib (*) <05b44e93-dffc-3bd8-90ab-fd97cb73f171> /usr/lib/system/libsystem_c.dylib
       0x1858e5000 -        0x185900ffb libc++abi.dylib (*) <4ac7c5cd-3746-3a53-aad6-c231e183b705> /usr/lib/libc++abi.dylib
       0x185564000 -        0x1855b3d83 libobjc.A.dylib (*) <b326b2c3-1069-3d17-b49d-9dcb24efec6f> /usr/lib/libobjc.A.dylib
       0x18a583000 -        0x18a737fff com.apple.UIFoundation (1.0) <f5ec41b2-8f0d-382b-943b-63785c82035d> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
       0x189246000 -        0x18a582fff com.apple.AppKit (6.9) <61f710be-9132-3cc2-883d-066365fba1ad> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1855b4000 -        0x18563ca17 dyld (*) <37bbc384-0755-31c7-a808-0ed49e44dd8e> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x1859a4000 -        0x185e7cfff com.apple.CoreFoundation (6.9) <84b539d5-22c9-3f8c-84c8-903e9c7b8d29> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x186af9000 -        0x187756fff com.apple.Foundation (6.9) <99e0292d-7873-3968-9c9c-5955638689a5> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          432K       23 
CoreGraphics                        32K        2 
CoreServices                       176K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.3G       36 
MALLOC guard page                  192K       12 
STACK GUARD                       56.1M        5 
Stack                             10.1M        5 
VM_ALLOCATE                         32K        2 
__AUTH                            1119K      237 
__AUTH_CONST                      21.8M      414 
__CTF                               824        1 
__DATA                            8446K      403 
__DATA_CONST                      21.1M      420 
__DATA_DIRTY                      1208K      134 
__FONT_DATA                          4K        1 
__LINKEDIT                       533.5M        3 
__OBJC_RO                         71.9M        1 
__OBJC_RW                         2199K        1 
__TEXT                           501.5M      437 
dyld private memory                272K        2 
mapped file                      158.3M       12 
shared memory                     1360K       13 
===========                     =======  ======= 
TOTAL                              2.7G     2167 

-----------
Full Report
-----------

{"app_name":"Mac Mouse Fix","timestamp":"2024-10-16 10:37:36.00 +0800","app_version":"3.0.3","slice_uuid":"167c1c95-5b0a-3972-bf03-fdcb8374fec0","build_version":"22854","platform":1,"bundleID":"com.nuebling.mac-mouse-fix","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.5 (23F79)","roots_installed":0,"name":"Mac Mouse Fix","incident_id":"F0F82150-BF3C-4EAA-8B1A-B89AD6BF7FB5"}
{
  "uptime" : 3100,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,2",
  "coalitionID" : 2079,
  "osVersion" : {
    "train" : "macOS 14.5",
    "build" : "23F79",
    "releaseType" : "User"
  },
  "captureTime" : "2024-10-16 10:37:35.8752 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "F0F82150-BF3C-4EAA-8B1A-B89AD6BF7FB5",
  "pid" : 4899,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-10-16 10:37:28.9725 +0800",
  "procStartAbsTime" : 75154939935,
  "procExitAbsTime" : 75320417960,
  "procName" : "Mac Mouse Fix",
  "procPath" : "\/Applications\/Mac Mouse Fix.app\/Contents\/MacOS\/Mac Mouse Fix",
  "bundleInfo" : {"CFBundleShortVersionString":"3.0.3","CFBundleVersion":"22854","CFBundleIdentifier":"com.nuebling.mac-mouse-fix"},
  "storeInfo" : {"deviceIdentifierForVendor":"B646D042-AB1E-5754-9CC3-27E219B3EF24","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.nuebling.mac-mouse-fix",
  "crashReporterKey" : "D2C19B8B-C97A-2125-633A-563A2C2769AC",
  "codeSigningID" : "com.nuebling.mac-mouse-fix",
  "codeSigningTeamID" : "LM5Z78756B",
  "codeSigningFlags" : 570520337,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"fyMD1f17v6n9AwCRW+D\/l78DAJH9e8Go\/w9f1sADX9YQKYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkVDg\/5e\/AwCR\/XvBqP8PX9bAA1\/WcAqA0g=="},
  "wakeTime" : 3010,
  "sleepWakeUUID" : "0170A76E-8168-43A9-A633-837582B68596",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"Mac Mouse Fix","byPid":4899},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":2},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "lastExceptionBacktrace" : [{"imageOffset":996064,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":11},{"imageOffset":108424,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":6},{"imageOffset":36800,"symbol":"-[NSConcreteData length]","symbolLocation":0,"imageIndex":12},{"imageOffset":69044,"imageIndex":1},{"imageOffset":68328,"imageIndex":1},{"imageOffset":44816,"symbol":"CALLING_SOME_+initialize_METHOD","symbolLocation":24,"imageIndex":6},{"imageOffset":44040,"symbol":"initializeNonMetaClass","symbolLocation":672,"imageIndex":6},{"imageOffset":162812,"symbol":"initializeAndMaybeRelock(objc_class*, objc_object*, locker_mixin<lockdebug::lock_mixin<objc_lock_base_t>>&, bool)","symbolLocation":164,"imageIndex":6},{"imageOffset":42436,"symbol":"lookUpImpOrForward","symbolLocation":892,"imageIndex":6},{"imageOffset":40804,"symbol":"_objc_msgSend_uncached","symbolLocation":68,"imageIndex":6},{"imageOffset":541796,"symbol":"-[NSClassSwapper initWithCoder:]","symbolLocation":768,"imageIndex":8},{"imageOffset":418224,"symbol":"UINibDecoderDecodeObjectForValue","symbolLocation":668,"imageIndex":7},{"imageOffset":417532,"symbol":"-[UINibDecoder decodeObjectForKey:]","symbolLocation":312,"imageIndex":7},{"imageOffset":76596,"symbol":"-[NSNibConnector initWithCoder:]","symbolLocation":88,"imageIndex":8},{"imageOffset":76420,"symbol":"-[NSNibOutletConnector initWithCoder:]","symbolLocation":336,"imageIndex":8},{"imageOffset":418224,"symbol":"UINibDecoderDecodeObjectForValue","symbolLocation":668,"imageIndex":7},{"imageOffset":418616,"symbol":"UINibDecoderDecodeObjectForValue","symbolLocation":1060,"imageIndex":7},{"imageOffset":417532,"symbol":"-[UINibDecoder decodeObjectForKey:]","symbolLocation":312,"imageIndex":7},{"imageOffset":72480,"symbol":"-[NSIBObjectData initWithCoder:]","symbolLocation":136,"imageIndex":8},{"imageOffset":418224,"symbol":"UINibDecoderDecodeObjectForValue","symbolLocation":668,"imageIndex":7},{"imageOffset":417532,"symbol":"-[UINibDecoder decodeObjectForKey:]","symbolLocation":312,"imageIndex":7},{"imageOffset":538184,"symbol":"-[NSNib _instantiateNibWithExternalNameTable:options:]","symbolLocation":440,"imageIndex":8},{"imageOffset":537544,"symbol":"-[NSNib _instantiateWithOwner:options:topLevelObjects:]","symbolLocation":132,"imageIndex":8},{"imageOffset":10658196,"symbol":"-[NSStoryboard _instantiateMainMenu:]","symbolLocation":164,"imageIndex":8},{"imageOffset":16840,"symbol":"NSApplicationMain","symbolLocation":600,"imageIndex":8},{"imageOffset":24800,"symbol":"start","symbolLocation":2360,"imageIndex":9}],
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":85533,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":6535766731},{"value":6161249296},{"value":110},{"value":0},{"value":7064252071320323722},{"value":7064252074219424394},{"value":512},{"value":11},{"value":0},{"value":2095104},{"value":2043},{"value":3089170535},{"value":328},{"value":8450677032},{"value":0},{"value":6},{"value":8279018496,"symbolLocation":0,"symbol":"_main_thread"},{"value":259},{"value":8279018720,"symbolLocation":224,"symbol":"_main_thread"},{"value":1},{"value":8260087808,"symbolLocation":0,"symbol":"OBJC_IVAR_$__NSIdentifierDifferMovePair._fromIndex"},{"value":8309178368},{"value":8260087808,"symbolLocation":0,"symbol":"OBJC_IVAR_$__NSIdentifierDifferMovePair._fromIndex"},{"value":8260087808,"symbolLocation":0,"symbol":"OBJC_IVAR_$__NSIdentifierDifferMovePair._fromIndex"},{"value":8260087808,"symbolLocation":0,"symbol":"OBJC_IVAR_$__NSIdentifierDifferMovePair._fromIndex"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6536047648},"cpsr":{"value":1073745920},"fp":{"value":6161249152},"sp":{"value":6161249120},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6535817824,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":39520,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":2},{"imageOffset":27680,"symbol":"pthread_kill","symbolLocation":288,"imageIndex":3},{"imageOffset":485936,"symbol":"abort","symbolLocation":180,"imageIndex":4},{"imageOffset":85256,"symbol":"abort_message","symbolLocation":132,"imageIndex":5},{"imageOffset":20416,"symbol":"demangling_terminate_handler()","symbolLocation":348,"imageIndex":5},{"imageOffset":147920,"symbol":"_objc_terminate()","symbolLocation":144,"imageIndex":6},{"imageOffset":82124,"symbol":"std::__terminate(void (*)())","symbolLocation":16,"imageIndex":5},{"imageOffset":95736,"symbol":"__cxa_rethrow","symbolLocation":204,"imageIndex":5},{"imageOffset":254676,"symbol":"objc_exception_rethrow","symbolLocation":44,"imageIndex":6},{"imageOffset":418920,"symbol":"UINibDecoderDecodeObjectForValue","symbolLocation":1364,"imageIndex":7},{"imageOffset":417532,"symbol":"-[UINibDecoder decodeObjectForKey:]","symbolLocation":312,"imageIndex":7},{"imageOffset":538184,"symbol":"-[NSNib _instantiateNibWithExternalNameTable:options:]","symbolLocation":440,"imageIndex":8},{"imageOffset":537544,"symbol":"-[NSNib _instantiateWithOwner:options:topLevelObjects:]","symbolLocation":132,"imageIndex":8},{"imageOffset":10658196,"symbol":"-[NSStoryboard _instantiateMainMenu:]","symbolLocation":164,"imageIndex":8},{"imageOffset":16840,"symbol":"NSApplicationMain","symbolLocation":600,"imageIndex":8},{"imageOffset":24800,"symbol":"start","symbolLocation":2360,"imageIndex":9}]},{"id":85703,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}],"threadState":{"x":[{"value":6161805312},{"value":5635},{"value":6161268736},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6161805312},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6536027424},"far":{"value":0}}},{"id":85704,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}],"threadState":{"x":[{"value":6162378752},{"value":10499},{"value":6161842176},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6162378752},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6536027424},"far":{"value":0}}},{"id":85714,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}],"threadState":{"x":[{"value":6162952192},{"value":18951},{"value":6162415616},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6162952192},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6536027424},"far":{"value":0}}},{"id":85724,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":3}],"threadState":{"x":[{"value":6163525632},{"value":0},{"value":6162989056},{"value":0},{"value":278532},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6163525632},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":6536027424},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4314513408,
    "CFBundleShortVersionString" : "1.27.3",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 294912,
    "uuid" : "e3f78d09-18f1-3c35-9a93-0a05559979b9",
    "path" : "\/Applications\/Mac Mouse Fix.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/A\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "1.108"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4305633280,
    "CFBundleShortVersionString" : "3.0.3",
    "CFBundleIdentifier" : "com.nuebling.mac-mouse-fix",
    "size" : 2244608,
    "uuid" : "167c1c95-5b0a-3972-bf03-fdcb8374fec0",
    "path" : "\/Applications\/Mac Mouse Fix.app\/Contents\/MacOS\/Mac Mouse Fix",
    "name" : "Mac Mouse Fix",
    "CFBundleVersion" : "22854"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6535778304,
    "size" : 241660,
    "uuid" : "9b8b53f9-e2b6-36df-98e9-28d8fca732f2",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6536019968,
    "size" : 53248,
    "uuid" : "386b0fc1-7873-3328-8e71-43269fd1b2c7",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6534565888,
    "size" : 520184,
    "uuid" : "05b44e93-dffc-3bd8-90ab-fd97cb73f171",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6535663616,
    "size" : 114684,
    "uuid" : "4ac7c5cd-3746-3a53-aad6-c231e183b705",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6531989504,
    "size" : 327044,
    "uuid" : "b326b2c3-1069-3d17-b49d-9dcb24efec6f",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6616002560,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.UIFoundation",
    "size" : 1789952,
    "uuid" : "f5ec41b2-8f0d-382b-943b-63785c82035d",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIFoundation.framework\/Versions\/A\/UIFoundation",
    "name" : "UIFoundation",
    "CFBundleVersion" : "909.7"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6595829760,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 20172800,
    "uuid" : "61f710be-9132-3cc2-883d-066365fba1ad",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2487.60.105"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6532317184,
    "size" : 559640,
    "uuid" : "37bbc384-0755-31c7-a808-0ed49e44dd8e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6536445952,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5083136,
    "uuid" : "84b539d5-22c9-3f8c-84c8-903e9c7b8d29",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "2503.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6554619904,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 12967936,
    "uuid" : "99e0292d-7873-3968-9c9c-5955638689a5",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "2503.1"
  }
],
  "sharedCache" : {
  "base" : 6531563520,
  "size" : 4220698624,
  "uuid" : "3406ad1b-2469-30eb-9863-5dce861e6dea"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          432K       23 \nCoreGraphics                        32K        2 \nCoreServices                       176K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.3G       36 \nMALLOC guard page                  192K       12 \nSTACK GUARD                       56.1M        5 \nStack                             10.1M        5 \nVM_ALLOCATE                         32K        2 \n__AUTH                            1119K      237 \n__AUTH_CONST                      21.8M      414 \n__CTF                               824        1 \n__DATA                            8446K      403 \n__DATA_CONST                      21.1M      420 \n__DATA_DIRTY                      1208K      134 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       533.5M        3 \n__OBJC_RO                         71.9M        1 \n__OBJC_RW                         2199K        1 \n__TEXT                           501.5M      437 \ndyld private memory                272K        2 \nmapped file                      158.3M       12 \nshared memory                     1360K       13 \n===========                     =======  ======= \nTOTAL                              2.7G     2167 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "245b8475bb6eb6aabc794a99cf8c30f88298d469",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {

      },
      "deploymentId" : 240000010
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c47ab4cc-c9c3-4b5d-a87c-e2433ce02597",
      "experimentId" : "6639bc6ba73d460582162323",
      "deploymentId" : 400000006
    },
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000007
    }
  ]
}
}

Model: MacBookPro18,2, BootROM 10151.121.1, proc 10:8:2 processors, 32 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: Redmi 215 NF, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Display: Color LCD, 3456 x 2234 Retina, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Apr  4 2024 20:37:43 version 20.103.14.0.8.7.174 FWID 01-95f1e684
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en4
Network Service: Wi-Fi, AirPort, en0
Network Service: iPhone 2, Ethernet, en11
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: Razer Lancehead Tournament Edition
USB Device: USB Billboard Device
USB Device: Razer BlackWidow V3
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: iPhone
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

–

**Comment by huangwei4478** [comment]
![image](https://github.com/user-attachments/assets/cc2529ae-e420-4cae-a988-f05bcbfe16af)
Crashes on the first launch, looks like some Storyboard decoder issue?

**Comment by noah-nuebling** [comment]
Hello @huangwei4478, thank you for posting the crash report!

To me it looks like the crash does not come from my code and is instead some bug with Apple's UI Framework. The code that crashes is the 'Storyboard decoding' which is defined by Apple. Maybe there's something weird about how I created the Storyboard for the app, but I don't think it should ever crash the decoder.

Have you submitted the crash to Apple? I think they might be able to do more with it.

Does the issue resolve itself when you restart the computer and try again?
If not, I'd be glad to give you a refund. Please [click here](https://redirect.macmousefix.com/?target=mmf-apply-for-refund) to apply.

Thank you! And I hope this helps a bit. If the issue doesn't resolve itself, or if you have ideas for how I could address this error (instead of just hoping Apple fixes it), please let me know. Thank you.

**Comment by huangwei4478** [comment]
Hello @noah-nuebling, sorry for this late reply, 
I tried this tool in another macOS machine which worked fine with this tool, 

so no need to refund, beside this app is free in China mainland, I really really appreciate this.

Above launch crashes should be some machine-specific issue, so kindly ignore this.
