### ISSUE TITLE
Doesn't seem to work at all

### ISSUE THREAD

**Issue by variable** [noah-nuebling/mac-mouse-fix#13]

**Comment by noah-nuebling** [comment]
Hi, variable thank you for your feedback. I'm sorry to hear that you're having issues with Mac Mouse Fix. Are you using Catalina? I haven't been able to update yet, but I've heard about the Preference Pane not opening on Catalina from some people. I will test Mac Mouse Fix with Catalina as soon as possible. 
If you are experiencing a different issue it would be awesome if you could describe it to me in more detail. Thank you!

**Comment by noah-nuebling** [comment]
Mac Mouse Fix should now work under Catalina. Closing this issue.
