### ISSUE TITLE
Holding middle click makes app fullscreen instead of showing desktop on macOS 12 beta 1 [bug]

### ISSUE THREAD

**Issue by TheMadRuffian** [noah-nuebling/mac-mouse-fix#134]
## Description

On macOS Monterey, long pressing middle click, when programed to show desktop, makes the foreground app fullscreen.  When programed with other options like app expose, launch pad, or others, they work fine. It also worked just fine on BigSur.

macOS version: 12 beta 1
App version: 1.0.4

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 1.0.4
macOS Version: 12 beta 1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey, thanks for the feedback!

It works fine on my Montery, so I assume it was an issue with the Monterey Beta.

Let me know if you still have this issue.
