### ISSUE TITLE
Completely stopped working [bug]

### ISSUE THREAD

**Issue by FraserEmbrey** [noah-nuebling/mac-mouse-fix#135]
## Description

Unsure why but it completely stopped working, I have checked the enable button and updated and reinstalled macOS and I had the same issue.

## Steps to reproduce

1. Install Mac Mouse Fix
2. Open, enable accessibility and restart app
3. Check enable switch
4. Try and use any custom settings

## Context

Mac Mouse Fix Version: 2.0.0 Beta 11
macOS Version: 12.0 and 11.4
Mouse Model: Logitech MX3 (for Mac)

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by FraserEmbrey** [comment]
Seems like it won't recognise any clicks, if I try to assign buttons only the primary and secondary buttons are seen. Also won't invert scroll direction or affect tracking.

Does it require Rosetta?

In general the UI in v.2 is great and very intuitive, not sure why "Smooth scrolling" has a colon at the end.

I think "Three Finger Swipe" is not very clear what it does, Apple calls it "Swipe between full-screen apps" so you could copy them or perhaps "workspaces" is more accurate.

I feel like the scrolling section could benefit from a little more separation and a heading.

**Comment by nghtstr** [comment]
I agree that the UI in V2 is fantastic and very intuitive. However, I am also having the same issue; it is not affecting anything. I have a Seedna Vertical Bluetooth Mouse, and when I was running Version 1 in Big Sur, it was working just fine. When I upgraded to Monterey Beta 1, it stopped working all together. So I upgraded MMF to V2 beta 11, and it is still not affecting the mouse usage at all.

I am running on a MBP 2016 15" i9 2.9 GHz machine. Not sure if that helps at all.

My mouse is a Seenda Bluetooth Vertical mouse.

**Comment by gferreroferri** [comment]
Same issue with M1 MBAir with macOS 12 public beta and MX Master 3

**Comment by gferreroferri** [comment]
Still not working on M1 MacBook Air with latest update :(

**Comment by noah-nuebling** [comment]
Is anyone still having this issue?

**Comment by nghtstr** [comment]
No, the application seems to be working great for me (running 2.0)
