### ISSUE TITLE
Caps lock on, make three finger swipe unusable. [bug]

### ISSUE THREAD

**Issue by ChienWeiChek** [noah-nuebling/mac-mouse-fix#136]
## Description

When caps lock is on, middle button click and drag malfunction, which is the three finger swipe.

## Steps to reproduce

1. On your caps locks
2. Click middle button and swipe

## Context

Mac Mouse Fix Version: 2.0.0 Beta 11
macOS Version: macOs Big Sur 11.3
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi Chien, thanks for your feedback!

Your issue should be resolved in the [latest 2.0.0 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)

**Comment by ChienWeiChek** [comment]
Yeah, is was fixed. SUPER NICE APPLICATION

**Comment by noah-nuebling** [comment]
Thanks, glad you like it! :D
