### ISSUE TITLE
希望在鼠标侧键功能上增加修饰键 [enhancement]

### ISSUE THREAD

**Issue by JavenYan** [noah-nuebling/mac-mouse-fix#139]
## Description
希望在鼠标侧键功能上增加修饰键，实现control、option、command side buttons=mission control、Exposé功能。

## Rationale
希望把mission control、Exposé、虚拟桌面集成到一个鼠标侧键上。因为很多软件都会用到鼠标中键，比如CAD。

## Additional info
–

**Comment by noah-nuebling** [comment]
您好，感谢您的反馈！这在新的 [Mac Mouse Fix 2](https://mousefix.org) 中应该是可能的！


如果您还有其他问题，请告诉我
