### ISSUE TITLE
Not working on M1 with macOS 12 Monterrey Beta [bug]

### ISSUE THREAD

**Issue by gferreroferri** [noah-nuebling/mac-mouse-fix#144]
## Description

App executes but it does not make any changes to the mouse

## Steps to reproduce

Execute app in macOS 12 Monterrey on MacBook Air with M1 chip

## Context

Mac Mouse Fix Version: 2.0.0 Beta 12 (6195)
macOS Version: 12.0 beta 21A5268h
Mouse Model: Logitech MX3

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by tangerine1202** [comment]
Same issue with MBAir 2020 (intel chip) with macOS 12 public beta and G603

Mac Mouse Fix Version: 2.0.0 Beta 12 (6195)
macOS Version: 12.0 beta 21A5284e
Mouse Model: Logitech G603

**Comment by CavalloneChen** [comment]
Same issue here with MBP 2016 intel chip with macOS 12 public beta 3 and Microsoft  Ergonomic Mouse.

**Comment by CavalloneChen** [comment]
> Same issue here with MBP 2016 intel chip with macOS 12 public beta 3 and Microsoft Ergonomic Mouse.

It is now working properly in public beta 4.

**Comment by tangerine1202** [comment]
> Same issue with MBAir 2020 (intel chip) with macOS 12 public beta and G603
> 
> Mac Mouse Fix Version: 2.0.0 Beta 12 (6195)
> macOS Version: 12.0 beta 21A5284e
> Mouse Model: Logitech G603

also working properly on MBAir 2020 (intel chip) in public beta 4

**Comment by tomasz-adamczyk** [comment]
Not working with Intel iMac (21A5294g)

**Comment by tomasz-adamczyk** [comment]
Works with 21A5304g.

**Comment by gferreroferri** [comment]
yes, working now on 21A5304g

**Comment by ramirez** [comment]
Not working with MacBook Pro M1. App starts but does nothing.

**Comment by noah-nuebling** [comment]
@ramirez Does version 1 work for you? If both version [1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/1.0.4) and [2](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0) don't work, that would be an important hint as to what's going on. Thanks!

**Comment by HiramTheHero** [comment]
@noah-nuebling I also have a MacBook Pro M1. For me, both version 2 and version 1 execute the app but do not make any changes to the mouse.

**Comment by ramirez** [comment]
> 

Same here. Either version do nothing.

**Comment by noah-nuebling** [comment]
Hi @ramirez!
If you run `launchctl enable gui/$UID/mouse.fix.helper` in the Terminal, does that fix the issue? See https://github.com/noah-nuebling/mac-mouse-fix/issues/192#issuecomment-1017130096 for context.

If not, it would be awesome if you opened a [Bug Report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report), and attached some console logs of when you try to enable Mac Mouse Fix. Thx!
