### ISSUE TITLE
Preferences window opens up every time the computer is booted up. [bug]

### ISSUE THREAD

**Issue by kushagr-m** [noah-nuebling/mac-mouse-fix#148]
## Description

The preferences window for Mac Mouse Fix opens every time that the computer is booted up, in the old .prefpane version, Mac Mouse Fix would be enabled on boot however the preferences window would not show up. Is there a way to restore this previous behaviour?

## Steps to reproduce

1. Turn on / fully restart Mac.
2. Watch as the Mouse Fix window opens up.

## Context

Mac Mouse Fix Version: 2.0.0 Beta 12
macOS Version: 11.5

**Comment by noah-nuebling** [comment]
Hi there, @theKKCD, thanks for reaching out!

I don't know why the MMF preferences might be opening up when you boot your computer. There isn't any code in MMF which might cause such behavior as far as I know.

So my guess is, that you might have configured macOS or some other software to start up MMF when your computer starts.

The first thing you might want to check, is whether the "Open at Login" option is checked for MMF. 
You can find this options as follows:

Open MMF so it appears in the Dock > Right-click MMF in the Dock > Go to "Options"

You should then see the "Open at Login" option, and unchecking it will hopefully solve your issue.

![Screen Shot 2021-07-28 at 15 56 51](https://user-images.githubusercontent.com/40808343/127334937-1ab99e0e-5a7d-4002-961d-be429169fd87.png)

Let me know if you have any more questions or issues.

**Comment by kushagr-m** [comment]
Hi @noah-nuebling, I tried that and it seemed to have fixed the problem. Thanks for your help.

**Comment by noah-nuebling** [comment]
Sure, glad to help! :)
