### ISSUE TITLE
Logitech M575 - Move between spaces [other]

### ISSUE THREAD

**Issue by edbarrer** [noah-nuebling/mac-mouse-fix#149]
Hello Noah,

This software looks amazing, and it have helped me solve the scrolling issue. I am trying to use my side buttons to move between Spaces, but it's not working. I only get back and forward functionality regardless of what setting is set.

Is there any setting I need to enable to get this working?

More Info: to Launch Mission Control, I have to enable it in System Preferences -> Mission Control settings and put Mouse Button 3 there. If I don't put it there and just leave it in the app, it doesn't work either.

Thanks,
Eduardo

**Comment by edbarrer** [comment]
Logitech Control Center was installed. After uninstalling it and rebooting, Mac Mouse fix works like a charm, thanks Noah!

**Comment by noah-nuebling** [comment]
Hey @edbarrer, thanks for reaching out.
It's nice that you've been able to resolve your issue so quickly, and I'm really glad you like Mac Mouse Fix!
