### ISSUE TITLE
Ability to invert side-scrolling direction [enhancement]

### ISSUE THREAD

**Issue by rafi-cohen** [noah-nuebling/mac-mouse-fix#151]
## Description
Like the option to invert vertical scrolling, add an option to invert horizontal scrolling (i.e. pushing the wheel button to the sides on supported mice)

## Rationale
I use Mac Mouse Fix to control the mouse scroll direction independently of the trackpad scroll direction. I like using the trackpad with what Apple calls the "natural" direction (flinging up scrolls down), and the mouse with the inverted direction (scrolling down scrolls down). To do so I must use natural scroll direction on the Macbook's settings, and use Mac Mouse Fix to invert the mouse scroll direction. However, Mac Mouse Fix does not affect the side scrolling direction of the mouse, so this is left with "natural" direction - scrolling left scrolls right.

## Additional info
–

**Comment by Zbun** [comment]
yes,I need  too, waiting for update

**Comment by noah-nuebling** [comment]
Hey guys thanks for reaching out! 

Pleased to inform you that in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases), it will now **smooth** and **invert** **horizontal scroll input** from your mouse!

Currently, there's just one option to invert the vertical and the horizontal direction. If you still would like to see a separate option for each direction, please open a new issue on that. Thanks!
