### ISSUE TITLE
vertical scrolling in calendar [enhancement]

### ISSUE THREAD

**Issue by c-fisc24** [noah-nuebling/mac-mouse-fix#153]
## Description
the possibility of vertically scrolling in the month- and year-view of calendar with the mouse. It's only possible to scroll through the views with the trackpad. Maybe it is possible to allow for scrolling with the mouse through mac mouse fix? 

## Rationale
This would enhance the flow of working with the mouse. 

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi there @c-fisc24, thanks for the feedback!

I actually made that work in version 3! Version 3 features an overhaul of the scrolling system and it simulates trackpad input very precisely, which also makes the horizontal scrolling in Apple Calendar work. It was a ton of work trying to reverse engineer how the trackpad events work exactly and to then build a system that can smoothen out the mouse-scroll-input and make the resulting scroll events look exactly like the ones that Apple's trackpad driver generates. 
Unfortunately, it's still a ton of work to finish it up and I won't have time to work on MMF in a while but the foundations are standing and you can look at that in the `version-3` branch of this repo. 

Before I release that I still need to release version-2 though and for version-3 I would also need to finish up the new scrolling system by implementing certain features like custom acceleration curves and separate settings for horizontal scrolling and inertial scrolling and then I'd have to overhaul the UI to fit the new scrolling options in, and so on... 

I don't have any time to work on MMF at the moment so I'm not sure I'll ever be able to finish this up :/

But I certainly hope so! And I'll keep you posted by updating this issue when I get around to implementing this stuff.

Hope that makes sense, and if you have any more questions let me know!

**Comment by noah-nuebling** [comment]
Hi again @c-fisc24, pleased to inform you that scrolling in Calendar should work the same as with a trackpad in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

Let me know if you have more thoughts or issues!
