### ISSUE TITLE
Disable smooth scrolling with a modifier key [enhancement]

### ISSUE THREAD

**Issue by CavalloneChen** [noah-nuebling/mac-mouse-fix#154]
## Description
It would be very convenient if we can temporarily disable smooth scrolling with a modifier key like ctrl. This function has been implemented in another project: https://github.com/Caldis/Mos

## Rationale
I don't always want to add an app to specific settings, and I would like to disable smooth scrolling just for a small period of time.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi @CavalloneChen, thanks for reaching out!

There's a similar feature to this in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases). Namely, you can temporarily disable smooth scrolling from the Menu Bar Item.

Does that solve your problem or would you still prefer the modifier key option?
If so, in which scenarious would you use it exactly?

If the solution in MMF 3 is not optimal for you please open a new Feedback report. Thanks!
