### ISSUE TITLE
Side buttons app specific [enhancement]

### ISSUE THREAD

**Issue by rafakob** [noah-nuebling/Mac-Mouse-Fix#162]
## Description
Would it be possible to set side buttons option per application? 

## Rationale
For example option "Back and Forward" works well for Finder and Chrome, but it's not working for other apps (example Football Manager game where only "Side button click" option works.). 

## Additional info
–

**Comment by bounty1342** [comment]
On VS Code, I tried to map it to "Go Back", "Go Forward" but it dosent get triggered.

**Comment by noah-nuebling** [comment]
Hey @rafakob, thanks for the feedback!

I'd love to build full support for app-specific configurations.
I already put some work into a UI refresh that will allow app-specific configurations to be supported in a really nice way. 

Please don't hold your breath though, as it's still a long way off.

**Comment by ubiquitous-dev** [comment]
+1 for this feature request - looks like app-specific configurations already exist, but not for the side buttons.  VS Code actually handles the M4 and M5 buttons natively, so disabling any "mouse helper" apps (this app or SensibleSideButtons) makes mouse back/forward work correctly on MacOS.  So enabling a per-app setting for VS Code to disable the overrides and send the buttons natively would be perfect.

I'm not sure if this is a separate feature, but this type of compatibility fix for the side buttons would be great to include in the app out of the box (eg. have a VS Code profile that fixes the side buttons included - it's the most common IDE with millions of users (and a lot of devs use Mac), so this is a very common situation where this app could lead the pack.

**Comment by raygan** [comment]
I'd like to see more per-app customization as well. 

For instance when I was using a Logitech mouse I liked to use their software to map one of my side buttons to the "Home" key in my Twitter app, for quickly scrolling to the top of the timeline. I had hoped I'd be able to override button mappings on a per-app basis (as you can with Logitech Options) but I see that's not currently possible.

**Comment by WilliamCappelletti** [comment]
I am really interested in this feature as well. On top of turning on/off, it would be great to have custom keybindings, for instance to navigate calendar with `cmd+left/right`.

**Comment by noah-nuebling** [comment]
Hi guys! I'll close this since #85 is now the dedicated place for discussion around this feature.
