### ISSUE TITLE
TLS certificate of mousefix.org has expired

### ISSUE THREAD

**Issue by ghost** [noah-nuebling/mac-mouse-fix#164]
Just to draw attention to something I noticed - the TLS certificate of [mousefix.org](https://www.mousefix.org/) has expired on 14 Oct:

<img width="484" alt="Screenshot 2021-10-19 at 13 04 25" src="https://user-images.githubusercontent.com/1466111/137908034-01a359fb-fc75-4cc6-abec-26084f183fea.png">

**Comment by noah-nuebling** [comment]
Thanks a lot for the heads up! Should be fixed.
