### ISSUE TITLE
Middle button not override [other]

### ISSUE THREAD

**Issue by nevack** [noah-nuebling/Mac-Mouse-Fix#165]
Please, add ability to not override middle mouse button, as I use it in games and with Mouse Fix it's not working as intended.

**Comment by ImanMahmoudinasab** [comment]
select middle button click option:

![image](https://user-images.githubusercontent.com/5295554/139333132-75fb8d33-d69d-4ace-9802-d1808825a267.png)

**Comment by nevack** [comment]
> select middle button click option:
> 
> ![image](https://user-images.githubusercontent.com/5295554/139333132-75fb8d33-d69d-4ace-9802-d1808825a267.png)

This is not a solution.
This option still doesn't allow me to click and drag, or long click.

**Comment by noah-nuebling** [comment]
Hey @nevack thanks for your feedback! 
If you use the `Middle button click` option as @ImanMahmoudinasab suggested, that should allow you to long click as well as click and drag normally, as long as you disable the `hold` action on the middle button as well. (set it to`-`)

Hope that helps, let me know if you have more questions!

**Comment by nevack** [comment]
> Hey @nevack thanks for your feedback! If you use the `Middle button click` option as @ImanMahmoudinasab suggested, that should allow you to long click as well as click and drag normally, as long as you disable the `hold` action on the middle button as well. (set it to`-`)
> 
> Hope that helps, let me know if you have more questions!

Hi, but i don't see `-` option in latest version

![image](https://user-images.githubusercontent.com/8330119/139355322-2a594a3e-c997-40ab-bebf-dd3b14ced80f.png)

**Comment by noah-nuebling** [comment]
In Mac Mouse Fix 2, removing all actions for the middle button will make the button behave as if Mac Mouse Fix is not running.

See the `Captured Buttons Guide` (#112) for more info and detailed instructions.

**Comment by nevack** [comment]
> In Mac Mouse Fix 2, removing all actions for the middle button will make the button behave as if Mac Mouse Fix is not running.
> 
> See the `Captured Buttons Guide` (#112) for more info and detailed instructions.

ohh, now it's clear for me. Removed all actions, closing the issue.

Thanks for making this great app!

**Comment by noah-nuebling** [comment]
Sure thing! :)
