### ISSUE TITLE
Allow side buttons to be configured separately [enhancement]

### ISSUE THREAD

**Issue by lzm0** [noah-nuebling/Mac-Mouse-Fix#168]
## Description
We only have options to configure side buttons together. It would be nice if we can configure assign different functions to the side buttons.

## Rationale
Currently there are only two options for side buttons.
- Move between Spaces
- Back and Forward
If we can configure side buttons separately, we would be able to add more options for side buttons, such as Show Desktop

## Additional info
I'd love to work on this feature and create a PR if you think this enhancement proposal is a good idea.

**Comment by noah-nuebling** [comment]
Hey @lzm0 thanks for reaching out! 
I think you'll be quite happy with the [MMF 2 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases).

If you have ideas and wanna work on the project that would be very welcome! Just let me know.

**Comment by lzm0** [comment]
That is awesome! Thank you.
