### ISSUE TITLE
Doesn't work when signed into mac as a second user [other]

### ISSUE THREAD

**Issue by ilium007** [noah-nuebling/Mac-Mouse-Fix#173]
Noticed today that is one user is signed in with Mac Mouse Fix running then I sign in with a second user (switch users) then the scroll wheel on the external mouse doesn't work. If I switch back to the first user, disable Mac Mouse Fix and then switch back the scroll wheel works again.

**Comment by noah-nuebling** [comment]
Hi @ilium007, thanks for the feedback! 

Unfortunately, I'd have to significantly restructure Mac Mouse Fix to solve this issue. As a work around, you can log out before you log into another user.

For more on this see #93.
Closing this to have all the relevant discussion in one place.
