### ISSUE TITLE
allow adding executables (like java) [enhancement]

### ISSUE THREAD

**Issue by nanopone** [noah-nuebling/Mac-Mouse-Fix#178]
## Description
allow adding regular unix executables (not .app bundles) to the app-specific exceptions

## Rationale
this allows games that use java (like minecraft) or games that dont use an .app bundle (like csgo) to be exceptions

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey @peepee, thanks for your feedback! 

@kode54 had the same request in #55. So I'm closing this to have all the discussion in one central place.
