### ISSUE TITLE
Mac Mouse Fix is not in applications folder [other]

### ISSUE THREAD

**Issue by tonyb007** [noah-nuebling/Mac-Mouse-Fix#180]
I successfully installed it and am happy with how it works... but I cannot find it to adjust settings. Running Big Sur on M1 macbook air.

**Comment by noah-nuebling** [comment]
Hey @tonyb007, thanks for reaching out!

Maybe it's in your Downloads folder. Or you could try Spotlight to search for it (⌘ Space).

Hope that helps!
