### ISSUE TITLE
Click and drag inversion [other]

### ISSUE THREAD

**Issue by Grunkhead** [noah-nuebling/Mac-Mouse-Fix#182]
When you click, you need to drag upwards. It would be really awesome if you could invert this to under, left or right.

**Comment by noah-nuebling** [comment]
Hi @Grunkhead, thanks for reaching out!

I'll take this into consideration for the future. But any changes on this are a while off.

Did you know you can see all Windows of the current app, by clicking and dragging down? 
But for that to work, the "App Exposé" option needs to be enabled under System Preferences > Trackpad > More Gestures.

<img width="500" alt="Screen Shot 2022-01-05 at 11 25 51 AM" src="https://user-images.githubusercontent.com/40808343/148269277-051b2db9-c983-4df0-87af-0b544268ab5b.png">

Let me know if you have any more questions!

**Comment by noah-nuebling** [comment]
I'll close this now, as I assume you've gotten used to the way things work. If you still would like to see this changed, please reopen this issue (Or write a comment telling me to reopen it if that's not possible).

Thanks!
