### ISSUE TITLE
Combination of mouse and shortcut key [enhancement]

### ISSUE THREAD

**Issue by DoneVirtue** [noah-nuebling/Mac-Mouse-Fix#183]
## Description
Thank you for your development.
Combination of mouse and shortcut key,

## Rationale
Thank you for your development.
Combination of mouse and shortcut key,
for example:Realize the preview of the picture, zoom in and out (command Scroll Down or command Scroll Up).
Thank you.

## Additional info
Thank you

**Comment by DoneVirtue** [comment]
Thank you for your hard time and community to create and improve the great app.

**Comment by noah-nuebling** [comment]
Hi @81876823, thanks for reaching out and for your kind words.

You can assign actions to holding a modifier key on your keyboard while clicking a button in the latest [Mac Mouse Fix 2](https://mousefix.org/)

Click and scroll actions (e.g. Click Mouse Button 4 and Scroll to Zoom In and Out) is something I've been working on, but that's a while off.

Hope that helps! Let me know if you have any more questions.

**Comment by noah-nuebling** [comment]
Closing this as I assume it's been resolved for you. Let me know if you have more questions!
