### ISSUE TITLE
Free custom shortcut for middle button [enhancement]

### ISSUE THREAD

**Issue by jjangga0214** [noah-nuebling/Mac-Mouse-Fix#184]
## Description
Currently, only one from the preset can be chosen. I think it might be cool if custom arbitrary shortcut can be configured

## Rationale
Personally, I want to use `Command   Tab` for middle button. 

## Additional info
Thanks for this cool software!

**Comment by noah-nuebling** [comment]
Hey there @jjangga0214, thanks for reaching out, I'm glad you like the app! :)

This is actually possible in the latest [Mac Mouse Fix 2](https://mousefix.org/)!

Let me know if you have any more questions.
