### ISSUE TITLE
Mac Mouse Fix not wroking and showing its force quit unexcpectedly [bug]

### ISSUE THREAD

**Issue by LynxHasGithub** [noah-nuebling/Mac-Mouse-Fix#187]
## Description

When i right click it and try to open it says mac mouse fixx quit unexcpectedly and i cant open it and i am on mac os 10.11.6

## Steps to reproduce

1. Go to the app in finder
2. Right click the app then click open

## Context

Mac Mouse Fix Version: 1.0.4
macOS Version: 10.11.6
Mouse Model: Vertux Indium

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there @FyxedHasGithub, thanks for reaching out!

The only thing I can think of is that some application state that macOS saves about the app between launches has gone corrupt. Then, when macOS is trying to load that state, the app crashes.

You could try:
- Downloading the latest [2.0 Version](https://mousefix.org/)
- Using [AppCleaner](https://freemacsoft.net/appcleaner/) to delete any files that macOS has created for the app
- Filing a [Bug Report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report)

Let me know how that goes!

**Comment by noah-nuebling** [comment]
Hi! 

I'l close this now as I assume it's a problem specific to macOS 10.11 and Mac Mouse Fix 2.2.1 dropped support for macOS 10.11.

Sorry about that. If you're on a newer macOS version (10.13 and later) you can check out the latest Mac Mouse Fix 2 version [here](https://github.com/noah-nuebling/mac-mouse-fix/releases).

Although it, too has some problems on older macOS versions. It has visual glitches pre macOS 11 (aka 10.16), and it doesn't seem to work at all for some people on 10.14.

I'll try to fix these issues sometime soon before moving development entirely to Mac Mouse Fix 3, but I can't give you a concrete timeframe right now.
