### ISSUE TITLE
Different software uses different key bindings [enhancement]

### ISSUE THREAD

**Issue by ttttmr** [noah-nuebling/Mac-Mouse-Fix#193]
## Description
The app-specific settings have too few controls for different apps, and I hope to have custom button4 button5 function settings

## Rationale
I mainly use the side key to switch tab pages in the browser, and set the binding to cmd tab and cmd shift tab in chrome, and I have multiple browsers, I hope this configuration can be copied to firefox for use
Other software cmd tab may be useless. For example, in vscode, I want the side key to control the code jump, and I need to bind ctrl - and ctrl shift -

## Additional info
–

**Comment by WilliamCappelletti** [comment]
+1, very similar to #162

**Comment by noah-nuebling** [comment]
Hi @ttttmr, thanks for your contribution! And thanks @WilliamCappelletti for helping to get an overview over all these issues!

This is a feature I definitely want to add but it's not coming very soon. 

Please refer to #279 for more info and further discussion of this feature.
