### ISSUE TITLE
System Volume control action for side buttons [enhancement]

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [noah-nuebling/Mac-Mouse-Fix#195]
## Description
Change System Volume via Buttons 4/5 should be a cool option.

## Rationale
I just recently used Logitech MX3 and it has side rotary to change System Volume, pretty cool thing.
I have mouse with 2 side buttons and I'm not using them for Back/Forward, instead I'd love to use them for System Volume. 

## Additional info
I have Mac Mini and just wired PC keyboard, so I can't assign shortcut to change brightness.
<img width="181" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3391456/148380237-115c747a-382c-492b-92ad-d94ec27df6da.png">

**Comment by noah-nuebling** [comment]
Hi @KAMIKAZEUA, thanks for the suggestion!

I just introduced that feature in [version 2.1](https://github.com/noah-nuebling/mac-mouse-fix/releases)! 
It's sort of hidden though. You need a keyboard with volume up and volume down keys and then you can remap your mouse buttons to those keys.

I hope that works for you!

Let me know if you have any more questions or suggestions.

**Comment by Anywhere-Music-Player** [comment]
Hey!

Well, I have just A4Tech KV-300H, so I think it's better to call some system function to Volume.
First, I was thinking that System Preferences has Volume key options, like for Brightness. So I can use call for keyboard shortcut in this app, but I can't find Volume.. 

<img width="604" alt="Screenshot 1" src="https://user-images.githubusercontent.com/3391456/148772288-72269b54-f100-4692-81cf-c827e857c65c.png">

Or maybe you can add a dropdown list, with pre-set shortcuts? Like for actual Volume keys from Mac keyboard..

**Comment by noah-nuebling** [comment]
Thanks for explaining. I would love to provide this feature but I’ll have to think about how to implement it exactly. I think the way it currently works is nice and minimal and works for most users, and I’m really wary of cluttering up the UI too much. 

I really like your idea of a dropdown menu for the shortcuts that aren’t available on non-apple keyboards though! Maybe only reveal it when the user holds option. If you have any more ideas let me know.

Please understand though, that the semester has started again, so it will probably be a while until I can work on this.

**Comment by noah-nuebling** [comment]
I lied! I couldn't help myself and built the feature tonight:

https://user-images.githubusercontent.com/40808343/148918472-0efa8603-3618-4f12-ba96-ae62fcc7a4d5.mp4

You can check it out here:

[MacMouseFixApp-2.1.1-Alpha-1.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/7845369/MacMouseFixApp-2.1.1-Alpha-1.zip)

**Comment by Anywhere-Music-Player** [comment]
Haha, you're best! 
**It works**, really cool feature!
I think this could be located not hidden menu of the Keyboard, but has some own menu item, like(the first thing that came to mind): "System Shortcuts" :)

**Comment by noah-nuebling** [comment]
Thanks, glad you like it! :)

I'll think about making it more visible, thanks for the ideas!
