### ISSUE TITLE
MMF 2.0 - cannot open in Monterey [bug]

### ISSUE THREAD

**Issue by jonathanlang** [noah-nuebling/Mac-Mouse-Fix#198]
## Description

I just got the prompt to update to the new 2.0 version. However, whether it's downloaded through the app or from the website / GitHub directly, the error message comes up "Mac Mouse Fix" may damage your computer. It's recommended to move the object to the Trash" (freely translated from German)... 
Is this a known issue? If not I can try to provide console logs... 

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/1255480/148655414-67e37362-366e-472f-82b7-bf18fb4f4037.png">

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.0.0
macOS Version: 12.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by rtrembecky** [comment]
right-click the app and choose "Open". this is a known issue and it is explained here (also accessible from https://mousefix.org/ website on top): https://github.com/noah-nuebling/mac-mouse-fix/discussions/114

**Comment by jonathanlang** [comment]
That’s what I tried first, but I’m getting the message even with Right-Click and selecting Open from the context-menu…

**Comment by noah-nuebling** [comment]
Hey @jonathanlang and @rtrembecky, thank you guys for your feeback and helpfulness!

I just published [version 2.1](https://github.com/noah-nuebling/mac-mouse-fix/releases) which should address this issue and also brings a cool new feature.

Does it work for you guys?

**Comment by noah-nuebling** [comment]
Closing this as it seems to work for everyone, let me know if you still have issues.
