### ISSUE TITLE
Mac Mouse Fix Identified by Apple as Malware [bug]

### ISSUE THREAD

**Issue by vorodo** [noah-nuebling/Mac-Mouse-Fix#199]
## Description
Went through the various guides including:

launchctl remove mouse.fix.helper
sudo open /Applications/Mac\ Mouse\ Fix.app
sudo xattr -dr com.apple.quarantine /Applications/Mac\ Mouse\ Fix.app
sudo chmod -R 755 /Applications/Mac\ Mouse\ Fix.app
sudo chmod +x /Applications/Mac\ Mouse\ Fix.app/Contents/MacOS/Mac\ Mouse\ Fix 
codesign --force --deep --sign - /Applications/Mac\ Mouse\ Fix.app
sudo xattr -dr com.apple.quarantine /Applications/Mac\ Mouse\ Fix.app
Right clicking and selecting open

None of them worked

## Description

Apple (not third party antivirus) identifies Mac Mouse Fix as malware, and doesn't let user open, let alone use, the software. Mac Mouse Fix had been working without issue for months when I was using the beta version of the 2.0 release.

## Steps to reproduce

Steps to reproduce are unknown, I've been using the 2.0 beta software for more than a month without issue, and it was only a couple days after installing the official release that Apple identified the software as an malware.

## Context

Mac Mouse Fix Version: 2.0.0
macOS Version: 12.1 (21C52)
Mouse Model: Logitech M720 Triathlon

## Additional Comments

View below screenshots that contain the following messages:
"Mac Mouse Fix.app" will damage your
computer. You should move it to the Trash.
This file was downloaded on an unknown date
When I try to open Mac Mouse Fix.app, the following error appears:
The application "Mac Mouse
Fix.app" can't be opened.
Uninstalling, reinstalling etc doesn't remedy the problem. I tried installing the beta version that had worked for weeks, but got the same error. Unfortunately, I've not been able to bypass this.

---
![Image 1-8-22 at 11 52 AM](https://user-images.githubusercontent.com/85590914/148658644-0561d841-d6ee-4c9d-9052-b52a8e25767e.jpg)
![Image 1-8-22 at 11 53 AM](https://user-images.githubusercontent.com/85590914/148658639-a0e3d168-6da4-48b3-8f2b-c1b51131de4e.jpg)

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @vorodo thanks for your detailed feeback!

I just published [version 2.1](https://github.com/noah-nuebling/mac-mouse-fix/releases). It addresses your issue and also bring a new feature.

Does it work for you?

**Comment by vorodo** [comment]
No problem, thanks for the speedy update! It's working beautifully, and I'm already taking advantage of the new feature :) Thanks for all your hard work and responsiveness, your software is a pleasure to use.
