### ISSUE TITLE
Doesn't work with 10.11?

### ISSUE THREAD

**Issue by Jagoche** [noah-nuebling/mac-mouse-fix#20]
Many thanks for this fix! It works great on 10.14. 

But on my old Macbook, which is stuck with 10.11, it refuses to start, saying: "This preference pane requires OS X 10.12 or later. Your computer has OS X 10.11.6 installed."

Since the webpage says "for MacOS 10.11+" is there any chance to make it run on 10.11?

**Comment by fklement** [comment]
@Jaogche 
Having the same problem here!
Is there any update on this?

**Comment by Jagoche** [comment]
> @Jaogche
> Is there any update on this?
Changelog suggests 10.11 compatibility will be fixed in the next release.

**Comment by fklement** [comment]
Ah ok nice.
Thanks for the information ♥️
