### ISSUE TITLE
Extend scroll wheel functionality [enhancement]

### ISSUE THREAD

**Issue by ericsodt** [noah-nuebling/Mac-Mouse-Fix#206]
## Description
Please allow the extension of the scroll wheel's gestures (scrolling up/down, tilt left/right while holding down another button).

## Rationale
Allow controlling "gestures" with the scroll wheel provides a lot of added functionality that would set this project apart from anything out there.  

For example clicking on ctrl   scroll down decreases your volume or screen brightness

## Additional info
–

**Comment by noah-nuebling** [comment]
I already built this in the version-3 branch! 

But I had to redo the whole scrolling architecture to get this and other stuff working, and it’s still pretty buggy and far from release. 

So please don’t hold your breath but know that I agree that this is a really cool feature and I really want it out there, too!

**Comment by noah-nuebling** [comment]
Hi @ericsodt, thanks for your feedback!

Pleased to inform you that scroll Gestures are in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

They can't be used to manipulate volume or screen brightness at this point, but they can do many other useful things!

If changing volume and screen brightness via scroll gestures is important to you please open another issue on that feature.

Let me know if you have any more questions or feedback!
