### ISSUE TITLE
Doesn't work with mouses that don't have side buttons

### ISSUE THREAD

**Issue by prattcmp** [noah-nuebling/mac-mouse-fix#21]
I have a simple mouse that only has left click, right click, and a clickable scroll wheel. There's no way to map Ctrl+Left Click, etc to swiping left or right. I can't use the app since I don't have side buttons.

**Comment by noah-nuebling** [comment]
Hi pratt, thank you for your feedback. 

I would love to provide better support for three button mice but unfortunately I don't have much time to work on the project so please don't hold your breath.

I would suggest you check out [SteerMouse](http://plentycom.jp/en/steermouse/), it provides more complex functions for 3 button mice through a feature called chording.
