### ISSUE TITLE
MacOS No longer allowing installation [bug]

### ISSUE THREAD

**Issue by henry-fisher** [noah-nuebling/Mac-Mouse-Fix#210]
## Description

After a reboot, MacOS disabled Mac Mouse Fix & moved it to the trash automatically due to it being unable to scan for malware. After attempting to reinstall it, MacOS says it can't scan the program for malware and to contact the developer for an update.

## Steps to reproduce

1. Download Mac Mouse Fix
2. Move to Applications
3. MacOS starts sending notifications and doesn't allow MMF to be opened.

## Context

Mac Mouse Fix Version: 2.1.0
macOS Version: 12.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey Henry, thanks for reaching out!

Can you open the app by right-clicking, choosing 'Open', and then choosing 'Open anyways' as described [here](https://github.com/noah-nuebling/mac-mouse-fix/discussions/114)?

If not check System Preferences > Security & Privacy > General for a button that says 'Open anyways' or something similar.

Hope that helps!

**Comment by henry-fisher** [comment]
That worked. Different from the other error messages which doesn't even recommend that. Sorry for the trouble

**Comment by noah-nuebling** [comment]
Cool, no worries :)
