### ISSUE TITLE
App wont open on Macbook Air 2020 (M1) [bug]

### ISSUE THREAD

**Issue by leleoveiga** [noah-nuebling/Mac-Mouse-Fix#218]
## Description

I tested every release, from the latest (2.2) to 2.0.0 Beta 7, and none of them opened.
The versions 2.1 and 2.2 when opened, it shows a window saying "Mac Mouse Fix can't be opened because Apple couldn't verify malware presence".
As in beta versions, when opened, it shows 2 windows. The first saying "The app Mac Mouse Fix couldn't be opened", and the second says "Mac Mouse Fix will damage the computer, you should move it to the trash"

(my OS is in portuguese, so the messages in english may differ, but the idea is the same)

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi Leonardo thanks for reaching out! 
2.2 and 2.1 should open when you right-click them in the Finder, then click 'Open', and then click 'Open' again in the dialog that pops up. More on this [here](https://github.com/noah-nuebling/mac-mouse-fix/discussions/114).

Does that work for you?

**Comment by leleoveiga** [comment]
> Hi Leonardo thanks for reaching out! 2.2 and 2.1 should open when you right-click them in the Finder, then click 'Open', and then click 'Open' again in the dialog that pops up. More on this [here](https://github.com/noah-nuebling/mac-mouse-fix/discussions/114).
> 
> Does that work for you?

yes! thx a lot

**Comment by noah-nuebling** [comment]
Very nice
