### ISSUE TITLE
Custom Function for Additional Mouse Buttons

### ISSUE THREAD

**Issue by tatnat** [noah-nuebling/mac-mouse-fix#22]
A neat feature would be to customize what the additional buttons do on your mouse (I have a Logitech Performance MX), where only the front/back function work as expected. Would be great to be able to also use the zoom and thumb buttons.

**Comment by kockok** [comment]
It would also be great if we can customise other actions for the buttons, e.g. "ctrl + w" for closing tabs whilst the side button is pressed.

**Comment by hacker1024** [comment]
My Acer Predator mouse also has a button below the scroll wheel that I'd like to map to mission control.

**Comment by noah-nuebling** [comment]
Hey there, thank you for your input!
I would love to provide better support for mice with more than 5 buttons, but I also want to keep the UI as simple as possible. I'm not sure that I know a great solution to this problem yet. If you have ideas for a solution let me know!

**Comment by noah-nuebling** [comment]
I think you'll be quite pleased with the new [2.0.0 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) :)

**Comment by kockok** [comment]
Really thank you for making the buttons customizable!! I can uninstall USB overdrive now!!!

**Comment by Oberlump** [comment]
Still need more options, e.g. for the MX Master 3 thumb button. :/

**Comment by Halvor-08** [comment]
2.1 works great, but the thumb button still sadly isn't recognised by the add button feature
