### ISSUE TITLE
Select All Keyboard Shortcut does not get set [bug]

### ISSUE THREAD

**Issue by vitalene** [noah-nuebling/Mac-Mouse-Fix#221]
## Description

When attempting to set the keyboard shortcut to "select all" (Cmd A), Mac Mouse Fix fails to set it.

## Steps to reproduce

1. Download and install Mac Mouse Fix 2.2.0
2. Try to change a button setting to command A (select all)
3. It doesn't work and won't let you. The default text is still there and no command is set.

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.1
Mouse Model: onn Wireless Bluetooth Mouse

## Additional Comments

–

---

### Console Logs

https://pastebin.com/tZXhK3YC

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi Neil, thanks for your thorough feedback!

The issue should be fixed here:

[MacMouseFixApp-2.2.1-Alpha-1.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/7917026/MacMouseFixApp-2.2.1-Alpha-1.zip)

Let me know if that works, or if you have any more questions!

**Comment by vitalene** [comment]
@noah-nuebling I have downloaded and tested and that has fixed the issue.  Thank you for the "quick hit with the hammer" on that bug. 🦟 🙂

**Comment by rjtort** [comment]
I'm having a similar issue. No keyboard shortcuts get set for me. I can see the modifier keys (ctrl, option, cmd, shift) show up in the keyboard shortcut capture window, but when I let go of the command, nothing happens. 

Verified my Privacy permissions are set in Accessibility and Keyboard Input for both the Mac Mouse Fix app and the Mac Mouse Fix Helper. Have removed/re-added those permissions and tried the MacMouseFixApp-2.2.1-Alpha-1.zip you have above. I'm on macOS Monterey and an M1 Pro, so not sure if that's part of the issue. Happy to share any logs, just let me know what you need. 

Thanks.
