### ISSUE TITLE
Cannot be opened because Apple cannot check it for malicious software. [bug]

### ISSUE THREAD

**Issue by Harrison97** [noah-nuebling/Mac-Mouse-Fix#222]
## Description

App will not open after download. It was also removed from recently on its own while it was working before.

Now I get this when I try to open it: "Cannot be opened because Apple cannot check it for malicious software."

## Steps to reproduce

1. Download app
2. Try to open app

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.1
Mouse Model: Logitech slim mouse for Mac

## Additional Comments

Please fix. I loved this app.

---

### Console Logs

–

### Crash Reports

–

**Comment by roughwood** [comment]
I am also experiencing this. I've never used this tool before and just now downloaded it, but I'm not able to run it.

**Comment by milanglacier** [comment]
Me too

**Comment by noah-nuebling** [comment]
Hey guys, thanks for reaching out! Can you open the app like this?

1. Right-click 'Mac Mouse Fix' in Finder
2. Choose 'Open'
3. Choose 'Open' in the dialog that pops up


Hope that helps!

You can learn more about this issue [here](https://github.com/noah-nuebling/mac-mouse-fix/discussions/114)

**Comment by noah-nuebling** [comment]
Hey there! I'm closing this now assuming it's not an issue anymore. Let me know it it's still a problem for you.
