### ISSUE TITLE
Problem in macOS 10.15 “Mouse Fix.prefPane” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by kockok** [noah-nuebling/mac-mouse-fix#23]
![Screenshot 2019-12-18 at 5 05 31 PM](https://user-images.githubusercontent.com/232541/71072032-a5591800-21b8-11ea-91bb-b45d8902b4f1.png)
![Screenshot 2019-12-18 at 5 05 43 PM](https://user-images.githubusercontent.com/232541/71072045-aab66280-21b8-11ea-8022-0e3058582dbd.png)

`This software needs to be updated. Contact the developer for more information.`

Please have a look into this.
I've already pressed the "Open Anyway" button under the Security Options.
![Screenshot 2019-12-18 at 5 00 54 PM](https://user-images.githubusercontent.com/232541/71071781-2ebc1a80-21b8-11ea-9246-abc6366f669a.png)

**Comment by noah-nuebling** [comment]
Hi kockok, I know it's been a while but thank you for your effort making all those screen shots and writing this up!

I just posted an official [workaround](https://mousefix.org/help/) for your issue on the Mac Mouse Fix Website if you wanna check it out.
