### ISSUE TITLE
[WORKAROUND] Mouse Fix can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by morgannewman** [noah-nuebling/mac-mouse-fix#24]
Duplicate of #17 and #23. Opening a new issue for visibility into this workaround.

Catalina users are getting the following error:
<img width="420" alt="Screen Shot 2019-12-19 at 3 16 50 PM" src="https://user-images.githubusercontent.com/30091235/71217514-e7df2b00-2272-11ea-90a0-f6f275c20e18.png">

As @noah-nuebling points out in #17, this app needs to be notarized by Apple, but a developer account costs $99 a year.

The workaround for opening the app anyway is to run the following in your terminal:

```bash
sudo spctl --master-disable
```

This will enable you to open apps by any developer without Gatekeeper blocking it. Result after the above command:
<img width="669" alt="Screen Shot 2019-12-19 at 3 29 33 PM" src="https://user-images.githubusercontent.com/30091235/71218015-ce3ee300-2274-11ea-9307-6ec41dd683e9.png">

@noah-nuebling it might be worth adding these instructions into your install instructions if you want to keep maintaining this wonderful tool!

**Comment by noah-nuebling** [comment]
I put a version of this workaround on the [website](https://mousefix.org/help). Thanks! :)
