### ISSUE TITLE
Translate middle mouse button click'n'drag to trackpad two-finger-scroll [enhancement]

### ISSUE THREAD

**Issue by wgdavies** [noah-nuebling/Mac-Mouse-Fix#245]
## Description
I have a Real Three Button Mouse (HP M-UD43) that works fine with normal functions, e.g left & right mouse buttons function as expected, middle button pastes selected text in Terminal and closes browser tabs, &c. 

I would very much like to use the middle mouse button to be able to drag and scroll window contents in e.g browsers, word processors, &c. It would also be exceptionally cool to support app-specific features, like horizontal scroll with a modifier key and middle mouse button. 

## Rationale
For those with a Real Three Button Mouse, this feature allows dragging and scrolling like with the Trackpad. For those using a scroll-wheel mouse for the third button, it would also allow finer-grain scroll control and a more natural Mac-like experience. 

It also just seems odd that Mac Mouse Fix recognises the middle-button click'n'drag gesture but only allows it to be mapped to Mission Control & Spaces. 

## Additional info
Great app! Thank you for making this available!

**Comment by noah-nuebling** [comment]
Hi! Thanks a lot for your feedback. Rumor has it I’m working on that ;) It’s really hard to get right so it’s a while off off but it will be really good! :) (If the rumors are true)

**Comment by noah-nuebling** [comment]
Hey @wgdavies, pleased to inform you that this is a feature in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!
