### ISSUE TITLE
Button 4 & 5 Additional Action  [other]

### ISSUE THREAD

**Issue by ShulamitWu** [noah-nuebling/Mac-Mouse-Fix#247]
Hi Noah, 

Thank you so much for creating this app! It is amazing! I am using Logitech G PRO X SUPERLIGHT, and I wonder how I can add additional actions to my Button 4 and 5. Currently, the app only shows "click" for these two buttons, but I also hope to have "hold" and "double click" for them. I tried to add but failed... My email is shulamit.wu@gmail.com. Thank you for your time. I look forward to hearing from you.

**Comment by noah-nuebling** [comment]
Hi @ShulamitWu, thanks for the feedback! I'm sorry for the late reply. 

If you haven't checked it out, the latest [Mac Mouse Fix 2](https://github.com/noah-nuebling/mac-mouse-fix/releases) should allow you to add as many actions to the side buttons as you want!

Let me know if you have more questions or issues.
