### ISSUE TITLE
Chording support [enhancement]

### ISSUE THREAD

**Issue by karlnippoldt** [noah-nuebling/Mac-Mouse-Fix#248]
## Description
Adding support for chording would be really helpful for devices that don't have many buttons.

## Rationale
Chording would allow devices (like the Kensington Orbit trackballs) that don't have many buttons to use more features. For example, you could allow the user to press both the left and right click buttons to perform a middle click for devices that are missing a middle click button.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey @karlnippoldt, this option should already be accessible in Mac Mouse Fix 2. Just click the "+" button, then place your mouse pointer inside the "+" field, and then click 2 buttons at the same time. 

It can be a bit finicky, but you should be able to make it work that way. 

Do you prefer chording over other options like click and hold, double click, or click and drag? If so, why is that?

Thanks!

**Comment by noah-nuebling** [comment]
Oh and this stuff should be a bit more obvious in the upcoming Mac Mouse Fix 3. Stay tuned!! :)

**Comment by noah-nuebling** [comment]
Closing this as I assume it's been resolved. Just reopen this issue if you still have problems (Or write a comment telling me to reopen it if that's not possible.)

**Comment by karlnippoldt** [comment]
I'm still not able to get it to work while pressing the primary and secondary mouse buttons at the same time—I just get a "Primary/Secondary Mouse Button can't be used" error. Basically, this is how Kensington replicates the missing middle click button in their own software. I don't really like their software otherwise, but I think this is the best way to replicate it as it doesn't interfere with my browser mouse shortcuts or anything else.

**Comment by noah-nuebling** [comment]
Ah okay that's interesting! So the problem here is that Mac Mouse Fix disallows using the Primary and Secondary Mouse Buttons, right? Because chording should be working with the other buttons.

**Comment by karlnippoldt** [comment]
Yep, that's correct. I didn't realize it supported chording at all since those are the only buttons my trackball has.

**Comment by noah-nuebling** [comment]
Okay cool. This is not coming super soon, but it's on my radar. In the meantime I can recommend [SteerMouse](http://plentycom.jp/en/steermouse/). That should support chording and it's probably nicer than the Kensington software.

**Comment by noah-nuebling** [comment]
I'm closing this now because I'm moving the topic of allowing the Primary / Secondary Mouse Button to Issue #364. Let me know if you have more questions!
