### ISSUE TITLE
Wacom Incompatibility [other]

### ISSUE THREAD

**Issue by bobbygeo** [noah-nuebling/Mac-Mouse-Fix#249]
Hello, 

Thank you for this tool! It works well for my traditional mouse. But I also use a Wacom tablet and it definitely affects scrolling using my pen on the tablet. Its sort glitches out and scrolling is very weird and choppy. Since Wacom handle their tablets separately, I'm not sure if this tool could have the ability of not editing the way the tablet works.

Thanks
Bobby

**Comment by noah-nuebling** [comment]
Hi @bobbygeo, thanks for your feeback! 
I wasn't aware of this issue before you reached out.

Unfortunately I don't have a drawing tablet to test, but I made some changes in the new [2.2.1 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.1-Beta-1) that might fix your issue. 

Let me know if that works for you or if you have any further questions.

**Comment by noah-nuebling** [comment]
Hey there! I'm closing this now assuming it's not an issue anymore. Let me know it it's still a problem.
