### ISSUE TITLE
Option reduces the amount of lines scrolled [enhancement]

### ISSUE THREAD

**Issue by shikhar006** [noah-nuebling/Mac-Mouse-Fix#250]
## Description
An option to use the Option(⌥) key to reduce or increase the amount of lines scrolled.

## Rationale
For some sites/apps like word a higher number is not precise and changing it all the time is a hassle.

## Additional info
–

**Comment by McDusty** [comment]
I would second this feature. 
Option or shift while scrolling to increase scroll amount would be kind of cool.

**Comment by noah-nuebling** [comment]
Hey guys thanks for the feedback report!

I'm pleased to inform you that both "Precise Scroll" and "Swift Scroll" are features in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

You can activate these features via keyboard modifiers or using just the mouse with the new "Click and Scroll" feature!

I hope that works for you guys! Let me know if you have more questions or thoughts!
