### ISSUE TITLE
No middle click [other]

### ISSUE THREAD

**Issue by ameen95m** [noah-nuebling/Mac-Mouse-Fix#256]
After I started using the app, even though I removed the "click" middle button action, I noticed that I can't use the normal function of the middle click. Is there a fix for this that I don't know about? I really need the normal middle click. Thanks.

**Comment by kriskate** [comment]
+1 for this; 

I'm working in fusion 360 and I want to use Mac Mouse Fix 2
But clicking and dragging on the middle button is not possible, even though I've removed the action

**Comment by thenktor** [comment]
Same here. Mouse Fix really is a great tool, but losing the default middle click sadly makes it useless for me (e.g. no middle click in browser for opening in a new tab anymore).

EDIT: Sorry, the solution is already there: https://github.com/noah-nuebling/mac-mouse-fix/discussions/112 👍

**Comment by noah-nuebling** [comment]
Hey guys thanks for reaching out!
Closing this now as I assume it's been resolved. If it's still a problem just reopen this Issue. (Or leave a comment telling me to reopen it if that's not possible)
