### ISSUE TITLE
Add support for middle button + scroll Space navigation

### ISSUE THREAD

**Issue by bearlysophisticated** [noah-nuebling/mac-mouse-fix#26]
Many mice doesn't have more than 3 buttons. In this case it would be a convenient way to change Spaces by holding middle button and scrolling up/down awhile. SteerMouse has this ability via Chords.

**Comment by noah-nuebling** [comment]
Hi bearlysophisticated, thank you for your suggestion!

I would love to provide more functionality for 3 button mice, and I will take your request into consideration. Unfortunately, I don't have too much time to work on the project, so please don't expect anything soon.

**Comment by noah-nuebling** [comment]
In the new [2.0.0 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) you can click-and-drag the to switch spaces in a super nice way. I think you'll love it! 
Let me know if you have any thoughts or would still prefer switching spaces by scrolling the scroll wheel over this.
