### ISSUE TITLE
smooth scrolling doesn't work in preview [bug]

### ISSUE THREAD

**Issue by imraan-go** [noah-nuebling/Mac-Mouse-Fix#264]
## Description

As the title suggest, looks like smooth scrolling does not work in preview when viewing a pdf. Also scrolling speed in MacOS mouse preference takes effect. But other smooth scrolling software such as MOS works just fine.

## Steps to reproduce

1. Open a pdf in preview

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.3
Mouse Model: Logitech G502

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by darahaas15** [comment]
This isn't an issue with the app, but a setting that's on by default for preview within the app (has smooth scrolling off) and can be enabled.

**Comment by noah-nuebling** [comment]
Hey @imraan-go, thanks for the feedback! 
@darahaas15 is right. Smooth scrolling in Preview could be toggled on or off in MMF 2 in the "App-specific settings...". The reason why it was off by default is that smooth scrolling didn't work properly in single page and double page viewing modes. In those modes it would scroll uncontrollably fast when smooth scrolling was enabled.

However in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) the scroll simulation has been improved to be more trackpad-like which should solve the scrolling issues in Preview entirely!

**Comment by imraan-go** [comment]
@noah-nuebling okay. Will give it a try. Thanks!
