### ISSUE TITLE
Start the app without opening the app window [enhancement]

### ISSUE THREAD

**Issue by jianglai** [noah-nuebling/Mac-Mouse-Fix#271]
## Description
I would like to start the app automatically at login, but right now it opens the main configuration window when it starts, which quite annoying. Can you add an option to start the app silently without opening the window?

## Rationale
This will make a much better experience for people who wants to run the app all the time in the background.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey @jianglai, thanks for the feedback! You can actually just close the app and it will stay "enabled". This will be made more obvious in the upcoming Mac Mouse Fix 3 along side many other cool improvements. Stay tuned!

I'm closing this now, let me know if you have more questions.
