### ISSUE TITLE
Cannot add [Command   A] as a keyboard shortcut [bug]

### ISSUE THREAD

**Issue by yohannjs** [noah-nuebling/Mac-Mouse-Fix#275]
## Description

Using MacOS BigSur Version 11.6.2
I use a Contour mouse with a middle button and two side buttons. When I try to add keyboard shortcuts as mappings for the buttons [Command   C], and [Command   X] and [Command   V] works fine, but it is not able to register [Command   A] as a keyboard shortcut. It only highlights the text in the decision window. 

## Steps to reproduce

Attempt to add [Command   A] as a keyboard shortcut for one of the mouse buttons

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 11.6.2
Mouse Model: UNIMOUSE-WL-L

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @yohannjs, thanks for the feeback!

**Comment by noah-nuebling** [comment]
This issue should be resolved. See https://github.com/noah-nuebling/mac-mouse-fix/issues/298.
