### ISSUE TITLE
middle button click-and-drag to scroll? [enhancement]

### ISSUE THREAD

**Issue by daeh** [noah-nuebling/mac-mouse-fix#28]
This is really nicely minimal and unobtrusive. Great work. I was hoping that it would give the ability to scroll by clicking and dragging the middle button. Is that a planned feature?

**Comment by stevenla** [comment]
This feature would be especially useful for trackball users!

**Comment by noah-nuebling** [comment]
Hi daeh, thank you for feedback! :)

This feature is not planned but I'm taking your request into consideration. In the mean time you might wanna check out [SteerMouse](http://plentycom.jp/en/steermouse/). Its a great piece of software which provides the feature you're looking for.

**Comment by jonikorpi** [comment]
Any plans for any other kind of 2D scrolling support, if not this feature? (Holding shift for horizontal scrolling is nice, but doesn't quite cut it when using canvas-style apps like Figma.)

For what it's worth, SteerMouse isn't working (at least for me) on Monterey, even with Mac Mouse Fix disabled. 😢

**Comment by noah-nuebling** [comment]
@jonikorpi  I actually built the underpinnings for a click and drag to scroll feature in the version-3 branch. 
It even supports inertial scrolling and I put a lot of work into getting the details right. It also emulates trackpad events super closely so you can use it to go back and forward in Safari or do anything else you would by swiping with two fingers on an Apple trackpad. It's a really cool feature and I'd love to put it out there!

But unfortunately I don't have much time to work on MMF, and it's a lotta work to finish the surrounding rewrite of the scrolling system up. So it'll be a long time, if I can ever get around to create a full, polished release with that feature. Sorry man :/

**Comment by noah-nuebling** [comment]
Hey guys Click and Drag to Scroll is finally here in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!
