### ISSUE TITLE
Mouse fix stops working after Sleep [bug]

### ISSUE THREAD

**Issue by daniellse** [noah-nuebling/Mac-Mouse-Fix#281]
## Description

When I finish working and I close the MacBook, then the next morning Mouse Fix never works! It's similar to the bug where some people will have it disabled when switching profiles, but I never do. Just suspending and resuming the session after a few hours will cause it to be unresponsive.

As in those cases, when I open the app it will appear enabled. I have to manually disable Mac Mouse Fix and enable again to have it work.

It appears to occur after a good time of Sleeping. If I manually Sleep the session and immediately resume, it will work as normal.

## Steps to reproduce

1. Work normally with MMF enabled.
2. Close the lid of the system and have it naturally sleep
3. Some time later (hours maybe) resume work
4. MMF will be unresponsive!

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.2.1
Mouse Model: Logitech G503

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @daniellse, thanks for your feedback!

I can't reproduce this issue. Does it still occur for you?

If so, please reopen this issue (Or write a comment telling me to reopen it if that's not possible). 
Filing a new [Bug Report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) with some Console Logs attached might also be very helpful.
