### ISSUE TITLE
Doesn't work after reboot [bug]

### ISSUE THREAD

**Issue by Korean-David** [noah-nuebling/Mac-Mouse-Fix#282]
## Description

After rebooting the system, MacMouseFix doesn't work. 
In order to make it work again, I have to launch the app, disable and enable MacMouseFix again. 

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: MacOS 12.3.1.
Mouse Model: Kensington Orbit Fusion

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi Korean-David! Does this problem still occur for you?

If so, please reopen this issue (Or write a comment telling me to reopen it if that's not possible). Filing a new [Bug Report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) with some Console Logs attached might also be very helpful.
