### ISSUE TITLE
Mouse fix does not work within preview [bug]

### ISSUE THREAD

**Issue by darahaas15** [noah-nuebling/Mac-Mouse-Fix#285]
## Description

Scrolling in preview reverts back to the default scroll (which does not emulate a magic mouse)

## Steps to reproduce

Scrolling within preview

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.3.1
Mouse Model: Logitech G304 Lightspeed

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by angusrogers** [comment]
It works for me using:
macOS 11.6
Mac Mouse Fix Version 2.2.0
Mouse Model: J .Burrows MS100

Are you sure that you have your app-specific scroll settings set correctly? If so then maybe it's macOS Montrey causing the issue; I haven't gotten around to updating yet.

**Comment by darahaas15** [comment]
This wasn't an issue with the app, but a setting that's on by default for preview within the app (has smooth scrolling off) and can be enabled.
