### ISSUE TITLE
Single clicking causes mouse to click twice [bug]

### ISSUE THREAD

**Issue by darahaas15** [noah-nuebling/Mac-Mouse-Fix#287]
## Description

Most single clicks cause mouse to to click 2-3x 

## Steps to reproduce

Clicking using left/right mouse button 

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: MacOS Monterey version 12.3.1
Mouse Model: Logitech g304 lightspeed

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by akira304moto** [comment]
Same double click here but I'm using middle button (set to "Middle click") to close Finder tabs. Two tabs will be closed when Mac-mouse-fix is on.

**Comment by noah-nuebling** [comment]
Hi guys thanks for reaching out! This is a really weird issue that I don't think I've heard about before or after. 

All I can think of is that maybe you have some other mouse driver like Logitech Options installed that interferes with Mac Mouse Fix?

To help investigate this issue you could file a [Bug Report](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) and attach some console logs. 

I'll close this issue now as I hope it's been resolved. If you're still experiencing it, please open a new issue. Thanks!
