### ISSUE TITLE
Increase scroll speed [enhancement]

### ISSUE THREAD

**Issue by kevinwang5658** [noah-nuebling/Mac-Mouse-Fix#288]
## Description
Hi Noah, awesome app! I love using it and it's been a real life saver for me. One thing I noticed was that the maximum scroll speed was on the low end and it would be awesome if the app could scroll a little bit faster. I actually checked out the code and tried it out myself by increasing the slider maximum to 4 and it turned out great. Would it be possible to add an option to increase the scrolling speed in an official release? Thanks!

<img width="709" alt="image" src="https://user-images.githubusercontent.com/20214115/167239913-278409cf-5ba0-47da-83e4-ae68f8875658.png">

**Comment by noah-nuebling** [comment]
Hi @kevinwang5658 thanks for your request!

Scrolling is a lot faster in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

Hope you like it and let me know if you have more thoughts or requests!
