### ISSUE TITLE
Allow use of ctrl + side buttons

### ISSUE THREAD

**Issue by daudn** [noah-nuebling/mac-mouse-fix#29]
This is feature request

Firstly, this is a great tool! I use the trackpad but every now and then I like to use my actual mouse and we all know that the Mac mice are horrible so this tool is perfect.

What I do see is that although I have the ability to switch screens, I have lost the ability to efficiently "swipe two fingers" and go back and forth.

If you allow your application to have side buttons to switch screens and ctrl + side buttons to mimic the swiping left and right with two fingers that would be great! Then using the mouse you can:
- switch screens
- go back/forward in webpages

**Comment by noah-nuebling** [comment]
Hi daudn, thank you for you kind words and feedback, I appreciate it! 
I totally agree that having both "Move between Spaces" and "Back & forward" available at the same time would be really nice to have! Your suggestion of using keyboard modifiers to change what the mouse buttons do is very interesting. I'm definitely taking your request into consideration.

**Comment by daudn** [comment]
My pleasure Noah! I respect people who provide open-source software since people like you give people like me a chance to learn and also some free upgrades! Keep working at it, I'm sure you can map more shortcuts and turn this simple app into a full fledged suite! Then make people pay for it xD

**Comment by TitorTraveller** [comment]
This is probably the best feature that i'm waiting for!

I'll be glad if the new release come up with this ability to use it as @daudn mentioned it, i'm in the same situation here, need the back and forward buttons for navigation but also need the left and right screen movement using just my mice.

Thanks @noah-nuebling for this tool, let me invite you a coffee when you drop the new release!

**Comment by noah-nuebling** [comment]
Hey guys I think you'll be pleased to know this is featured in the new [2.0.0 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) along with lots of other cool new features! Let me know what you think! :)
