### ISSUE TITLE
Startup and "disappear" [enhancement]

### ISSUE THREAD

**Issue by mskopp** [noah-nuebling/Mac-Mouse-Fix#290]
## Description
I added Mac Mouse Fix to my user-startup programs, even with the "hide" checkbox set.
So the configured mouse behaviour activates after each boot.
But the app is still active in the Dock - I would appreciate to have it kind of minimize to a menubar icon.

BTW, great tool, I love it.

## Rationale
Save space in the Dock

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey @mskopp, thanks for reaching out! 

You can actually just close the app and it will stay "enabled". I plan to make this more obvious in the upcoming Mac Mouse Fix 3. Stay tuned! :)

**Comment by noah-nuebling** [comment]
Oh and let me know if you have more questions or issues!

**Comment by mskopp** [comment]
Hey @noah-nuebling 
yeah, I only noticed closing the app is a workaround. Nevertheless it would be a great convenience feature to have the app closing itself to the menu bar upon startup (as an enablable feature), e.g. when the mac is restarted and app is executed as a start app.

**Comment by noah-nuebling** [comment]
It should stay "enabled" even after restarting your Mac actually. Does that work for you?
