### ISSUE TITLE
Unable to add Command   A as a keyboard shortcut for middle mouse click. [other]

### ISSUE THREAD

**Issue by yohannjs** [noah-nuebling/Mac-Mouse-Fix#298]
The program does not recognize Command   A as a keyboard, when attempting to add keyboard shortcut mappings for the different mouse buttons.

**Comment by noah-nuebling** [comment]
Hi Yohann!

Your issue should be resolved in the new [2.2.1 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.1-Beta-1). 

Let me know it goes!

**Comment by yohannjs** [comment]
Hello Noah, 

The issue was resolved in the 2.2.1 Beta release. Thank you very much!
