### ISSUE TITLE
Mac mouse fix cannot be opened anymore [bug]

### ISSUE THREAD

**Issue by eambutu** [noah-nuebling/Mac-Mouse-Fix#300]
## Description

As of a few days ago, I cannot open mac mouse fix because it says “Mac Mouse Fix.app” can’t be opened because Apple cannot check it for malicious software."

This software needs to be updated. Contact the developer for more information.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 11.6.2
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by eambutu** [comment]
p.s. thanks so much for creating this! it's super helpful. will buy you a milkshake!

**Comment by lrcf** [comment]
See #114.
