### ISSUE TITLE
Add the ability to scroll while the middle button is pressed  [enhancement]

### ISSUE THREAD

**Issue by Andriikym** [noah-nuebling/Mac-Mouse-Fix#304]
## Description
It will be good to have the ability to scroll while the middle button is pressed as a separate event.

## Rationale
Currently middle button hold is detected as a stand-alone event. But it can be extended with wheel scrolling. For controllers without horizontal scroll ability, it can be a decision to obtain it. Or for some other actions.

Therefore the idea - is to detect wheel scrolling while being hold

## Additional info
I have no idea is it feasible in the current implementation. I am ready to assist in implementation, but missing experience in that domain. So if you can direct with info, I can start to work on PR

**Comment by noah-nuebling** [comment]
Hey @Andriikym, thanks a lot for your feedbacka and for offering your help!

I'm glad to inform you that scroll Gestures are in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

You can "Click and Scroll" to do many different useful things including scrolling horizontally. You can also "Click and Drag" to scroll horizontally.

Let me know if you have any more questions or feedback!
