### ISSUE TITLE
please add shift to keyboard shortcut  [enhancement]

### ISSUE THREAD

**Issue by RobgriffinZ912** [noah-nuebling/Mac-Mouse-Fix#309]
## Description
please add shift key to keyboard shortcut 

## Rationale
 I would like to do horizontal scroll just buy using the mouse in Logic Pro. and now keyboard shortcut doesn't allow me to input single key like shift or command. If you could add that feature the app would be insane and more than perfect. really love what you have developed. thanks!

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey @RobgriffinZ912, I'm happy to inform you that one-handed horizontal scrolling is in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

You can either use "Click and Scroll" or "Click and Drag" to scroll sidewards.

Let me know if you have any more questions or feedback!
