### ISSUE TITLE
Page up/down with side-buttons

### ISSUE THREAD

**Issue by r3a1d3a1** [noah-nuebling/mac-mouse-fix#31]
The scroll wheels of my mice don't last long. It would be great to allow paging with side-buttons.

**Comment by r3a1d3a1** [comment]
My quick hack to do this is to change behavior of "Move between spaces" in InputParser.m as follows:
(Since I personally don't use multiple spaces that often)

![Screen Shot 2020-03-20 at 10 48 56 AM](https://user-images.githubusercontent.com/5890731/77175146-80ff2700-6a98-11ea-9835-36063472bf78.png)

added `#include <Carbon/Carbon.h>` on top as well (not shown above).

I'm not too familiar with XIBs and Objective-C, otherwise I'd have created a PR with this feature baked in as a 3rd option for side-buttons :)

**Comment by avh4** [comment]
I have a trackball with side buttons and no scroll wheel buttons, so having a "Page up/down" option for the Side Buttons would also be valuable for me.

**Comment by pallas** [comment]
Can you post a PR? I'm not sure where to add that but I'd love to try it out.

**Comment by pallas** [comment]
Ah, nevermind, I see where you mention that you're not super familiar with ObjC/XIBs.. me either :(

**Comment by noah-nuebling** [comment]
Hey guys sorry for chiming in so late. You can now assign Page Up and Page Down to a mouse button in the new [2.0.0 Beta 2](https://github.com/noah-nuebling/mac-mouse-fix/releases). I hope you'll like it! Let me know what you think, or if you need help with anything.
