### ISSUE TITLE
Mouse Scrolling Stops on User Profile Switch [bug]

### ISSUE THREAD

**Issue by damianmalysza** [noah-nuebling/Mac-Mouse-Fix#317]
## Description

I have two local user accounts set up on my M1 Pro 14inch Macbook. Whenever I switch between profiles, I lose the ability to scroll on my mouse. All of features of the app work on switch with the exception of scrolling. 

## Steps to reproduce

1. Log into each account on local machine and have Mac Mouse Fix running on both
2. Log into one account - validate that all Mac Mouse Fix features work fine
3. Switch to other user account session - ability to scroll on mouse gets lost

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.4
Mouse Model: Logitech G502 Wireless

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @damianmalysza, thanks for reaching out!

This has been an issue for a while and I would love to fix it but it's not easy as there's a bunch of under-the-hood restructuring I'd have to do. So it's not coming soon. 

In the mean time you can either 

1. Log out of the old profile before switching to the new one
2. Disable and re-enable Mac Mouse Fix after switching to the new profile

Hope that helps a little! Let me know if you have more questions.

**Comment by noah-nuebling** [comment]
Closing this now so all the discussion is focused in #93
