### ISSUE TITLE
Side buttons are suddenly not working anymore...

### ISSUE THREAD

**Issue by hirschferkel** [noah-nuebling/mac-mouse-fix#32]
I've installed the app two weeks ago and everything worked fine. Since two days it does not work anymore, I do not know if it somehow depends on the fact that I had to restart the machine in save mode, some days ago.

It's OSX 10.14.6

Middle Mouse action is still assigned with the mouse app but side buttons just does nothing. It seems that if only side buttons are activated, the app does not recognize the side buttons from the mouse anymore. Is there a wrong remapping issue? How can I track it down?

console log does show any further information:
```
standard	13:01:58.733709 +0200	Mouse Fix Helper	right
standard	13:01:58.957300 +0200	Mouse Fix Helper	Input HID (InputReceiver)
standard	13:01:58.957769 +0200	Mouse Fix Helper	Input CG (InputReceiver)
standard	13:01:58.957823 +0200	Mouse Fix Helper	parsing input (Input Parser)
standard	13:01:58.957868 +0200	Mouse Fix Helper	SINGLE CLICK REMAPPING
debug	13:01:59.068684 +0200	launchservicesd	Checking app App:"Mouse Fix Helper" asn:0x0-c70c7 pid:1375 refs=5 @ 0x7f9fb2d355f0 for keys in { "CFBundleIdentifier"="com.mti.Monotype-SkyFonts" }
debug	13:01:59.489972 +0200	launchservicesd	Checking app App:"Mouse Fix Helper" asn:0x0-c70c7 pid:1375 refs=5 @ 0x7f9fb2d355f0 for keys in { "CFBundleIdentifier"="com.mti.Monotype-SkyFonts" }
standard	13:01:59.549251 +0200	Mouse Fix Helper	Input HID (InputReceiver)
standard	13:01:59.549407 +0200	Mouse Fix Helper	Input CG (InputReceiver)
standard	13:01:59.549457 +0200	Mouse Fix Helper	parsing input (Input Parser)
standard	13:01:59.549500 +0200	Mouse Fix Helper	SINGLE CLICK REMAPPING
standard	13:01:59.549523 +0200	Mouse Fix Helper	handling input (Input Parser)
standard	13:01:59.549547 +0200	Mouse Fix Helper	left
standard	13:01:59.765223 +0200	Mouse Fix Helper	Input HID (InputReceiver)
standard	13:01:59.765371 +0200	Mouse Fix Helper	Input CG (InputReceiver)
standard	13:01:59.765401 +0200	Mouse Fix Helper	parsing input (Input Parser)
standard	13:01:59.765439 +0200	Mouse Fix Helper	SINGLE CLICK REMAPPING
```

**Comment by hirschferkel** [comment]
I deleted the preferences pane and reinstalled it after a restart. Now it works again, hopfully for more then two weeks...

**Comment by hirschferkel** [comment]
Broken again...

**Comment by LucaRed** [comment]
I think I have the same bug on my machine as well. Side buttons are only recognized if you're already pressing another mouse button.

**Comment by 23he** [comment]
Hi I had the same problem - with me it was an issue with firefox.
Here's how I solved it:
Inside Firefox, open "Preferences"
goto "General" , scroll down to subsection "Browsing"
**disable** both options related to scrolling


Hope that helped.

**Comment by HadrienKulik** [comment]
I seem to have the same problem. Middle button mapping works great, but side buttons are totally unresponsive. I'm on 10.15.6 and I had the same issue on 10.14 with Sensible Side Buttons (which worked great for a while).

Let me know if I can help debug with some logs or something!

**Comment by noah-nuebling** [comment]
Hey guys sorry for the late reply, and thanks for your feedback!

If this issue is still occurring for you guys on the latest version it would be awesome if someone filed a bug report and recorded some console logs while pressing the unresponsive side buttons.

You can easily file bug reports [here](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report). Thanks!
