### ISSUE TITLE
Unable to enable on macOS ventura system [bug]

### ISSUE THREAD

**Issue by 906836920** [noah-nuebling/Mac-Mouse-Fix#320]
macOS 13 beta3 、after update system from 12.5, MMF Unable to enable on macOS ventura system

**Comment by nianiam** [comment]
+1

I appreciate Ventura is still in beta, however, presumably the cause will stay the same in the release version.  I have come to rely on MacMouseFix, so a fix would be greatly appreciated!

**Comment by chris-c-thomas** [comment]
Oh hey I was just about to create this issue, awesome! Here's a video of it:

https://user-images.githubusercontent.com/22353987/180470733-3543efb4-678e-49ac-ba40-05fdfd827873.mov

**Comment by nianiam** [comment]
Just a heads up, it seems like there are bugs in the beta versions of Ventura which are causing this problem. The author seems to be waiting to see if the release version will fix this. 

https://github.com/noah-nuebling/mac-mouse-fix/issues/297

**Comment by chris-c-thomas** [comment]
> Just a heads up, it seems like there are bugs in the beta versions of Ventura which are causing this problem. The author seems to be waiting to see if the release version will fix this.
> 
> #297

Thanks for the heads up! I was able to get it to work with the interim fix. Hopefully Apple gets a fix in soon for the overall issue.

**Comment by chris-c-thomas** [comment]
Err actually no it's not working right. Oh well, will get on for now without it I guess.

**Comment by noah-nuebling** [comment]
Hi there thank you guys for the feedback!

I just published a [new beta version](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.1-Beta-1) that adds proper Ventura support.

Let me know if that works for you.

**Comment by noah-nuebling** [comment]
I left the Issue https://github.com/noah-nuebling/mac-mouse-fix/issues/297 open for further discussion.
