### ISSUE TITLE
Mouse scroll click default behaviour [enhancement]

### ISSUE THREAD

**Issue by kiishanbarmawala** [noah-nuebling/Mac-Mouse-Fix#324]
## Description
While using Google Chrome, I need the default mouse middle click which opens links in new tabs and closes tabs easily while clicking on the tab name. So I'm missing that functionality. So default behavior should be there.

## Rationale
–

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey, thanks for reaching out!

![CleanShot 2022-09-07 at 00 35 59@2x](https://user-images.githubusercontent.com/40808343/188752434-7f354b64-b323-46a4-8d87-de554cf56c79.png)

That option should be there under "Middle Click".

I'll try to make that more obvious in the future.

Let me know if you have more questions or concerns!
