### ISSUE TITLE
Fantastic app [other]

### ISSUE THREAD

**Issue by OptimusPrime91** [noah-nuebling/Mac-Mouse-Fix#326]
It's free and multifunctional and it replaced 2 apps: Scroll Reverser and SensibleSideButtons! My favorite feature is that I can switch to a space on the left/right with just a click & swipe, which is as convenient as on the touchpad with 4 fingers! It's a must have app for any Mac user with a mouse.

**Comment by noah-nuebling** [comment]
Thanks so much for letting me know you appreciate the app!

I'm probably biased, but I agree it's pretty cool.

**Comment by nianiam** [comment]
I’d like to concur! I spent last week without it because I’d installed Ventura and my whole workflow was interrupted. Thank you for such a brilliant app.

The only thing it’s missing for me is middle click to two finger swipe! Any progress on this feature?

**Comment by noah-nuebling** [comment]
> Any progress on this feature?

Yes :)

**Comment by noah-nuebling** [comment]
Stay tuned... 😎
