### ISSUE TITLE
Mouse bluetooth connectivity lost after connecting another bluetooth device

### ISSUE THREAD

**Issue by ghost** [noah-nuebling/mac-mouse-fix#33]
Whenever I connect airpods or my google home to my macbook pro through bluetooth, the mouse would all of a sudden stop working. To fix this issue, I would simply disable mouse fix and enable it again. Is there a way to fix this issue without having to disable and enable mouse fix?

**Comment by noah-nuebling** [comment]
Hey @lildefaz, sorry for the late reply, I didn't have time to look into this at first and then I unfortunately forgot about it. 

Does this problem still occur for you?

**Comment by noah-nuebling** [comment]
Hey there! I'm closing this for now since there hasn't been any activity in a while. Let me know it it's still an issue.
