### ISSUE TITLE
Disable the smooth scroll in full screen mode for specific app [enhancement]

### ISSUE THREAD

**Issue by zxkmm** [noah-nuebling/Mac-Mouse-Fix#332]
## Description
When I watch video in some website like Bilibili, the volume changes too much per grid I scroll. It is caused by the smooth scroll.

## Rationale
I'm not a macOS programmer, so idk if there is some api in macOS that able to detect full screen mode? And if it is possible, would it be ok to add a complex rule like "disable the smooth scroll in full screen mode for specific app" ?

**Comment by noah-nuebling** [comment]
Hi @zxkmm! Thanks for reaching out.

There's a "Precise Scroll" option in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases), which should allow you to use those volume sliders properly. 

You can also quickly disable smooth scrolling from the menu bar in MMF 3. 

I hope that works for you! Please open a new issue if the solutions provided in MMF 3 aren't optimal for you. Thanks!
