### ISSUE TITLE
Support for more side buttons

### ISSUE THREAD

**Issue by tomatsaev** [noah-nuebling/mac-mouse-fix#34]
First of all, I wanted to say that among all apps that try to fix this problem, this one is undoubtly the best! If it's possible, can you add support for other mouse buttons? I got a Razer Viper that has 2 side buttons on each side. Thanks a lot!

**Comment by noah-nuebling** [comment]
Hey there, thank you for your compliment! :)

This is very high up the list of features I'd like to add. But if I do the feature I wanna do it right, and I don't have a lot of time on my hands. So please don't hold your breath, but know that I'm taking your request into consideration.

**Comment by Skwol** [comment]
I wanted to create another issue (feature request) but this one seems like a good spot. App really works great. Can you please add support for wheel buttons (like left and right tilt)? It feels like the horizontal scroll is useless and I think only logitech mice support assigning different features for for left and right tilt.

**Comment by noah-nuebling** [comment]
Hey guys I finally got around to building this feature and many more for the new [2.0.0 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) I think you'll love it :)

It's all still in Beta and many things can change so let me know if you have any feedback!
