### ISSUE TITLE
Drag recognition of side buttons (btn4&5) depends on mouses. [bug]

### ISSUE THREAD

**Issue by teleV2** [noah-nuebling/Mac-Mouse-Fix#342]
## Description

Hi, Thank you for providing such a great app to public. I am really happy to use Mac Mouse Fix 2.0. What I tested was Logitech G10, G304 and MX Anywhere 3.
For each mouse, 
I click and drag the buttons in the ' ' zone to see the gesture is well recognized.

- G102 : no problem
- G304 : no problem
- MX Anywhere 3 : does not recognize the gesture.

* test condition: I deleted the logitech options  
(if it is installed, I had to uncheck them in the  'System Preferences > Security & Privacy > Privacy > Accessibility and Bluetooth', )

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.5.1
Mouse Model: Logitech G102, G304 & MX Anywhere 3

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by teleV2** [comment]
I figured out that, MX Anywhere3 side buttons have weird behavior. They don't do anything when pressed. They work when released. therefore, it seems there's nothing we can do about it.

https://forums.highrez.co.uk/viewtopic.php?t=4420

**Comment by noah-nuebling** [comment]
@teleV2 Thanks for the feedback and the kind words! Have you tested your MX Anywhere 3 with SteerMouse or Logitech Options? They should be able to handle your mouses' buttons correctly. 

Mac Mouse Fix unfortunately can't understand the signals that many Logitech mice send as they are proprietary and different from normal mice. However I do really want to add proper support for Logitech mice in the future.

**Comment by teleV2** [comment]
Hi, noah :)
Logitech make that behavior because of the horizontal scroll feature(one of the side buttons + wheel scroll = horizontal scroll). When I disable the horizontal scroll feature, the button suddenly acts as normal button (functions when pressed). However, the click and drag is not recognized by the Mac Mouse Fix 2.0 unfortunately. Logitech Options are not compatible with MX Anywhere 3, it needs Logitech Options+. No matter I deleted the Options+ or not, disabled it in system preferences or not, there was no luck.
Therefore, I end up choose G304. Thank you.

**Comment by noah-nuebling** [comment]
Okay cool glad you figured something out! :)
