### ISSUE TITLE
Mac Mouse Fix quit unexpectedly [bug]

### ISSUE THREAD

**Issue by rpcaptain** [noah-nuebling/Mac-Mouse-Fix#343]
## Description

When starting Mac Mouse Fix (2.2.1 Beta 2) it crashes every time.

## Context
Mac Mouse Fix Version: 2.2.1 Beta 2
macOS Version: macOS 12.5.1 (21G83)
Mouse Model: Logitech MX Master 3

### Crash Reports
https://hastebin.com/ajalirazud

**Comment by noah-nuebling** [comment]
Hey @rpcaptain, thanks for reaching out! This should be resolved in the latest [2.2.1 Beta 3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.1-Beta-3).

Let me know if you have more issues.

**Comment by noah-nuebling** [comment]
For future discussion it's best if you refer to #327 so everything is focused in one place.
