### ISSUE TITLE
Problem when scrolling with zoom applied [bug]

### ISSUE THREAD

**Issue by danilokleber** [noah-nuebling/Mac-Mouse-Fix#348]
## Description

The cursor jumps randomly when scrolling after applying any level of zoom (from the Accessibility preferences).

## Steps to reproduce

1. Apply any level of zoom (from the Accessibility preferences).
2. Use the scroll wheel.

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.5.1
Mouse Model: Logitech M720

## Additional Comments

Disabling Mac Mouse Fix fixes the problem.

---

### Console Logs

–

### Crash Reports

–

**Comment by danilokleber** [comment]
Just letting you know that this is fixed on version 3 beta. Thanks! I'll happily pay for Mac Mouse Fix.

**Comment by noah-nuebling** [comment]
Great! Thanks for letting me know!
