### ISSUE TITLE
Zooming (pinch to zoom equivalent) options [enhancement]

### ISSUE THREAD

**Issue by noah-nuebling** [noah-nuebling/Mac-Mouse-Fix#360]
### Discussed in https://github.com/noah-nuebling/mac-mouse-fix/discussions/260

<div type='discussions-op-text'>

<sup>Originally posted by **limeafon** March 12, 2022</sup>
Hi, I've been trying to figure a way to perform one-handed zooming with a mouse. Was wondering if there is a way to configure the existing cmd+scroll gesture to something like:

holding the middle button + scrolling, or 
holding the middle button + move mouse up/down?</div>

**Comment by noah-nuebling** [comment]
Hey @limeafon, pleased to inform you that one handed zooming is in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)! Let me know what you think!

**Comment by limeafon** [comment]
> Hey @limeafon, pleased to inform you that one handed zooming is in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)! Let me know what you think!

Just gave the v3 beta a whirl, it's excellent! I have configured a side-button + scroll as the option of zooming in and out. Thank you for the update!
