### ISSUE TITLE
“Mac Mouse Fix quit unexpectedly” when opening v3.0.0 Beta 1 [bug]

### ISSUE THREAD

**Issue by HazemAM** [noah-nuebling/Mac-Mouse-Fix#369]
## Description

I get a “Mac Mouse Fix quit unexpectedly” error every time I try to open the new v3.0.0 beta.

![Screen Shot 2022-09-14 at 3 32 46 AM](https://user-images.githubusercontent.com/3602800/190038730-4a692aca-e841-4322-a745-e80970376cc4.png)  ![Screen Shot 2022-09-14 at 3 33 23 AM](https://user-images.githubusercontent.com/3602800/190038741-045a4992-0b71-45d4-8abe-76417f6a4ac1.png)

## Steps to reproduce

1. Just opening the app produces the issue

## Context

Mac Mouse Fix Version: 3.0.0 Beta 1
macOS Version: 12.1
Mouse Model: Logitech G305

## Additional Comments

Looking forward to test the new beta!

---

### Console Logs

–

### Crash Reports

https://pastebin.com/3wyNL2Wj

**Comment by noah-nuebling** [comment]
Hi @HazemAM, thanks for posting the first 3.0.0 feedback! 

No idea how what might be causing that though. Very strange. I’ll look into it more in the next few days.

**Comment by CavalloneChen** [comment]
Well, for me, MMF 3 can't be opened even though I've clicked "open any way" in the "privacy and security" panel.
macOS: Ventura public beta 4
<img width="372" alt="image" src="https://user-images.githubusercontent.com/28266566/189561705-1ffe20f9-6016-4851-9a65-bfd75ee8c1d8.png">

**Comment by Zzoomrus** [comment]
Same for me. MacOS 12.5.1
Crash log https://pastebin.com/eRyABK4K

**Comment by Shavcat** [comment]
I had to revert back because beta 3 can't be opened. Also my mac get freezed while installing

**Comment by noah-nuebling** [comment]
Hey guys, thanks for chiming in! 

Are all of you using intel Macs?

**Comment by nianiam** [comment]
Having the same problem on my M1 Macbook Pro. Running Ventura pubkic beta 4.

**Comment by CavalloneChen** [comment]
> Hey guys, thanks for chiming in!
> 
> Are all of you using intel Macs?

No, I'm using an M1 Macbook Air.

**Comment by adnanmur** [comment]
i can confirm that it cant be opened on latest monterey, also managed to open it once and the mac frooze, i could move the mouse but couldnt click anywhere, also the keyboard was unresponsive

**Comment by noah-nuebling** [comment]
Okay so it's not about you guys using a different chip or a different OS than me.

The crash reports are saying something about an invalid code signature. Maybe we could learn more by using the `codesign` tool.

If you guys run these commands and report back what you find, that should be very helpful!

```
codesign -v --verbose=4 ~/Downloads/Mac\ Mouse\ Fix.app/
```

```
codesign -d --verbose=4 --deep -r- --entitlements - --file-list - ~/Downloads/Mac\ Mouse\ Fix.app/
```

(Replace `~/Downloads/Mac\ Mouse\ Fix.app/` if your app is not in the downloads folder)

Thanks!

**Comment by adnanmur** [comment]
first code

/Applications/Mac Mouse Fix.app: valid on disk
/Applications/Mac Mouse Fix.app: satisfies its Designated Requirement


second code

Identifier=com.nuebling.mac-mouse-fix
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20500 size=4038 flags=0x10000(runtime) hashes=115+7 location=embedded
Signature size=4796
Signed Time=6 Sep 2022 at 15:45:06
Info.plist entries=28
TeamIdentifier=LM5Z78756B
Runtime Version=13.0.0
Sealed Resources version=2 rules=13 files=17
Nested=Frameworks/Sparkle.framework
Nested=Library/LoginItems/Mac Mouse Fix Helper.app
Nested=Frameworks/ZipArchive.framework
designated => identifier "com.nuebling.mac-mouse-fix" and anchor apple generic and certificate leaf[subject.CN] = "Apple Development: noah.n.developer@gmail.com (8HVKLRF463)" and certificate 1[field.1.2.840.113635.100.6.2.1] /* exists */

**Comment by adnanmur** [comment]
adnan@adnans-MacBook-Pro ~ % codesign -v --verbose ~/Downloads/Mac\ Mouse\ Fix.app/
/Users/adnan/Downloads/Mac Mouse Fix.app/: valid on disk
/Users/adnan/Downloads/Mac Mouse Fix.app/: satisfies its Designated Requirement
adnan@adnans-MacBook-Pro ~ % codesign -d -r- --file-list --entitlements --verbose ~/Downloads/Mac\ Mouse\ Fix.app/

Executable=/Users/adnan/Downloads/Mac Mouse Fix.app/Contents/MacOS/Mac Mouse Fix
Identifier=com.nuebling.mac-mouse-fix
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=50654 flags=0x0(none) hashes=1572+7 location=embedded
Signature size=4796
Signed Time=12 Sep 2022 at 02:19:18
Info.plist entries=30
TeamIdentifier=LM5Z78756B
Sealed Resources version=2 rules=13 files=59
designated => identifier "com.nuebling.mac-mouse-fix" and anchor apple generic and certificate leaf[subject.CN] = "Apple Development: noah.n.developer@gmail.com (8HVKLRF463)" and certificate 1[field.1.2.840.113635.100.6.2.1] /* exists */
adnan@adnans-MacBook-Pro ~ %

**Comment by noah-nuebling** [comment]
@adnanmur, thanks for that! 

Just a heads up, I wrote the second command wrong, and it created a file named `--entitlements ` in the folder where you executed the command. (I think it's your home folder.) Sorry!

I also since updated the commands to provide even more detailed outputs, in case you want to run it again.

As for the output of the command that you posted, I can't see anything wrong with it at first glance. `codesign` seems to think the signature is okay. Very strange. I have to do some other stuff now but I'll look into it more ASAP. If anyone else has any ideas what might be going on here I'd also really appreciate your input of course!

**Comment by adnanmur** [comment]
no worries, found it.

handle LS launch error: {\n    Action = oapp;\n    AppMimimumSystemVersion = "10.13";\n    AppPath = "/Users/adnan/Downloads/Mac Mouse Fix.app";\n    ErrorCode = "-10810";\n}

default	14:56:35.103792+0200	kernel	ASP: Security policy would not allow process: 7944, /Users/adnan/Downloads/Mac Mouse Fix.app/Contents/MacOS/Mac Mouse Fix


proc 8355: load code signature error 4 for file "Mac Mouse Fix"


this is the error i get in console when opening the app

**Comment by Write** [comment]
Can't be opened for me too. On M1 Max 32GB. Ventura Beta 7.

Here's stderr && stdout of `codesign -d --verbose=4 --deep -r- --entitlements - --file-list - ~/Downloads/Mac\ Mouse\ Fix.app/ > stdout 2>&1`

```
Executable=/Users/redacted/Downloads/Mac Mouse Fix.app/Contents/MacOS/Mac Mouse Fix
Identifier=com.nuebling.mac-mouse-fix
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=50654 flags=0x0(none) hashes=1572+7 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=851968
Hash type=sha256 size=32
CandidateCDHash sha256=4205295044125261f0812bfbf4c1c29509ed00a5
CandidateCDHashFull sha256=4205295044125261f0812bfbf4c1c29509ed00a5d3a3c3b182568d55d3fe7a2f
Hash choices=sha256
CMSDigest=4205295044125261f0812bfbf4c1c29509ed00a5d3a3c3b182568d55d3fe7a2f
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=2195456
Executable Segment flags=0x1
Page size=4096
Launch Constraints:
	None
CDHash=4205295044125261f0812bfbf4c1c29509ed00a5
Signature size=4796
Authority=Apple Development: noah.n.developer@gmail.com (8HVKLRF463)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=12 Sep 2022 at 02:19:18
Info.plist entries=30
TeamIdentifier=LM5Z78756B
Sealed Resources version=2 rules=13 files=59
Nested=Frameworks/libswiftCoreData.dylib
Nested=Frameworks/libswiftIOKit.dylib
Nested=Frameworks/libswiftDarwin.dylib
Nested=Frameworks/libswiftAppKit.dylib
Nested=Frameworks/ZipArchive.framework
Nested=Frameworks/libswiftDispatch.dylib
Nested=Frameworks/libswiftFoundation.dylib
Nested=Frameworks/libswiftsimd.dylib
Nested=Frameworks/libswiftQuartzCore.dylib
Nested=Frameworks/Sparkle.framework
Nested=Frameworks/libswiftos.dylib
Nested=Library/LoginItems/Mac Mouse Fix Helper.app
Nested=Frameworks/libswiftCore.dylib
Nested=Frameworks/libswiftXPC.dylib
Nested=Frameworks/libswiftCoreImage.dylib
Nested=Frameworks/libswiftMetal.dylib
Nested=Frameworks/libswiftCoreFoundation.dylib
Nested=Frameworks/libswiftObjectiveC.dylib
Nested=Frameworks/libswiftCoreGraphics.dylib
designated => identifier "com.nuebling.mac-mouse-fix" and anchor apple generic and certificate leaf[subject.CN] = "Apple Development: noah.n.developer@gmail.com (8HVKLRF463)" and certificate 1[field.1.2.840.113635.100.6.2.1] /* exists */
[Dict]
	[Key] com.apple.application-identifier
	[Value]
		[String] LM5Z78756B.com.nuebling.mac-mouse-fix
	[Key] com.apple.developer.team-identifier
	[Value]
		[String] LM5Z78756B
	[Key] com.apple.security.app-sandbox
	[Value]
		[Bool] false
	[Key] com.apple.security.files.user-selected.read-only
	[Value]
		[Bool] true
	[Key] com.apple.security.get-task-allow
	[Value]
		[Bool] true
	[Key] keychain-access-groups
	[Value]
		[Array]
			[String] LM5Z78756B.com.nuebling.mac-mouse-fix.keychain-group
/Users/redacted/Downloads/Mac Mouse Fix.app/Contents/MacOS/Mac Mouse Fix
/Users/redacted/Downloads/Mac Mouse Fix.app/Contents/_CodeSignature/CodeResources
```

**Comment by Write** [comment]
![Screenshot du 2022-09-12 à 16 18 59](https://user-images.githubusercontent.com/541722/189677909-fa961835-1e44-43ab-89de-7d8a542daeb5.png)

This is so weird. ? It instantly return ? (Trying to watch syscalls) for Mac Mous Fix executable directly inside Mac Mouse Fix.app/Contents/MacOS/  directory

**Comment by noah-nuebling** [comment]
Thanks for your guys' help with this!

I really can't see anything obviously wrong with the `codesign` output. @adnanmur's console errors seems interesting, but I haven't been able to figure out what they mean so far.

Maybe it'll be interesting to see what the security policy tool `spctl` says about MMF. You can run it like this:

```
spctl --assess --verbose=4 ~/Downloads/Mac\ Mouse\ Fix.app/
```

(Replace `~/Downloads/Mac\ Mouse\ Fix.app/` if your app is not in the downloads folder)

**Comment by noah-nuebling** [comment]
@Write oh that's interesting! I didn' know about `dtruss`. I have no clue what's going on there either though.

**Comment by Write** [comment]
> Thanks for your guys' help with this!
> 
> I really can't see anything obviously wrong with the `codesign` output. @adnanmur's console errors seems interesting, but I haven't been able to figure out what they mean so far.
> 
> Maybe it'll be interesting to see what the `spctl` tool says about MMF. You can run it like this:
> 
> ```
> spctl --assess --verbose=4 ~/Downloads/Mac\ Mouse\ Fix.app/
> ```
> 
> (Replace `~/Downloads/Mac\ Mouse\ Fix.app/` if your app is not in the downloads folder)
![Screenshot du 2022-09-12 à 16 34 56](https://user-images.githubusercontent.com/541722/189681951-7e219a2d-2673-4f3c-b47d-19d17f484d5a.png)


¯\_(ツ)_/¯

**Comment by noah-nuebling** [comment]
Sooo I still don't know what's going on but here are some more clues, maybe someone else can help make sense of this:

I just found I can reproduce the issue by enabling "Open using Rosetta" for the app! I get an alert saying `The application "Mac Mouse Fix" can't be opened.` accompanied by the "Code Signature Invalid" crashes in the Console, so it seems to be the exact same problem you guys observed. But when I disable "Open using Rosetta" it works again.

I Googled some stuff and it said it might have to do with provisioning profiles. Then I went back to Xcode and now I suddenly can't build the app anymore with these strange errors also related to provisioning profiles:

![CleanShot 2022-09-12 at 17 12 06@2x](https://user-images.githubusercontent.com/40808343/189690763-fdaa6225-c563-43cd-903d-8f6ca683dca7.png)

I get these errors for the `Mac Mouse Fix` and `Mac Mouse Fix Helper` targets, but not for the `Mac Mouse Fix Accomplice` target.

All in all: I'm very confused. But it does seem like it might have to do something with the provisioning profiles?

Edit: Downloaded it again and now I can't open it at all anymore, with the same errors that you guys are having. This is good because at least I can now reproduce the issue and work on it more efficiently. 

Will look into this more later!

**Comment by noah-nuebling** [comment]
Quoting @Write
> ![Screenshot du 2022-09-12 à 16 34 56](https://user-images.githubusercontent.com/541722/189681951-7e219a2d-2673-4f3c-b47d-19d17f484d5a.png)
> 
> ¯_(ツ)_/¯

So `spctl` doesn't have any problems with the app either. Weird. Thanks for getting back!

**Comment by noah-nuebling** [comment]
Hey guys  I made some changes, and I think I might have fixed it!

[MacMouseFixApp.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/9561508/MacMouseFixApp.zip)

Does this work?

**Comment by runzr0bass** [comment]
wasn't part of original discussion but earlier today I downloaded the latest beta and my M1 Pro MacBook exhibited same symptoms...just downloaded the package you posted. I am now able to open the app but it immediately crashed....gonna try a couple or things and will report back. pls let me know if there are any specific commands that you would like to see the output of

**Comment by runzr0bass** [comment]
❯ sudo spctl --assess --verbose=4 Mac\ Mouse\ Fix.app
Password:
Mac Mouse Fix.app: rejected
source=Unnotarized Developer ID


ill code sign and try again

**Comment by HazemAM** [comment]
@noah-nuebling Just tried the new build, still get the same errors :(

![Screen Shot 2022-09-14 at 3 32 46 AM](https://user-images.githubusercontent.com/3602800/190038730-4a692aca-e841-4322-a745-e80970376cc4.png)  ![Screen Shot 2022-09-14 at 3 33 23 AM](https://user-images.githubusercontent.com/3602800/190038741-045a4992-0b71-45d4-8abe-76417f6a4ac1.png)

**Comment by noah-nuebling** [comment]
Does this one work?

[MacMouseFixApp.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/9561926/MacMouseFixApp.zip)

**Comment by noah-nuebling** [comment]
Thanks for offering your help @ar311krypton!

**Comment by runzr0bass** [comment]
![Screen Shot 2022-09-13 at 9 51 43 PM](https://user-images.githubusercontent.com/64196974/190040719-3d84600b-9899-4def-b725-a607428bb114.png)
success

**Comment by noah-nuebling** [comment]
Niceee finally!!

**Comment by runzr0bass** [comment]
> Thanks for offering your help @ar311krypton!

anytime dude, your app is incredible and absolutely vital to my workflow so really I should be thanking you. Super stoked to check out all the new features

**Comment by HazemAM** [comment]
Yes can confirm it works now! 🎉

**Comment by noah-nuebling** [comment]
@ar311krypton Thank you man, so glad you enjoy the app!

**Comment by Zzoomrus** [comment]
> Does this one work?
> 
> [MacMouseFixApp.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/9561926/MacMouseFixApp.zip)

Now it's start normally, but crash then I click Enable Mac Mouse Fix
https://pastebin.com/fVZCQjNR

**Comment by adnanmur** [comment]
Crashing here as well when i press enable.

edit: i pressed enable a little bit offset from where it needs to be pressed and it installed the helper now the app is opened. 

Edit: logitech mx master 3s back and forward buttons not working

**Comment by Zzoomrus** [comment]
> Crashing here as well when i press enable.
> 
> edit: i pressed enable a little bit offset from where it needs to be pressed and it installed the helper now the app is opened.
> 
> Edit: logitech mx master 3s back and forward buttons not working

Confirm, you need click here ![here](https://user-images.githubusercontent.com/11575231/190075656-9cdf102b-0c80-4aa2-8840-eac633c9b84e.png) to activate switch. It works random, so you need several tries.

**Comment by nianiam** [comment]
> Does this one work?
> 
> [MacMouseFixApp.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/9561926/MacMouseFixApp.zip)

Works like a charm for me! Purchased "Very Generously". Enjoy the special milkshake!

**Comment by noah-nuebling** [comment]
I published the fix as [3.0.0 Beta 2](https://github.com/noah-nuebling/mac-mouse-fix/releases). Thanks everyone for helping to figure this out!

**Comment by noah-nuebling** [comment]
@nianiam Thanks!! I will! I was gonna remove that because I didn't anyone would ever buy it, but maybe I was wrong. So that's a nice surprise.

**Comment by Zzoomrus** [comment]
On beta2 still crash on press enable.

**Comment by noah-nuebling** [comment]
@Zzoomrus even when you click on the edge?

I can't debug the crashes when clicking on the enable toggle at the moment because I can't reproduce it on my system. That's probably because I'm using the Ventura Beta.

But Beta 2 should have more detailed crash reports, if someone wants to post that crash again, I'll have a look and maybe I can figure something out.

**Comment by Write** [comment]
It seesm the crash happen when we don't have the permission already, on adding perm it crash the frrst time

**Comment by Zzoomrus** [comment]
> @Zzoomrus even when you click on the edge?

> I can't debug the crashes when clicking on the enable toggle at the moment because I can't reproduce it on my system. That's probably because I'm using the Ventura Beta.

> But Beta 2 should have more detailed crash reports, if someone wants to post that crash again, I'll have a look and maybe I can figure something out.

I try to turn off switcher using click on the edge, but no luck for now. In console I have this then start MMF:

```
*** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSNumber' (0x7ff847f332e8) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.objects', even though it was not explicitly included in the client allowed classes set: '{(
    "'NSDictionary' (0x7ff847f099e0) [/System/Library/Frameworks/CoreFoundation.framework]"
)}'. This will be disallowed in the future.
```

**Comment by Zzoomrus** [comment]
> > @Zzoomrus even when you click on the edge?
> > I can't debug the crashes when clicking on the enable toggle at the moment because I can't reproduce it on my system. That's probably because I'm using the Ventura Beta.
> > But Beta 2 should have more detailed crash reports, if someone wants to post that crash again, I'll have a look and maybe I can figure something out.
> 
> I try to turn off switcher using click on the edge, but no luck for now. In console I have this then start MMF:
> 
> ```
> *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSNumber' (0x7ff847f332e8) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.objects', even though it was not explicitly included in the client allowed classes set: '{(
>     "'NSDictionary' (0x7ff847f099e0) [/System/Library/Frameworks/CoreFoundation.framework]"
> )}'. This will be disallowed in the future.
> ```

Actually, I have bunch of errors:
![Снимок экрана 2022-09-14 в 17 08 16](https://user-images.githubusercontent.com/11575231/190162408-31a6af0d-03b8-4ad9-b4ac-ea1cce0f4bc2.png)

**Comment by Zzoomrus** [comment]
> > > @Zzoomrus even when you click on the edge?
> > > I can't debug the crashes when clicking on the enable toggle at the moment because I can't reproduce it on my system. That's probably because I'm using the Ventura Beta.
> > > But Beta 2 should have more detailed crash reports, if someone wants to post that crash again, I'll have a look and maybe I can figure something out.
> > 
> > 
> > I try to turn off switcher using click on the edge, but no luck for now. In console I have this then start MMF:
> > ```
> > *** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSNumber' (0x7ff847f332e8) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.objects', even though it was not explicitly included in the client allowed classes set: '{(
> >     "'NSDictionary' (0x7ff847f099e0) [/System/Library/Frameworks/CoreFoundation.framework]"
> > )}'. This will be disallowed in the future.
> > ```
> 
> Actually, I have bunch of errors: ![Снимок экрана 2022-09-14 в 17 08 16](https://user-images.githubusercontent.com/11575231/190162408-31a6af0d-03b8-4ad9-b4ac-ea1cce0f4bc2.png)

Finally I turn switch off by clicking on corner. Amount of errors reduced:
![Снимок экрана 2022-09-14 в 17 12 47](https://user-images.githubusercontent.com/11575231/190163939-727bc084-fd1b-40cf-a841-9f7cd0743c92.png)

**Comment by Zzoomrus** [comment]
Then I clicking switch, have this in console:
`<TCCDProcess: identifier=com.nuebling.mac-mouse-fixxx, pid=37934, auid=501, euid=501, binary_path=/Applications/Mac Mouse Fix.app/Contents/MacOS/Mac Mouse Fix> attempted to call TCCAccessRequest for kTCCServiceAccessibility without the recommended com.apple.private.tcc.manager.check-by-audit-token entitlement` from tccd,

`[XPC Server] managed connection recieved connection invalidated: Connection invalid`
from analyticsd,

`RBSStateCapture remove item called for untracked item <RBProcessMonitorObserver| qos:0 qos:(null) configs:{
	}>`
from runningboardd,

`CGXGetConnectionProperty: Invalid connection 341823`
from WindowServer (SkyLight),

`RBSStateCapture remove item called for untracked item 180-140-51716 (target:[app<application.com.nuebling.mac-mouse-fixxx.14579107.14579118(501)>:37934])`
`RBSStateCapture remove item called for untracked item 180-168-51720 (target:[app<application.com.nuebling.mac-mouse-fixxx.14579107.14579118(501)>:37934])`
`RBSStateCapture remove item called for untracked item 180-140-51718 (target:[app<application.com.nuebling.mac-mouse-fixxx.14579107.14579118(501)>:37934])`
`RBSStateCapture remove item called for untracked item 180-168-51721 (target:[app<application.com.nuebling.mac-mouse-fixxx.14579107.14579118(501)>:37934])`
`RBSStateCapture remove item called for untracked item 180-168-51717 (target:[app<application.com.nuebling.mac-mouse-fixxx.14579107.14579118(501)>:37934])`
from runningboardd,

`Unhandled notification: <private>`
from ContextStoreAgent (KnowledgeMonitor)

**Comment by nianiam** [comment]
> @nianiam Thanks!! I will! I was gonna remove that because I didn't anyone would ever buy it, but maybe I was wrong. So that's a nice surprise.

I _literally_ can't use my mac without MMF. It's easily worth this price.

**Comment by Zzoomrus** [comment]
Enable switch works properly in Beta 3.

**Comment by noah-nuebling** [comment]
@Zzoomrus great! Is anyone still having problems opening or enabling the app under [Beta 3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-3)?

**Comment by noah-nuebling** [comment]
Sorry about all the issues getting the Betas to run by the way! In the future I will try to test on different macOS versions and machines before a big release like this one.

**Comment by noah-nuebling** [comment]
I'll close this now assuming it's been resolved, let me know if you're still having issues!
