### ISSUE TITLE
MMF disables cmd scroll on Ableton [bug]

### ISSUE THREAD

**Issue by coolwindow** [noah-nuebling/Mac-Mouse-Fix#371]
## Description

Whenever MMF is enabled, cmd scroll to zoom on ableton stops working. I haven't experienced the problem with any other apps.

## Steps to reproduce

1. Open Ableton Live 11
2. Try cmd scroll, nothing happens

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.15.1
Mouse Model: Glorious Model O

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @coolwindow, thanks for reaching out!

If you

1. Open Mac Mouse Fix, then go to "More..." > "App-specific settings" and then add Live
2. Disable "⌘-scroll to zoom" for Live

Does that fix it?

**Comment by coolwindow** [comment]
Yes it does, thank you so much!!!
________________________________

**Comment by noah-nuebling** [comment]
Sure, glad to help! :)
