### ISSUE TITLE
PayPal alternatives for purchase [enhancement]

### ISSUE THREAD

**Issue by tolgaaaltas** [noah-nuebling/Mac-Mouse-Fix#374]
## Description
I want to support your hard work but PayPal is currently banned in Turkey and I can't purchase a license right now. Please add an alternative purchase method.

## Rationale
Adding an alternative payment method solves my problem.

## Additional info
–

**Comment by tolgaaaltas** [comment]
I just figured out there is already an alternative for PayPal with a credit card option. Sorry for the misunderstanding.

**Comment by noah-nuebling** [comment]
All good thanks for the kind words!
