### ISSUE TITLE
3.0.0 Beta 3 can't be opened properly [bug]

### ISSUE THREAD

**Issue by ShanePark** [noah-nuebling/Mac-Mouse-Fix#377]
## Description
![image-20220917211724031](https://i.imgur.com/RBoxlD4.png)
i tried to install 3.0.0 Beta 3 But it keep saying The application can't be opened. But 3.0.0 Beta 2 works properly

![img](https://i.imgur.com/G2Iz2Xz.png)
> I even allowed apps from Anywhere

## Steps to reproduce

simply can not open it after download

## Context

Mac Mouse Fix Version: 3.0.0 Beta 3
macOS Version: Monterey 12.6 
Mouse Model: Logitec G304

## Additional Comments

At the same time 3.0.0 Beta2 works OK

–

---

### Console Logs

–

### Crash Reports

–

**Comment by ShanePark** [comment]
I installed 3.0.0 Beta2 and then upgraded it through the application. 
it was successful so now i can use Beta 3. I was 2.2.0 version user and I love 3.0.0 beta so far. I'll be happy to pay if it works as I expect . Thanks

- just the 3.0.0 Beta3 installer doesn't work properly on my m2 Air

**Comment by noah-nuebling** [comment]
Shane thanks for reaching out! I'll close this now assuming it's been resolved. Let me know if you experience any more issues.
