### ISSUE TITLE
Different "macOS" scroll speed/behaviour in `v3` compared to `v2` [bug]

### ISSUE THREAD

**Issue by DrJume** [noah-nuebling/Mac-Mouse-Fix#381]
## Description

I am a big fan of macOS' scroll behaviour and noticed that something was off when I updated to MMF v3.

It is difficult to quantify, but I still would like to report that I noticed a difference in scroll speed/behaviour in the v3 beta compared to MMF v2.

## Steps to reproduce

1. use MMF `2.2.0`
2. set `Scroll Speed` to the lowest setting (Slow)
3. disable `Smooth Scrolling`
4. enable `Natural Scrolling` in macOS System Preferences
5. enable `Invert Scrolling`
6. **test scrolling behaviour**
7. use MMF `3.0.0 Beta 3`
8. set `Scroll Behaviour` to "macOS"
9. **compare scroll behaviour**

## Context

Mac Mouse Fix Version: 3.0.0 Beta 3
macOS Version: 12.6
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @DrJume, thanks for your feedback! I think I've fixed this! Update should be coming pretty soon.

**Comment by noah-nuebling** [comment]
Should be fixed in [3.0.0 Beta 4](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-4)!

**Comment by DrJume** [comment]
Sorry for the late feedback...
I finally tested MMF 3 Beta 5 with my beloved "macOS" scroll speed setting.
The scrolling feels normal again! Thanks :)
