### ISSUE TITLE
Music control for additional buttons [enhancement]

### ISSUE THREAD

**Issue by danilinus** [noah-nuebling/Mac-Mouse-Fix#393]
## Description
I suggest you implement music control

## Rationale
I ask you to implement volume control, as well as play/pause music

Thanks, the app is very cool

**Comment by noah-nuebling** [comment]
Hey @danilinus, thanks for reaching out, and I'm glad you like the app!

You should be able to remap your mouse buttons to the volume keys on your Apple keyboard using the "Keyboard Shortcut..." option.

If you don't have an Apple Keyboard available you can hold the Option (⌥) key to reveal the " Exclusive Keys" option


<img width="635" alt="Screenshot 2022-10-17 at 18 42 27" src="https://user-images.githubusercontent.com/40808343/196235259-852dcd4e-fdba-4dfc-b8f5-6972096ebad1.png">

This screenshot is from the MMF 3 Beta, but it should work the same in MMF 2.

Hope that helps! Let me know if you have more questions.

**Comment by danilinus** [comment]
Thank you! 🎉
