### ISSUE TITLE
Option to stay with the default behavior of the mouse buttons [bug]

### ISSUE THREAD

**Issue by PawelGIX** [noah-nuebling/Mac-Mouse-Fix#394]
## Description

When the application is running, the Back / Forward mouse buttons in some applications stop working.
For example, in Visual Studio Code.
Is it possible to add to the application the option did not overwrite the behavior of these buttons? So they would work in the default way.

## Steps to reproduce

Using the back forward button (mouse) in VScode

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: Monterey
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by PawelGIX** [comment]
![image](https://user-images.githubusercontent.com/391153/193288591-309e5297-bc4f-42fd-b4ed-b9659bddc00f.png)
OMG I just discovered that you can right click and unassign an action from a button.
This solves my problem 😅

**Comment by noah-nuebling** [comment]
Glad you could figure it out! I'll make this more obvious in a future update.
