### ISSUE TITLE
"Enable Mouse Fix" checkbox is disabled, even though the helper is running when "Resuming" System Preferences on the Mouse Fix prefpane after a reboot / relogin

### ISSUE THREAD

**Issue by noah-nuebling** [noah-nuebling/mac-mouse-fix#4]
When the Mouse Fix prefpane is open before a shutdown / logout, it will be reopened after the next startup / login. 
If macOS launches Mouse Fix Helper after Mouse Fix.prefPane, the "Enable Mouse Fix" checkbox of Mouse Fix.prefPane will be disabled even after Mouse Fix Helper has launched.

#### Ideas For a Solution
- Make helper launch before System Preferences
- Helper send an "I'm Running" message to prefPane after launching, which makes the prefPane activate the checkbox.

**Comment by abhijit945** [comment]
+1
Beta version works fine though.

**Comment by noah-nuebling** [comment]
This should be fixed in 2.0.0 Beta 1
