### ISSUE TITLE
Exclude apps from smooth scrolling [enhancement]

### ISSUE THREAD

**Issue by griffindavidson** [noah-nuebling/Mac-Mouse-Fix#401]
## Description
Enabling smooth scrolling causes exaggerations of scrolling in certain games. Minecraft: Java Edition for example: one scroll "tick" results in the hotbar selection flying a few spaces

This also includes Launchpad, where without smooth scrolling, it only takes one scroll "tick" to move to another page. With smooth scrolling, it takes multiple "ticks" in rapid succession to move from one page to another.

## Rationale
I'd like to be able to use smooth scrolling across the system without having to disable/reenable smooth scrolling depending on what I'd like to do at the moment

## Additional info
Thank you for developing the app, my Razer Basilisk X would be nearly useless otherwise, as Razer's app for it doesn't support macOS

**Comment by matvey733** [comment]
Same issue

**Comment by noah-nuebling** [comment]
Hi @GriffinDavidson thanks for your feedback, I'm glad you like the app!

You can actually disable Smooth Scrolling for specific apps under Mac Mouse Fix 2 under `More... > App-specific settings...`. But it doesn't work for Minecraft unfortunately.

Mac Mouse Fix 3, which is currently in Beta, doesn't support App-specific settings, but you can quickly disable Smooth Scrolling from the menu bar if you enable the `Show in Menu Bar` option.

At some point, I'd love to bring back App-Specific settings to Mac Mouse Fix 3 in a much better way that will hopefully support Minecraft as well.

Hope that helps! Let me know if you have any more questions or input.

**Comment by soggytomato** [comment]
Having the same problem in the Moonlight streaming client as well.

EDIT: Nevermind, restarting my machine fixed the issue!

**Comment by gohma231** [comment]
I think there is a bug in Mac Mouse Fix 2 'App-specific settings.'

I am hoping to disable Smooth Scrolling for an app, but enable horizontal scroll. With the settings shown below, horizontal scroll does not work.

![image](https://user-images.githubusercontent.com/4106435/212964461-83f8caaf-65ca-4b0b-a2c8-6077cd0eb34e.png)
