### ISSUE TITLE
Deadlock when scrolling too fast [bug]

### ISSUE THREAD

**Issue by mhaeuser** [noah-nuebling/Mac-Mouse-Fix#402]
## Description

Mac Mouse Fix deadlocks when scrolling too fast. Its CPU activity remains at around 100 % indefinitely and scrolling does not work at all till restarting the program.

## Steps to reproduce

Scroll *very* fast in an arbitrary window (my mouse has what Logitech calls an "infinite scroll wheel")

## Context

Mac Mouse Fix Version: 3.0.0 Beta 3
macOS Version: 13 Beta 10
Mouse Model: Logitech G502

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @mhaeuser, thanks for reaching out! I haven't been able to reproduce this issue, but I've made some fundamental improvements to the scrolling algorithm and how input from free-spinning scrollwheels is handled in the latest [3.0.0 Beta 6](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-6) which may have also fixed your issues. 

I'll close this issue for now. Let me know if you still have troubles.
