### ISSUE TITLE
"D" Key Not Working When Mac Mouse Fix Window is Closed [bug]

### ISSUE THREAD

**Issue by lc-t** [noah-nuebling/Mac-Mouse-Fix#404]
## Description

Somehow I can't enter "D"  key when Mac Mouse Fix window is closed. D is working fine when I keep the window open or minimized.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.6
Mouse Model: Logi M590

## Additional Comments

Also can reproduce it in 3.0.0 Beta 3

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @lc-t, thanks for your feedback!

Are you saying you can't use the D key on your keyboard in any app when Mac Mouse Fix is enabled but the app is closed?

That would be very strange. I have no idea what might be going on there, and I also have never heard of this issue. 

You might want to try completely uninstalling Mac Mouse Fix using [AppCleaner by FreeMacSoft](https://freemacsoft.net/appcleaner/) and then restarting your computer and reinstalling.

**Comment by lc-t** [comment]
Hi, @noah-nuebling, thanks for the reply. Somehow the bug is gone for now without uninstalling the app. I have no idea what's causing it, and how it's resolved. Might be other apps occupying the key. I'll close the issue for now, and keep an eye on it.

**Comment by noah-nuebling** [comment]
Cool, glad it's working for you now!
