### ISSUE TITLE
Mac Mouse Fix cannot be opened because it is not supported by this Mac. [bug]

### ISSUE THREAD

**Issue by Zzoomrus** [noah-nuebling/Mac-Mouse-Fix#411]
## Description
I have "Mac Mouse Fix cannot be opened because it is not supported by this Mac" error then try to open app. 

iMac19.1, Intel. I tried download it 2 times, no changes

## Steps to reproduce

Just open app

## Context

Mac Mouse Fix Version: 3.0.0 Beta 4
macOS Version: 12.6
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by jaekyeom** [comment]
Yeah, I think it is only packaged for Apple Silicon.

**Comment by noah-nuebling** [comment]
Thank you guys for getting back so quickly. @jaekyeom is right. I will upload a version that works on Intel shortly.

**Comment by noah-nuebling** [comment]
I swapped out the download link the [3.0.0 Beta 4 Release](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-4)!

Does that work for you guys?

**Comment by noah-nuebling** [comment]
By the way @Zzoomrus how did you notice the new beta release so quickly?

**Comment by Zzoomrus** [comment]
Works perfect! I just click on "Watch" button, choose that I need to notified and now receive email then new release is out

**Comment by noah-nuebling** [comment]
Great! Thx again.

**Comment by noah-nuebling** [comment]
> I just click on "Watch" button

Ah! I couldn't see you under watchers and betas always get a bunch of downloads pretty fast even though I don't advertise them anywhere and there's only 26 watchers showing up for me. So I thought there was another mechanism. But I guess just not all watchers show up for me?

**Comment by Zzoomrus** [comment]
> > I just click on "Watch" button
> 
> Ah! I couldn't see you under watchers and betas always get a bunch of downloads pretty fast even though I don't advertise them anywhere and there's only 26 watchers showing up for me. So I thought there was another mechanism. But I guess just not all watchers show up for me?

Yes, watchers count increases only if I choose watch all activity, not custom.

**Comment by noah-nuebling** [comment]
That would explain it. Good to know. Thanks!
