### ISSUE TITLE
Scrollwheel Problem in Premiere Pro [bug]

### ISSUE THREAD

**Issue by BlackBird11** [noah-nuebling/Mac-Mouse-Fix#414]
## Description

When I enable Mac Mouse Fix, the scrollwheel is not working as a normal scrollwheel anymore in Premiere Pro.
Ctrl scroll when disabled: scrub through timeline
Ctrl scroll when enabled: zoom timeline

scroll when disabled: scrolling through folder/settings
scroll when enabled: nothing

Anyone else having this issue?

## Steps to reproduce

Open Premiere pro and switch from enable to disable in mac mouse fix

## Context

Mac Mouse Fix Version: 3.0.0 Beta 4
macOS Version: 13.0
Mouse Model: Logitech G Pro X Superlight 

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @BlackBird11, I made some changes to scrolling in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5). Do your issues still occur when you use it?

**Comment by BlackBird11** [comment]
> Hi @BlackBird11, I made some changes to scrolling in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5). Do your issues still occur when you use it?

This fixed the issue for me in Lightroom and Premiere Pro for now. Will report back, if I encounter any issues in other programs. Thanks so much for this fix!

**Comment by noah-nuebling** [comment]
Cool, sounds good! :)

I think this was the same issue as #413 then.

Thanks for getting back!

**Comment by BlackBird11** [comment]
> Cool, sounds good! :)
> 
> I think this was the same issue as #413 then.
> 
> Thanks for getting back!

sorry for opening a new issue, didn't see the other one, but yes, seems like this was the same issue - thanks again for the quick fix and the response! your tool is literally the only way how i can use MacOS (with a mouse especially) coming from windows (with no mouse acceleration) without freaking out!

**Comment by noah-nuebling** [comment]
Well I'm happy to hear that :) Thanks for sharing!
