### ISSUE TITLE
Can't grant Accessibility Access on macOS Ventura [bug]

### ISSUE THREAD

**Issue by marcosatanaka** [noah-nuebling/Mac-Mouse-Fix#415]
## Description

I just updated to macOS Ventura RC and noticed that the enhancements provided by Mac Mouse Fix were not working. So I opened the app to check, and it asked me to grant Accessibility Access in Security Settings. I opened Security Settings, but Mac Mouse Fix Helper was already enabled. Switching the toggle doesn't seem to have any effect. So now I have the Mac Mouse Fix Helper enabled, but Mac Mouse Fix still thinks it is disabled. And my scrolling behavior and other enhancements don't work anymore.

## Steps to reproduce

1. Install the latest version of Mac Mouse Fix on macOS Ventura RC (I also tried with the beta - same results).
2. Open Mac Mouse Fix and enable it.
3. You will see that it asks for Accessibility Access.
4. Click the Open Security Settings button to open it.
5. You will see in System Settings that Mac Mouse Fix Helper is already enabled.

## Context

Mac Mouse Fix Version: 3.0.0 Beta 4
macOS Version: 13.0 (22A380)
Mouse Model: Logitech M90

## Additional Comments

I believe this is specific to macOS Ventura, because it was working as expected on previous versions. The issue happened after upgrading to Ventura.

---

### Console Logs

–

### Crash Reports

–

**Comment by drjaat** [comment]
Facing the same issue on monterey aswell @noahmtnr

**Comment by rabomen** [comment]
Same on 2.2.1, Monterey
EDIT: try this https://github.com/noah-nuebling/mac-mouse-fix/issues/412#issuecomment-1285629403

**Comment by marcosatanaka** [comment]
[#412 (comment)](https://github.com/noah-nuebling/mac-mouse-fix/issues/412#issuecomment-1285629403) fixed the issue! I was going mad trying to return to the Magic Mouse all-day long 😅. Thanks for the update!

**Comment by noah-nuebling** [comment]
Hey guys thanks for reaching out! 

I'll close this now so everything is focused in Issue #412.

I hope to push an update soon that automatically fixes this problem. Until refer to [@rishifter's comment](https://github.com/noah-nuebling/mac-mouse-fix/issues/412#issuecomment-1285629403).
You can test the fix [here](https://github.com/noah-nuebling/mac-mouse-fix/issues/412#issuecomment-1287527416). Would love to hear if that works for you!

**Comment by vsheg** [comment]
Unfortunately, I still have the problem. I've already reinstalled the app (previously removed it by brew, and by AppCleaner) and rebooted my computer each time. 
![Screenshot 2022-10-22 at 10 20 47](https://user-images.githubusercontent.com/36817377/197326508-ac8d9e21-d7ef-44a2-90c1-ba5ebfedc086.jpg)
