### ISSUE TITLE
Mac Mouse Fix is unusable since it doesn't recognize the activated helper [bug]

### ISSUE THREAD

**Issue by DallAlexander** [noah-nuebling/Mac-Mouse-Fix#418]
## Description

I activated the Mac Mouse Fix Helper in the settings but the app doesn't recognize it.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.1
macOS Version: MacOS Monterey
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports
![Bildschirmfoto 2022-10-22 um 19 32 53](https://user-images.githubusercontent.com/71569915/197354273-bb45dc98-622b-4604-b66b-8dbd779308d6.png)

–

**Comment by noah-nuebling** [comment]
Hi Alex, thanks for reaching out!

Try this version of the app:
https://github.com/noah-nuebling/mac-mouse-fix/files/9843007/MacMouseFixApp-2.2.2-Alpha.zip
