### ISSUE TITLE
Button 4 + 5 should have the same four different gestures as Middle Button [enhancement]

### ISSUE THREAD

**Issue by holdingsllc** [noah-nuebling/Mac-Mouse-Fix#419]
## Description
Button 4 + 5 should have the same four different gestures as Middle Button. This would be an incredible addition that I would donate a lot of money for!

## Rationale
Middle Button Click and Button 4 + 5 Click can't be reserved because they are so essential in most apps and there aren't enough other gestures on any of the buttons to compensate.

## Additional info
This app is incredible already!

**Comment by L-i-v-y** [comment]
I'm not entirely sure if I understood your request correctly, but if you use the + icon to add a new button, then click and drag Button 4 or Button 5 within the small window with the + symbol, you will get the same option to have Mission Control & Spaces with dragging the mouse while holding Button 4 or Button 5.

<img width="541" alt="Screenshot 2022-10-23 at 18 20 33" src="https://user-images.githubusercontent.com/48463681/197403632-aac2dec1-3475-4a55-bd32-41ca1fba689e.png">

**Comment by holdingsllc** [comment]
My apologies, I have successfully added gestures. I did not see the + sign and after clicking it now it's a unclear that it does what I needed.

My suggestion is to improve the messaging around these features and to make the + and - more prominent.

Thanks!

**Comment by noah-nuebling** [comment]
Thanks for your feedback @holdingsllc and thanks for helping out @Aloekior!

@holdingsllc you're not the first person to be confused but this. Things should be a lot more easily discoverable in Mac Mouse Fix 3 which is currently in Beta!

**Comment by holdingsllc** [comment]
Absolutely! I have to say, this has nearly doubled my productivity and I would love to donate somehow.

**Comment by noah-nuebling** [comment]
Great to hear!

You don't have to worry about it, but of course I'm happy if you want to donate!

You can donate via PayPal [here](https://www.paypal.com/donate?token=22iR__eW_t7Eizg59RflbU5AJVV_-aSh7UAUy0u6QiQv5hUqZmZE_Vw-N3oUxcI8xAe5EDqL8b4SaWag&locale.x=en_US) or you can just buy a Mac Mouse Fix 3 license for 1.99.

Thanks again!
