### ISSUE TITLE
Accessibility permissions not recognized [bug]

### ISSUE THREAD

**Issue by NikEfth** [noah-nuebling/Mac-Mouse-Fix#422]
## Description

I just updated to 3.0.0 beta 4 and the switch in the Accessibility permissions is not recognized by the app. I switched on both "Mac Mouse Fix" and "Mac Mouse Fix Helper"  

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.2
macOS Version: 13.0
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @NikEfth, thanks for reaching out! See #412 for a solution / explanation of the issue.
