### ISSUE TITLE
Ventura 13.0 Middle Mouse Button Not Recognized

### ISSUE THREAD

**Issue by coffinmilk** [noah-nuebling/Mac-Mouse-Fix#423]
When updating to Ventura 13.0 (22A380), MacMouseFix ceased to recognize the middle-mouse button on my Logitech Pebble M350. It still functions as a regular middle mouse button elsewhere (click to open links in new tabs, etc.). I was on MacMouseFix 2.2.2 and then updated to 3.0.0 Beta 4 (19384) but issue persists. It does however, recognize primary and secondary mouse buttons.

**Comment by noah-nuebling** [comment]
Hey @coffinmilk has your issue been resolved or should I reopen it?

**Comment by coffinmilk** [comment]
@noah-nuebling It has been resolved. Your troubleshooting steps on #362 fixed the issue: removing accessibility permissions entirely, then restarting computer. Thanks!
