### ISSUE TITLE
The middle button cannot be detected on MacOS Ventura [bug]

### ISSUE THREAD

**Issue by MSamiulHasnat** [noah-nuebling/Mac-Mouse-Fix#424]
## Description

Recently I've upgraded to the MacOS Ventura. I was using Mac Mouse Fix since previous version (Monterary or something similar). Middle Button (Wheel) was working fine with that version. But It is not working on this latest version. Try to fix it up asap.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.2
macOS Version: Ventura
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi! Thanks for your feedback. Unfortunately I don’t know what might be causing these issues. But here are some troubleshooting steps:

1. Disable Mac Mouse Fix. Close it.
2. Install [AppCleaner by FreeMacSoft](https://freemacsoft.net/appcleaner/), then delete Mac Mouse Fix. AppCleaner should give you a pop up to also remove residue. Make sure you deleted the file at "~/Library/Application Support/com.nuebling.mac-mouse-fix/config.plist". It contains all the settings and state for Mac Mouse Fix, and maybe it has been corrupted.
3. Delete **all versions** of Mac Mouse Fix from your computer. Search for "Mac Mouse Fix" with Spotlight to make sure you deleted everything.
4. Empty your trash
5. Go to System Settings > Privacy & Security > Accessibility and remove “Mac Mouse Fix Helper” using the “-“ button at the bottom.
6. Restart your computer, reinstall Mac Mouse Fix, and try again!

Hope that helps! Let me know how it goes.

**Comment by noah-nuebling** [comment]
Someone else with the same issue fixed it using these simplified steps:

1. Delete all versions of Mac Mouse Fix
2. Empty the Trash
3. Restart your computer
4. Download the latest version of MMF from the Website and try again

**Comment by MSamiulHasnat** [comment]
I just followed your steps and it is not working. staying the same. 
I've uninstalled mmf, empty trash, restarted device, downloaded latest (2.2.2) mmf and also upgraded to beta version. But it is not working.

**Comment by noah-nuebling** [comment]
Okay a few more things you could try:

- Follow the long version of the steps (the one with 6 steps above).
- If that still doesn't work, try this [online mouse test](https://www.onlinemictest.com/mouse-test/) and see if it recognizes the middle button on your mouse. Try testing with Mac Mouse Fix disabled and with Mac Mouse Fix enabled.
    - If it doesn't work while MMF is disabled, it's probably a hardware issue with your mouse. But If it **does** work while MMF **is enabled**, then that tells us some stuff about what's going on internally in MMF.
- Last thing you could do is gather some Console Logs as described on the ['Bug Report' page](https://noah-nuebling.github.io/mac-mouse-fix-feedback-assistant/?type=bug-report) and send me those. Try [MacMouseFixApp-2.2.2-Debug-for-Samiul.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/9888278/MacMouseFixApp-2.2.2-Debug-for-Samiul.zip) for that as it will output more detailed information to the Console.

Let me know if you have any more questions or if anything is not entirely clear!

**Comment by noah-nuebling** [comment]
This person also had the same issue #423.
They could resolve it by completely removing 'Mac Mouse Fix Helper' from Accessibility Settings and then restarting. (This step is also contained in the 6 steps above. The 6 steps contain everything that has worked for someone so far.)

**Comment by MSamiulHasnat** [comment]
Negetive, Stays the same, Middle button is being detected on onlinemictest on and off the mmf but not working on mac

**Comment by MSamiulHasnat** [comment]
I just noticed one thing, none of my buttons (5+) except primary left and right is working. I'm using an onMicro BT5.1 Mouse.

**Comment by noah-nuebling** [comment]
Hey @samiulhsnt,

Thanks for getting back! I now finally have time to look into your issue!

Here are some things you could test to shed light on things:

1. In MMF 3.0.0 Beta 4 if you go to the 'Buttons' tab and click 'Reset to defaults...' with your mouse it should tell you how many buttons your mouse has. How many buttons is that?
2. Do other versions of Mac Mouse Fix work? You could test [2.2.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.3) and [3.0.0 Beta 3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-3). After you download another version, it's best if you delete all other versions of Mac Mouse Fix and restart your computer before testing it.
3. Record some Console Logs of what Mac Mouse Fix does internally when you click buttons on your mouse:
    1. Open and enable Mac Mouse Fix 3.0.0 Beta 4
    2. Go to Console.app > Action and enable 'Include Info Messages' and 'Include Debug Messages'
    4. Go to Console.app > Search and enter 'Mac Mouse Fix' 
    5. Go to Console.app > [Your device name] and click 'Start streaming'
    6. Click some buttons on your mouse (other than Mouse Button 1 and Mouse Button 2 (aka left click and right click))
    7. Copy-paste logs which occured around the time when you clicked the buttons and send them to me.

Explanation:

Mac Mouse Fix uses some low level APIs to determine on which mouse you are clicking a button. When those low level APIs fail, it just ignores that click. Several of the things point to these APIs not working correctly for your mouse. 

The tests above should give more insight into what's going on especially the Console Logs. 

Thanks for helping out!

Oh and in the mean time if Mac Mouse Fix isn't working I can recommend these alternatives to you:

- [Steermouse](https://plentycom.jp/en/steermouse/)
- [LinearMouse](https://linearmouse.org/)
- [BetterMouse](https://better-mouse.com/)
- [MOS](https://mos.caldis.me/)
- Another version of Mac Mouse Fix like [2.2.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.3) or [3.0.0 Beta 3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-3)

Hope that helps! Let me know if anythings confusing!

**Comment by samiulhsnt** [comment]
> Hey @samiulhsnt,
> 
> Thanks for getting back! I now finally have time to look into your issue!
> 
> Here are some things you could test to shed light on things:
> 
> 1. In MMF 3.0.0 Beta 4 if you go to the 'Buttons' tab and click 'Reset to defaults...' with your mouse it should tell you how many buttons your mouse has. How many buttons is that?
> 2. Do other versions of Mac Mouse Fix work? You could test [2.2.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.3) and [3.0.0 Beta 3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-3). After you download another version, it's best if you delete all other versions of Mac Mouse Fix and restart your computer before testing it.
> 3. Record some Console Logs of what Mac Mouse Fix does internally when you click buttons on your mouse:
>    
>    1. Open and enable Mac Mouse Fix Beta 4
>    2. Go to Console.app > Action and enable 'Include Info Messages' and 'Include Debug Messages'
>    3. Go to Console.app > Search and enter 'Mac Mouse Fix'
>    4. Go to Console.app > [Your device name] and click 'Start streaming'
>    5. Click some buttons on your mouse (other than Mouse Button 1 and Mouse Button 2 (aka left click and right click))
>    6. Copy-paste logs which occured around the time when you clicked the buttons and send them to me.
> 
> Explanation:
> 
> Mac Mouse Fix uses some low level APIs to determine on which mouse you are clicking a button. When those low level APIs fail, it just ignores that click. Several of the things point to these APIs not working correctly for your mouse.
> 
> The tests above should give more insight into what's going on especially the Console Logs.
> 
> Thanks for helping out!
> 
> Oh and in the mean time if Mac Mouse Fix isn't working I can recommend these alternatives to you:
> 
> * [Steermouse](https://plentycom.jp/en/steermouse/)
> * [LinearMouse](https://linearmouse.org/)
> * [BetterMouse](https://better-mouse.com/)
> * [MOS](https://mos.caldis.me/)
> * Another version of Mac Mouse Fix like [2.2.3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.2.3) or [3.0.0 Beta 3](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-3)
> 
> Hope that helps! Let me know if anythings confusing!

**Comment by noah-nuebling** [comment]
Hey @samiulhsnt, did the bug go away or should I reopen this?

**Comment by MSamiulHasnat** [comment]
It is not solved, Let me give you a screenshot

**Comment by MSamiulHasnat** [comment]
<img width="662" alt="Screenshot 2022-11-01 at 8 55 49 AM" src="https://user-images.githubusercontent.com/58338543/199252121-9d2dccdd-7e07-4778-8de6-f2f6a1226d94.png">
<img width="662" alt="Screenshot 2022-11-01 at 8 57 09 AM" src="https://user-images.githubusercontent.com/58338543/199252155-c74225b2-0978-472f-a6c3-c5e8e8b07cf4.png">
<img width="1440" alt="Screenshot 2022-11-01 at 9 28 19 AM" src="https://user-images.githubusercontent.com/58338543/199252171-154bfd4d-eea8-4654-b943-46dd034ccd81.png">
Look at these, it says 5+ buttons but captures only the additional two buttons with primary buttons. And also look at the consol log

**Comment by noah-nuebling** [comment]
Thanks for those screenshots. Another user with the same problem had "0 buttons" showing up for their mice. But that's not the case for you so that's interesting.

When you click buttons there should be logs in the Console starting with "Received CG". For each "Received CG" log there needs to be a messages starting with "Received HID" shortly before. Otherwise the button click will be ignored by Mac Mouse Fix. My theory is that something is preventing the "Received HID" messages from occuring on your system.

This is what it should look like

<img width="1552" alt="Screenshot 2022-11-01 at 15 11 05" src="https://user-images.githubusercontent.com/40808343/199255310-115d221c-133d-4f77-9a24-46a8d35ffe2b.png">

You can filter for "Mac Mouse Fix Helper" instead of just "Mac Mouse Fix" and also filter for "Received" to find these logs more easily because there will be thousands of logs each second.

**Comment by stevenya97** [comment]
Having the same issues here with the middle button on my Razer Orochi V2 on 2.2.3. Was fine before the upgrade to Ventura. Tried some of the recommended fixes like removing from Accessibility settings, reinstall after deleting the app and restarting. Posting the output of the log here with the 2.2.2 debug app you posted above. The Back and Forward functions I assigned work no issues.

[consolelogs-debug.txt](https://github.com/noah-nuebling/mac-mouse-fix/files/9912374/consolelogs-debug.txt)

this is my settings for reference
<img width="578" alt="Screenshot 2022-11-01 at 12 47 36 PM" src="https://user-images.githubusercontent.com/10717304/199289668-ad81342d-09ea-4d3c-87a9-16de55d5a754.png">

**Comment by noah-nuebling** [comment]
Hey @stevenya97, thanks for the info!

In the logs you sent I can't see any signals from the middle button. Does this [online mouse test](https://www.onlinemictest.com/mouse-test/) pick up your middle button?

**Comment by stevenya97** [comment]
@noah-nuebling I figured it out! The test failed to detect the middle mouse button so I tried it again on my Windows PC. It worked perfectly fine there and was detected on the test site which made me think it had to do with the onboard memory profile. I checked Razer Synapse software and sure enough the middle mouse button was reassigned to a function that doesn't exist in MacOS. I reverted it to the default middle click function, reconnected to Mac, and now the middle mouse functions work with Mac Mouse Fix. Turns out the firmware/profile of the mouse buttons does override certain standard mouse functions on Mac. I likely changed the function on my Windows PC by accident sometime between Ventura releasing and today. Sorry for the panic!

Maybe if more people report this as an issue, you could write a footnote somewhere to try to reset their mouse. Cheers!

**Comment by noah-nuebling** [comment]
No worries! Glad that's figured out. Thanks for getting back.

> Maybe if more people report this as an issue, you could write a footnote somewhere to try to reset their mouse.

Yes that might be a good idea, thanks for your input!

**Comment by noah-nuebling** [comment]
@samiulhsnt, I made some changes that might help with your issue:

[MacMouseFixApp-ForSamiul.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/9914712/MacMouseFixApp-ForSamiul.zip)

Let me know if you notice any difference!

**Comment by noah-nuebling** [comment]
I'll close this Issue now as it has been resolved for the other person with the same problem. 

Let me know if the problem still occurs and I'll reopen this Issue.

Thanks for your help!

**Comment by noah-nuebling** [comment]
Also the fix from "MacMouseFixApp-ForSamiul.zip" is implemented in the latest [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5) if you want to check it out!

**Comment by kaygdotorg** [comment]
Hey, I am using the beta6 and I am experiencing this issue. I had everything working fine on v2 until I accidentally disabled accessibility perms of Mac Mouse Fix (which also prevents the mac from receiving any input btw, maybe that's a separate issue). I switched to v3beta6, hoping to get rid of the bug but nope, the middle button is not detected and upon trying to restore defaults, I get this:

<img width="204" alt="image" src="https://github.com/noah-nuebling/mac-mouse-fix/assets/30401343/d8da99f2-92fe-4e05-bd56-affd5dd6ba4f">

<img width="699" alt="image" src="https://github.com/noah-nuebling/mac-mouse-fix/assets/30401343/880961b4-c3aa-420a-85eb-d1806fc4e5f5">

**Comment by cmdrkatee** [comment]
UPDATE: Issue fixed. I think. 

Hi there, I'm Using Beta 5 after troubleshooting and reading these threads. I have the same issue as above, and tried resetting the mouse profile on my windows PC, as mentioned by @stevenya97. 
I'm still getting the issue where the middle button is not recognised, but the mouse is including that it has 6 buttons. 
![Screenshot 2024-03-29 at 11 25 35](https://github.com/noah-nuebling/mac-mouse-fix/assets/165340706/6ab77323-9112-4e92-b01d-be2d6733ea1d)
![Screenshot 2024-03-29 at 11 25 15](https://github.com/noah-nuebling/mac-mouse-fix/assets/165340706/c4cc753c-b2be-4041-9265-0c13f7df95aa)
![Screenshot 2024-03-29 at 11 24 44](https://github.com/noah-nuebling/mac-mouse-fix/assets/165340706/9f03d491-0feb-41c0-a936-8ace6e1c4298)
