### ISSUE TITLE
Horizontal scroll navigates back to previous page [bug]

### ISSUE THREAD

**Issue by kujohn** [noah-nuebling/Mac-Mouse-Fix#430]
## Description

When doing the horizontal scroll to the left, it reaches the end and navigates back to the previous page.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Ventura
Mouse Model: Logi MX Ergo

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @kujohn, thanks for your feedback! 

This is intended behaviour, could you elaborate why and in which situations it is bothering you?

**Comment by noah-nuebling** [comment]
Like is there a specific website or app where you find the behaviour annoying?

**Comment by kujohn** [comment]
This is for Safari. When I am moving horizontally left and right, sometimes it accidentally navigates the history to back.

**Comment by noah-nuebling** [comment]
Gotcha. Do you have a preferred solution in mind? Like just disable being able to go back and forward entirely or is there something to make it harder to trigger accidentally that you could think of?

Also, are you using the Smooth Scrolling “with Inertia” option?

**Comment by noah-nuebling** [comment]
Hi @kujohn, in the latest [3.0.0 Beta 6](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-6) you can now turn off this behaviour by disabling the "Trackpad Simulation" option.

Hope that works for your! If you have more troubles let me know.
