### ISSUE TITLE
Smooth Scrolling breaks scrolling in Thunderbird [bug]

### ISSUE THREAD

**Issue by l33** [noah-nuebling/Mac-Mouse-Fix#431]
## Description

Once I enable Smooth Scrolling I can no longer scroll the folder and the email pane of Thunderbird (red area in screen shot). The view which shows the current e-mail is still scrollable (green area in screenshot). Disabling Smooth Scrolling immediately fixes scrolling.

![image](https://user-images.githubusercontent.com/775772/199257441-bbcea8b7-4ca7-4d88-86f9-c5e580309f0b.png)

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0 Beta 4
macOS Version: 12.6
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @l33 thanks for you feedback. This issue shouldn't occur under 3.0.0 Beta 3 or if you build the app from source from the `version-3` branch. 

I'll try to push an update that fixes this soon.

**Comment by l33** [comment]
I have not tried Beta 3. I will drop a note when I have.

Probably the same issue is also happening in LibreOffice Calc.

**Comment by noah-nuebling** [comment]
This is the latest build:

[MacMouseFixApp-ForLee.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/9911175/MacMouseFixApp-ForLee.zip)

**Comment by noah-nuebling** [comment]
> Probably the same issue is also happening in LibreOffice Calc.

Yes probably.

**Comment by l33** [comment]
I cannot test Beta 3 because the helper _Mac Mouse Fix Helper_ does not appear in _System Preferences_ ->  _Security & Privacy_ -> _Privacy_ -> _Accessibility_. Manually adding it using the + does not work because I can only select the app and not the helper. If I start Beta 4 the helper does appear.

**Comment by noah-nuebling** [comment]
Hey Lee, try these instructions: https://github.com/noah-nuebling/mac-mouse-fix/discussions/101?sort=new

Let me know if anything’s unclear

**Comment by noah-nuebling** [comment]
Hey Lee, your scrolling problem should be fixed in [3.0.0 Beta 5](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-5)!
The accessibility issues should also not occur under Beta 5.

If you're still having the same issues, please open a new Issue or let me know so I can reopen this one. Thanks!

Also see #413 which I think is the same bug.
