### ISSUE TITLE
Configuring the middle button click to the middle click functionality does not always work and includes an annoying lag. [bug]

### ISSUE THREAD

**Issue by azrielgold** [noah-nuebling/Mac-Mouse-Fix#437]
## Description

Configuring Mac Mouse Fix to use the Middle Click functionality for middle button clicks either works with a noticeable lag and sometimes misses clicks.

## Steps to reproduce

1. In Mac Mouse Fix's preferences, assign the 'Middle Click' option to Middle Button > Click.
2. Open Apple Safari (or any other app with tabs).
3. To reproduce the lag, open a second tab. Middle click anywhere on the tab (not on the small X). Notice a lag between the middle click and the tab closing. When Mac Mouse Fix is disabled, the tab closes immediately.
4. To reproduce the middle clicks that don't register, open a webpage in Safari (or any other web browser) with many hyperlinks (for example a Google search). Middle click several results quickly. Notice that not all results open. (When Mac Mouse Fix is disabled, all links open.)

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 12.6.1
Mouse Model: Logitech MK120 (a plain simple wired mouse)

## Additional Comments

The ideal solution would be not to capture middle clicks at all when middle click is set to middle click. Thanks for your great work!

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi thanks for reaching out! Try removing the "Double Click" action. That should remove the delay.

Let me know if you have more issues or questions!

**Comment by azrielgold** [comment]
It did solve the problem. Thanks again!

**Comment by noah-nuebling** [comment]
Yes, glad to help! :)
