### ISSUE TITLE
More action request

### ISSUE THREAD

**Issue by MarcGondran** [noah-nuebling/mac-mouse-fix#44]
Thanks for this awesome app ! I would love to be able to set other action with the side button as : Display MissonControl and Display the Dock !

It would be perfect !

Cheers

**Comment by noah-nuebling** [comment]
Hey there MarcGondran, thanks for letting me know what you are looking for when it comes to new features. I'll definitely take your feedback into consideration.

But I'll have to let you know, that I'm very slow to release new stuff so please don't hold your breath for anything. 

In the meantime, you might want to check out some alternatives to Mac Mouse Fix which provide more extensive remapping features.
I can recommend [SteerMouse](http://plentycom.jp/en/steermouse/). Some other great alternatives which should suit your needs are Smooze, USB Overdrive, or ControllerMate.

**Comment by noah-nuebling** [comment]
You can now do the things you were asking for and much more in the new [2.0.0 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)!

Displaying the Dock is only sort of supported though. To use it, choose the "Keyboard Shortcut..." action and then enter '⌥⌘D'. '⌥⌘D' is the default keyboard shortcut for 'Turn Dock Hiding On/Off'. You'll now be able to use that right from your mouse. I hope that's close enough to what you had in mind. If you had something slightly different in mind or have any more input let me know!
