### ISSUE TITLE
Keyboard input lag and app freezes when mac mouse fix is enabled [bug]

### ISSUE THREAD

**Issue by tomsotte** [noah-nuebling/Mac-Mouse-Fix#444]
## Description

For as strange as it sounds since 2 weeks ago I've started having problems with the MacBook Pro 16 (2019) on macOS Monterey 12.6.1 and Mac mouse fix 2.2.0 (6943).

The problems were that everything I did appeared to be lagging, every action such as typing in chats, clicking buttons, scrolling, moving between virtual desktops. The lag was very annoying but the culprit were the total app freezes when opening Activity monitor or during Teams screen sharing calls.
I've tried everything: unplugged every external devices, just kept the Wi-Fi on, run some cleanup apps, tried to reset SMC, disabled auto switch of the graphic card.
I'm trying to describe the problems here as they might help somebody else with the same problems as I had.

After some trial and errors I've found an answer about someone suggesting that the problems might be caused by event taps https://forums.macrumors.com/threads/macbook-pro-16-lagging-when-clicking-typing-with-integrated-gpu-but-not-with-discreet-gpu.2299382/?post=30013566#post-30013566
After investigating with `osqueryi` I've found that mac mouse fix was enabled. After disabling it all the lag and problems I experienced stopped.
I hope this might help somebody else while also improve this very helpful tool.

## Context

Mac Mouse Fix Version: 2.2.0
macOS Version: 12.6.1
Mouse Model: –

**Comment by noah-nuebling** [comment]
Hi @tomsotte, sorry for the late reply! I'm glad you could fix your issue and let me know if you still experience any similar issues. 

I think I've experience something similar after disabling accessibility for Mac Mouse Fix Helper when it was running. But this seemed to be an issue with any app that has event taps, so I'm not sure it's something I can do much about on my end and should probably be addressed by Apple.

Either way thanks for your feebback and happy holidays!
