### ISSUE TITLE
Disable acceleration [enhancement]

### ISSUE THREAD

**Issue by ghost** [noah-nuebling/Mac-Mouse-Fix#449]
## Description
I hope to add the option to disable mouse acceleration, then this software will be completely perfect!

## Rationale
Mouse acceleration does not match human muscle memory (the hand moves the same distance but the cursor may move a different distance)
In addition, I play games on Windows, which makes this switch more difficult

## Additional info
Thank you for making such great software!
After switching to a mouse, I tried software such as steermouse, which received many recommendations and even charges, and finally found that this software meets my needs perfectly, every feature is very useful, like zooming and horizontal scrolling, which many similar software does not do, and the performance is very good!
Really thank you very much! Love you❤️

**Comment by ghost** [comment]
In fact after ten minutes of adaptation found that mouse acceleration is not so deadly 😂
But this is still a chance to make this software even better 😄

**Comment by noah-nuebling** [comment]
Hey @SamyukL thanks a lot for your kind feedback :)

I do plan to bring improvements to mouse acceleration at some point so stay tuned 😎
