### ISSUE TITLE
Max speed of scroll acceleration with "macOS" mode is way higher than macOS's [bug]

### ISSUE THREAD

**Issue by DrJume** [noah-nuebling/Mac-Mouse-Fix#459]
## Description

When having `Scroll Speed` set to "macOS" the acceleration goes way higher than the default macOS behaviour. This leads to huge scrolls/jumps after a few fast scrolls when scrolling through a long document. 

macOS seems to cap the maximum scroll distance/speed to a comprehensible speed.

## Steps to reproduce

1. Set `Scroll Speed` to "macOS"
2. Scroll fast in a long document

## Context

Mac Mouse Fix Version: 3.0.0 Beta 5
macOS Version: 12.6.1
Mouse Model: –

**Comment by DrJume** [comment]
Screen recordings:

<details>
<summary>Native macOS with MFF disabled</summary>

https://user-images.githubusercontent.com/12785972/205960669-7559ce12-3e28-4753-bf8b-ebaa0119d442.mp4
</details>

<details>
<summary>MMF with Scroll speed set to "macOS"</summary>

https://user-images.githubusercontent.com/12785972/205961021-b045522b-1c9e-416f-92d0-c7f847932e53.mp4
</details>

**Comment by noah-nuebling** [comment]
Hi @DrJume, thanks a lot for your feedback! 

Mac Mouse Fix has a feature where the scrolling speed ramps up more and more as you keep quickly scrolling into one direction. This wasn't tuned properly in previous MMF 3 Betas. But in the new [3.0.0 Beta 6](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-6) I spent a lot of time to make it harder to trigger accidentally and to make the way it speeds up more gradual at the beginning so you feel more in control.

For the "macOS" scroll speed, I totally disabled the feature.

I'll close this issue now assuming it's been resolved.

Let me know if this makes sense or if you have any more questions!
