### ISSUE TITLE
Can't completely disable scrolling [enhancement]

### ISSUE THREAD

**Issue by yazan-abbas** [noah-nuebling/Mac-Mouse-Fix#461]
## Description
MMF 3.0 beta 5 interferes with Steer Mouse. I can't use functions mapped to the keyboard modifier   mouse wheel programmed with Steer Mouse. I tried disabling MMF scrolling from the menu bar and also disabling all options in the MMF scrolling pane. Only thing that works is to disable MMF from the General options window.

## Rationale
I really like MMF and use it to map touchpad gestures to mouse buttons. I don't need the MMF scrolling options and prefer to use steer mouse to fine tune my mouse wheel. It would be nice if MMF and steer mouse can coexist as it is a powerful combination.

## Additional info
Using logitech g602, running on macOS 12.6

**Comment by noah-nuebling** [comment]
Hi @yazan-abbas, I've made a lot of changes to the scrolling settings in the latest [3.0.0 Beta 6](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-6). I'll close this issue now, assuming it's been resolved. If not please let me know or open a new issue. Thanks!

**Comment by yazan-abbas** [comment]
Hi Noah,

Thanks, modifying the scrolling from steer mouse works perfectly now.

Cheers!

Yazan

**Comment by noah-nuebling** [comment]
Great thanks for letting me know!
