### ISSUE TITLE
App is not enabling [bug]

### ISSUE THREAD

**Issue by NaderLobandi** [noah-nuebling/Mac-Mouse-Fix#464]
## Description

The enable button does not work. The functions are not applied. I tried to reinstall the app, but the issue remains.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 13.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @NADER1196, thanks for reaching out!

Does the latest [3.0.0 Beta 6](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-6) work for you?

**Comment by noah-nuebling** [comment]
Hey @NADER1196 I'll close this now assuming it's been resolved. Let me know if you have any more issues or questions.
