### ISSUE TITLE
Mouse click [enhancement]

### ISSUE THREAD

**Issue by Largofey** [noah-nuebling/Mac-Mouse-Fix#466]
## Description
The mouse wheel click, to close tabs or open a link in a new tab does not work when you assign "hold" on the mouse wheel. 

## Rationale
-

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi @Largofey, thanks for reaching out!

Try the "Middle Click" option, in MMF, it should allow you to open and close tabs. 
Alternatively you can [uncapture](https://github.com/noah-nuebling/mac-mouse-fix/discussions/112) the Middle Button to have it work as if MMF wasn't enabled.

Hope that helps! Let me know if you have more questions.

**Comment by truongvantuan** [comment]
It working, thanks
