### ISSUE TITLE
3.0.0 Beta 6 (21668) Button 5 in this version is reversed [bug]

### ISSUE THREAD

**Issue by SuperDaniel-cn** [noah-nuebling/Mac-Mouse-Fix#468]
## Description

After I upgraded to 3.0.0 Beta 6 (21668), I tried to use button 5 to switch the desktop, but it was the opposite of the drag direction of the pre-upgrade version. Button 4 has the same movement direction problem, can you fix it?

## Steps to reproduce

1. Press the button 5
2. Drag and drop to switch the desktop

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: macOS 13.1
Mouse Model: RZ01-03850

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by alohaquando** [comment]
This is also happening with "Scroll & Navigation" and "Spaces & Mission Controls" which is very jarring. An option to select which direction to use would be greatly appreciated!

**Comment by noah-nuebling** [comment]
Hey guys, thanks for reaching out!

In Beta 6 the Click and Drag direction follows the trackpad swipe direction. You should be able to flip the direction by going to System Settings > Trackpad or System Settings > Mouse and then flipping the "Natural scrolling" toggle. 

I agree it would be nice to have a toggle for this inside Mac Mouse Fix.

Hope that helps a little! Let me know if you have more questions.

**Comment by SuperDaniel-cn** [comment]
> Hey guys, thanks for reaching out!
> 
> In Beta 6 the Click and Drag direction follows the trackpad swipe direction. You should be able to flip the direction by going to System Settings > Trackpad or System Settings > Mouse and then flipping the "Natural scrolling" toggle.
> 
> I agree it would be nice to have a toggle for this inside Mac Mouse Fix.
> 
> Hope that helps a little! Let me know if you have more questions.



@noah-nuebling 

There seems to be a bug here. When I toggle Mouse ->  "Natural scrolling" in the system Settings, the direction doesn't change at first. Then I try to toggle "Natural scrolling" on System Settings > Trackpad, but the scrolling direction still doesn't change. Then I messed around with the MMF and the options in the system, and finally I found that the direction was normal. My current Settings are shown, with all three options open. This is the same result as before I changed the Settings. The only difference is that I changed the Settings and restored them.

So I wonder if there is a bug that requires you to manually change the Settings to make the desired configuration work.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/27357588/208426227-fb221ace-81da-4f9f-9d5e-38ecb89737d6.png">

**Comment by noah-nuebling** [comment]
Hey guys! The click and drag direction should now properly match the trackpad and magic mouse gesture direction in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). You can change the direction by toggling 'natural scrolling' in system settings. If you have any other questions, let me know. Thanks!

**Comment by noah-nuebling** [comment]
@SuperDaniel-cn thanks for your feedback. I can't reproduce this on my end. For me the click and drag direction changes immediately upon toggling natural scrolling in system settings.

If you still want this problem to be addressed, please open a new issue. Thanks.
