### ISSUE TITLE
3.0.0 Beta 6 has super slow space movement [bug]

### ISSUE THREAD

**Issue by JensMertelmeyer** [noah-nuebling/Mac-Mouse-Fix#469]
## Description

Version 3 and beta 3 (up to beta 5) had normal behaviour when "Spaces & Mission control" for holding down a mouse button. With beta 6, it is now
1. Very slow and sluggish
2. Horizontally inversed

## Steps to reproduce

1. Set a "click and move" action to "Spaces & Mission control"
2. Make sure at least two spaces are open in macOS
3. Hold down the mouse button and move it to the left and to the right to switch between spaces

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 12.6.1
Mouse Model: Razer Pro Click Mini (5 Buttons, also acts as a keyboard)

**Comment by noah-nuebling** [comment]
Hey there, thank you for your feedback. The click and drag direction should now match the trackpad and magic mouse gesture direction in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). You can change the direction by toggling 'natural scrolling' in system settings. If you have any other questions, let me know. Thanks!
