### ISSUE TITLE
add a option for hold shortcuts [enhancement]

### ISSUE THREAD

**Issue by ameerzaheer** [noah-nuebling/Mac-Mouse-Fix#477]
## Description
Like if i perform a single click on the mouse it will do the assigned action and hold that same key it should perform a different action, example: hold a mouse button will act like hold shift for horizontal scrolling.

## Rationale
it will make the make timeline navigation in fcp much easier.

## Additional info
–

**Comment by larryqiann** [comment]
It seems like on the MX Anywhere 3, holding the button on the side already does horizontal scrolling. This seems to be configurable in Logi Options but not MMF3, which also leads to click and drag not working for those buttons. 

Is this feature done internally to the mouse?

**Comment by noah-nuebling** [comment]
Hi @ameerzaheer, thanks for your feedback. If I understand correctly, the features you wished for are available in MMF 3!

@larryqiann Please open a new issue if you still want this addressed. Thank you.

I'll close this now, let me know if you have more questions or concerns.
