### ISSUE TITLE
Please bring back options for buttons menu

### ISSUE THREAD

**Issue by amadav** [noah-nuebling/Mac-Mouse-Fix#479]
> Removed several options from the "Click", "Click and Hold" and "Click and Scroll" Actions because I thought they were redundant since the same functionality can be achieved otherwise and since this cleans up the menus a lot. Will bring those options back if people complain. So if you miss those options - please complain.

Registering my complain. It is super helpful to see something selected from the app menu than setup individual keyboard shortcuts (which I usually override myself using karabiner anyway) and than indirectly setting them via app. Please bring it back!!

**Comment by amadav** [comment]
The options provided were also contextual. For instance, dropdown options provided for click and scroll, just made sense to that context. 

Would highly appreciate if the options are ported back. Honestly, it is one of the best things that the app does for me aside from the scrolling functionality. Stuck with beta-3 version for now. Appreciate support!! :)

**Comment by noah-nuebling** [comment]
Hi @amadav, thanks for your feedback!

Which options specifically would you like to return? 

(I only removed a select few options. Most of them were redundant to the `Click and Drag for Spaces & Mission Control` feature.)

**Comment by noah-nuebling** [comment]
Closing this now, as I brought the options back in Beta 7. Let me know if you have more questions or concerns.
