### ISSUE TITLE
Disable on a per app basis

### ISSUE THREAD

**Issue by S-n-d** [noah-nuebling/mac-mouse-fix#48]
## Description
Would love to be able to disable the functionality for specific apps.

## Rationale
Example: VLC volume is changing 70% per scrollwheel tick. A bit too much if you ask me ;-)

## Additional info
Thanks for your great work!

**Comment by noah-nuebling** [comment]
Hey there S-n-d, thank you for your feedback! I wasn't aware of this issue with VLC in particular.

Disabling the smooth scrolling for specific apps is already implemented in the latest beta of version 0.9.2 which you can download [here](https://github.com/noah-nuebling/mac-mouse-fix/releases).

**Comment by S-n-d** [comment]
@noah-nuebling superb! Thank you!
