### ISSUE TITLE
Updating beta version of app overrides button settings [bug]

### ISSUE THREAD

**Issue by amadav** [noah-nuebling/Mac-Mouse-Fix#480]
## Description

As per the title, updating app version should port existing modifications and apply it to the latest version. If not possible, provide a workaround to export button modification settings and then import it in the latest version.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 13.1
Mouse Model: Evoluent Vertical Mouse

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by amadav** [comment]
Can confirm that the issue exists for non-beta releases too. In absence of a complete fix, any way to export configuration and import one during update (especially major release) would be highly appreciated.

**Comment by noah-nuebling** [comment]
Hi there, @amadav, thanks for your feedback!

When updating from 3.0.0 to 3.0.1 the settings will be upgraded instead of being reset. I will also make future updates behave in this way if feasible.
