### ISSUE TITLE
3.0.0 Beta 6 mouse drag direction and space switch direction are inconsistent: want to improve [enhancement]

### ISSUE THREAD

**Issue by aoaim** [noah-nuebling/Mac-Mouse-Fix#481]
## Description
First of all, I must say that the mac mouse fix has improved my mouse experience by 10000 times! Really thank you so much for creating it.

I remember when I was using mac mouse fix 2, when I set Spaces & Mission control as middle button hold and drog, the direction of my mouse drag was the direction that space moved and switched. But when I updated to 3, this direction was reversed.

For example, now, when I hold down middle button and move to the right, my current space moves to the left and switches to the second space that appears from the right. This is a little uncomfortable.

## Rationale
I want to be able to give an option to control the direction of the space switch. Thank you!

## Additional info
–

**Comment by skylark36** [comment]
I’m feeling the same.

**Comment by theoneVincent** [comment]
Same feeling, the direction is not consistent with my Magic Trackpad.

**Comment by nikkufans** [comment]
Yes , need a option switch button for `click and drag` direction.

**Comment by benruehl** [comment]
Same.
Also, I bought my license just after upgrading to Beta 6 and when I downgrade to Beta 5 it says that my free time is over and does not accept the license key. So I'm stuck with this behavior and cannot go back...

**Comment by noah-nuebling** [comment]
Hey guys, thanks for chiming in! The click and drag direction should match the trackpad and magic mouse gesture direction in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). If you have other questions, let me know. Thanks!
