### ISSUE TITLE
Stops working when switch User [bug]

### ISSUE THREAD

**Issue by flossiesheep** [noah-nuebling/Mac-Mouse-Fix#487]
## Description

Every time fast-switch user (fingerprint button on MacBook Pro-M1), the "Enable Mac Mouse Fix" toggle shows on, but you have to toggle it twice (Off and On) for it to actually work.

## Steps to reproduce

1. Enable MMF
2. Switch user
3. Use side buttons/scroll wheel - nothing happens
4. Toggle MMF Off, On
5. Use side buttons / scroll wheel - now  work as expected

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Ventura 13.0
Mouse Model: Logitech MX518

## Additional Comments

Consistent - happens every time switch users. Issue also present in previous Beta versions. May be related to same problem when changing Displays. 

---

### Console Logs

https://pastebin.com/K55TiF6w

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there thanks for your feedback. I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1).

Let me know if you have any more questions.
