### ISSUE TITLE
click and drag to move spaces is backwards from trackpad gesture [enhancement]

### ISSUE THREAD

**Issue by whitebearpark** [noah-nuebling/Mac-Mouse-Fix#489]
## Description
when using 3 fingers and the trackpad to move between spaces, you drag in the opposite direction of the window you would like to move to. With mac mouse fix, holding a button and moving side to side to swap spaces behaves the opposite way; you move the mouse towards the window you'd like to go to. 

## Rationale
fixing this would make it so you don't have to retrain muscle memory from the trackpad gestures and make the program feel smoother.

Just a simple toggle or options in the settings menu would fix this as macOS provides no trackpad interpretation options

## Additional info
–

**Comment by shamruk** [comment]
Totally agree. Especially when the reverse is off. Looking forward to using this feature with pleasure

**Comment by shamruk** [comment]
Is this a line with the problem?

<img width="595" alt="Screenshot 2023-01-21 at 12 23 23 AM" src="https://user-images.githubusercontent.com/1157792/213816228-32f05090-0603-4f4e-90d1-5e43ad4a78b7.png">

**Comment by shamruk** [comment]
Fixed it and created a pull request. Works great now.

**Comment by noah-nuebling** [comment]
Hey guys, thanks for your contrubutions! The drag direction should correctly follow the system settings for the trackpad swipe direction in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). If you other questions, let me know.
