### ISSUE TITLE
Keyboard shortcuts not working [bug]

### ISSUE THREAD

**Issue by franlucc** [noah-nuebling/Mac-Mouse-Fix#496]
## Description

I tried adding the ctrl left/right arrow as well as cmd z to my 4/5 buttons and the keyboard shortcuts did not appear in the input field. I did not allow me to set any keyboard shortcuts I could think of.

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: ventura 13.1
Mouse Model: –

**Comment by noah-nuebling** [comment]
Hi! Thanks for your feedback. I've never heard of this issue, so I assume it's something specific to your setup. If you're still experiencing this, please open a new issue. Thank you.
