### ISSUE TITLE
can`t enable [bug]

### ISSUE THREAD

**Issue by valn1** [noah-nuebling/Mac-Mouse-Fix#497]
## Description

the "enable Mac Mouse Fix" switch does not change when clicked 

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: MacOS ventura 13.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by johntony366** [comment]
same issue

**Comment by noah-nuebling** [comment]
Hey there @valn1 and @johntony366,

Thanks for reaching out and I'm sorry for the late reply!

If you're still interested in trying to resolve this, there are troubleshooting steps in issue https://github.com/noah-nuebling/mac-mouse-fix/issues/648. 
If you try the steps there and let me know how it goes that would be super helpful. Thanks!

I'll close this issue now to move all the conversion around the problem to #648.
