### ISSUE TITLE
Preference pane doesn't support dark mode

### ISSUE THREAD

**Issue by SimonMayerhofer** [noah-nuebling/mac-mouse-fix#50]
## Description
If dark mode is enabled in system settings, the preference pane still shows in light mode.

## Rationale
Consistency

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi there Simon, thanks for your feedback! :)

You might want to check out the 0.9.2 Beta which does support dark mode. You can download it [here](https://github.com/noah-nuebling/mac-mouse-fix/releases).
