### ISSUE TITLE
Hotkey Zoom doesn't work in Firefox [other]

### ISSUE THREAD

**Issue by larryqiann** [noah-nuebling/Mac-Mouse-Fix#500]
Using the Keyboard Modifiers button for Zoom In or Out doesn't take effect in Firefox on macOS Ventura.

I'm not sure if this is the right place to report this since this is a Firefox issue (works elsewhere), but an Apple Magic Trackpad functions fine in Firefox for this purpose. 

Wondering if this is a problem that could be somehow fixed at all

Thanks!

**Comment by TinyMito** [comment]
Firefox 109 has changed the zoom behaviour. 

https://www.mozilla.org/en-US/firefox/109.0/releasenotes

<img width="858" alt="image" src="https://user-images.githubusercontent.com/75095713/215644938-23584c4e-bbfd-45ea-8d8b-d729d9b4efb1.png">

**Comment by larryqiann** [comment]
This appears to be for scrolling type input, not emulated pinch zoom I believe if I am not mistaken

**Comment by ib0ndar** [comment]
There are two variables in FF 

mousewheel.with_meta.action 
mousewheel.with_control.action

Meta is  the Cmd key in macOS. Cotrol is control, as usual. So, those variables can have following values:

0 – to completely disable or turn off the feature. Nothing will happen.
1 – to scroll the page
2 – to go back or forward in page history
3 – to zoom the page using reflow (Like Cmd and +/-)
5 - to zoom the page using pinch and zoom

When Mac mouse fix is set to use Cmd and scroll to emulate pinch and zoom it somehow interferes with the FF mousewheel.with_meta.action and it doesn't work. However, if you set mousewheel.with_control.action to '5', then you can zoom with Ctrl+scroll wheel. However, I use Mac Mouse Fix set to scrolling speed 'High' and Ctrl+wheel is too fast and too aggressive in FF, simply unusable :( It would be great to disable FF to intercept the keys and let the system (and Mac Mouse Fix) to do the job... But I still didn't find the way to do so.

Nevertheless it is strange that with touchpad the pinch and zoom works perfectly in FF, but Mac Mouse Fix fails to emulate it. It does perfect job in all apps, but not in FF...

**Comment by hotsno** [comment]
Thanks @ib0ndar for sharing that setting and what all of the options do (btw, how did you find out what all of the options do?)

I found that *disabling* ⌘-scroll to zoom in Mac Mouse Fix, and then enabling `mousewheel.with_meta.action = 5` allows me to now ⌘-scroll to zoom in Firefox!

1. Mac Mouse Fix > More... > App-specific settings > Add Firefox > Disable ⌘-scroll to zoom
2. Open `about:config` in Firefox, set `mousewheel.with_meta.action` to `5`

**Comment by sporkus** [comment]
> Thanks @ib0ndar for sharing that setting and what all of the options do (btw, how did you find out what all of the options do?)
> 
> I found that _disabling_ ⌘-scroll to zoom in Mac Mouse Fix, and then enabling `mousewheel.with_meta.action = 5` allows me to now ⌘-scroll to zoom in Firefox!
> 
>     1. Mac Mouse Fix > More... > App-specific settings > Add Firefox > Disable ⌘-scroll to zoom
> 
>     2. Open `about:config` in Firefox, set `mousewheel.with_meta.action` to `5`

This works perfectly for me. Thank you for your finding!

**Comment by noah-nuebling** [comment]
Hey guys, thanks for the feedback. I'll close this now assuming it's been resolved. Please open a new issue if this is still a problem.
