### ISSUE TITLE
Mouse button combos and simultaneous button clicks [enhancement]

### ISSUE THREAD

**Issue by stpork** [noah-nuebling/Mac-Mouse-Fix#503]
## Description
It would be great if MacMouseFix can capture simultaneous mouse clicks and handle them as separate button press events., which can be assigned to actions. For example - Left+Right click, Left+Middle, Back+Right, Middle+Right, etc. Also it would be nice if the app can differ the order of how buttons were pressed and hold to form the combination.

## Rationale
Some models of mouse and trackballs have very few buttons, sometimes only two. That limits the user in terms of options and they need to find some tricks to enable middle button clicks, scroll, back/forward, etc. While mouse   keyboard modifier combos are good, very often it is more practical to use pure mouse button combos.

There are apps for Windows that allow capturing mouse button combos (e.g. simultaneous pressing of left and right button) and assigning actions to them or doing button-key remaps.

For example, using the AHK app, for the 2-button trackball in Windows I've defined two combinations:
1. First click left button, hold it, then click right button and release both - "Back" action
2. First click right button, hold it, then click left button and release both - "Forward" action

It would be very nice if MacMouseFix would be able to capture simultaneous button clicks and button combos to enable even more functions. 

## Additional info
–Example - First left button, hold it, then right button = Action 1, First right button, hold it, then left button, release = Action 2, etc

**Comment by noah-nuebling** [comment]
Hey there, thanks for your feedback. This should already possible! Mac Mouse Fix just doesn't recognize left click and right click, but button combos in the way you describe should be possible. Please open a new issue, if there's still something you want addressed. Thanks.
