### ISSUE TITLE
Final Cut Timeline Zoom in/out not working anymore [bug]

### ISSUE THREAD

**Issue by timf777** [noah-nuebling/Mac-Mouse-Fix#505]
## Description

Hey man!
First of all thanks a lot for providing this app!
For about the last 2 months I used version 2.2 of this app mainly to be able to zoom in / out of the timeline in Final Cut Pro which worked pretty good.
Now I updated to 3.0.0 and this function is not working anymore.
Is this a bug or are there any setting changes I have to do?

Thank you!
Best regards,
Tim Feistner

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 12.6.2 
Mouse Model: Logitech MX Master 3

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there, thanks for reaching out and sorry for answering so late. 

I've never heard of this bug and there are no other reports of it, so I'll assume that it's something specific with your setup. If you still think this should be addressed in MMF, please open a new issue and reference this one. Thank you.
