### ISSUE TITLE
Navigation is unreliable [bug]

### ISSUE THREAD

**Issue by nulaft** [noah-nuebling/Mac-Mouse-Fix#508]
## Description
I find that using "click and drag" to navigate to the (previous) tab in Safari only works randomly half of the time.

I assume this is because I am not moving the mouse perfectly and only to the side, but slightly vertical at the same time. This might sometimes trigger a slight upwards or downwards scroll and thus prevent the navigation.

## Context
Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: macOS Ventura 13.2
Mouse Model: Logitech G500

## Additional Comments
One way to fix this:
After the user holds down the relevant button, you could delay the scrolling by dragging action until the mouse has moved for some small amount. For example, if the mouse moves one step up and then two steps to the side, then only the sideways scrolling / navigation action is triggered.

**Comment by noah-nuebling** [comment]
Hi! Thanks for the feedback! Have you used a trackpad or Magic Mouse? In my experience they have the same problems - which leads me to believe this is a bug in Safari

**Comment by nulaft** [comment]
I have done an experiment using the trackpad of my MacBook as well as using the mouse in order to get some numbers on this. I have tested Safari, Chrome and Firefox. For each browser, I attempted to invoke the backwards navigation action 80 times for each input method. These are the success rates that I got:

|   | **Trackpad** | **Mouse** |
|---------|--------------|-----------|
| Safari  | 99%          | 70%       |
| Chrome  | 99%          | 96%       |
| Firefox | 91%          | 29%       |

For me, the trackpad navigation works pretty reliably, regardless of the browser. The mouse navigation is significantly less reliable for Safari and Firefox. Chrome works just fine, however at first Chrome did not want to do the backwards navigation action at all and instead reliably scrolled horizontally. I don't know if this is reproducible.

**Comment by noah-nuebling** [comment]
Hey @nulaft, thanks a lot for the extensive tests! It might be helpful if you sent a screen recording of the unreliable navigation, because I don't think I experience the same problem, and I'm not sure what might be causing it at this point.

**Comment by noah-nuebling** [comment]
Hey there, I'll close this now. If you still think this should be addressed in MMF, please open a new issue. Thank you.
