### ISSUE TITLE
Scroll Wheel on external USB suddenly stopped working while mouse fix is enabled.

### ISSUE THREAD

**Issue by shot-codes** [noah-nuebling/mac-mouse-fix#51]
## Description

I connected a new mouse to my machine. Everything was working as expected. I only use Mouse Fix for scroll direction and smooth scrolling, button functionality I handle with Karabiner Elements. After about an hour or two, my scroll wheel stopped working, and I can see in my event viewer that the system is no longer detecting scroll events from the mouse. If i disable Mouse Fix it works again, natively.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 0.9.1
macOS Version: 10.15.7
Mouse Model: Deltaco Wired optical silent mouse

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

https://pastebin.com/4WSPLrY5

**Comment by noah-nuebling** [comment]
Hi there TheFoolishPupil, thanks for taking the time to file a bug report!

Unfortunately, I'm not sure what might be causing your issue.

You might want to try using the [latest beta version (0.9.2 Beta 5)](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/0.9.2-Beta-5) to see if that fixes things. 

If the error still occurs under 0.9.2 it would be awesome if you provided the following info to help figure this out:

- Any other applications you're using which might intercept mouse inputs except Karabiner and Mac Mouse Fix
- Whether the crash from the crash report you attached happened at the same time as scrolling stopped working for you (The crash occurred on 23. October at 11:06)
- A crash report for 0.9.2 Beta 5 or some console logs from around the same time that the issue occurred.

**Comment by shot-codes** [comment]
Hey Noah, of course, it's the least I can do for using the software you have taken time to develop and share for free. I did try to use the latest beta and then I get no behaviour changes at all with this mouse, i.e. the scroll is not reversed or smoothed; I didn't check to see if the button mapping worked. 

I like the implementation of your app because it exists in the ayst preferences which seems natural to me. I honestly don't understand how Apple hasn't introduced this feature yet. But alas, for now I will use Mos, or scroll reverse for my work mouse. At home with my Logitech I believe it is still working and will continue to use Mouse fix. Next week I'll do some more testing with the work mouse and see if I can get some more meaningful info for you. I am not positive if the crash report is from the specific time it stopped working.

Thanks for the response and good weekend to you.

**Comment by noah-nuebling** [comment]
Hey @TheFoolishPupil, sorry for the very late response, and thanks for you nice message!

You could check out the [latest 2.0.0 Beta 9 version](https://github.com/noah-nuebling/mac-mouse-fix/releases) to see if it still occurs there, if you're still interested. 
I've made lots of changes to how scroll input is processed in the versions since, and I haven't heard of anyone experiencing similar issues in a while, so there's a good chance that you issue is fixed now.

**Comment by shot-codes** [comment]
No problem, my apologies as well. Just updated to beta 11. Seems to work with the mouse the was causing me issues before, I'll wait and see if it crashes as it used to and if not I'll close the issue. Thanks for the help :)

**Comment by noah-nuebling** [comment]
Sure thing thanks for getting back :)
