### ISSUE TITLE
为什么不增加一个”在启动电脑后自动运行并启用“的功能呢？ [enhancement]

### ISSUE THREAD

**Issue by Darling-Lee** [noah-nuebling/Mac-Mouse-Fix#514]
## Description
为什么不增加一个”在启动电脑后自动运行并启用“的功能呢？每次都要手动打开并启用是不是有些麻烦？

## Rationale
为什么不增加一个”在启动电脑后自动运行并启用“的功能呢？每次都要手动打开并启用是不是有些麻烦？

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi there @Darling-Lee, thanks for reaching out! If you enable Mac Mouse Fix, you can then close the app and it will keep being active in the background. Even if you restart the computer! 

Let me know if you have more questions or concerns.
