### ISSUE TITLE
License not working! [bug]

### ISSUE THREAD

**Issue by BlackBird11** [noah-nuebling/Mac-Mouse-Fix#516]
## Description

I bought the license and it says license successfully activated, but I can not switch the "button" to on. It stays on the "off" side.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 13.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there, I'm really sorry about the late reply. Do you still need help with this? If you shoot me an email with the email address you used to buy the app, and 'refund' in the subject, I will refund you.
