### ISSUE TITLE
zoom does not work at all [bug]

### ISSUE THREAD

**Issue by huntermarlette** [noah-nuebling/Mac-Mouse-Fix#539]
## Description

I downloaded this app to be able to zoom using the scroll wheel. I want to emulate the trackpad's pinch to zoom within an app by holding the command key while scrolling up or down on the scroll wheel to zoom in or out respectively. By default, this app is bricked, but if I install the beta version this is allowed... well kind of. It says it has the command key mapped as the keyboard modifier for "zoom in or out". That would be fantastic if it worked! It literally does nothing! 

## Steps to reproduce

1. install application
2. update to beta
3. switch to the "scrolling" tab to note the keyboard modifier keys
4. hold the zoom in or out keyboard modifier (CMD in my case) 
5. observe that you wasted your time downloading this app because it does not work at all

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Ventura 13.2.1
Mouse Model: Logitech MX Master 2s

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by xyzwifi** [comment]
Me too  

Mac Mouse Fix Version: 3.0.0 Beta 6 
macOS Version: Monterey 12.51
Mouse Model: Logitech MX Master 3

**Comment by homeclubber** [comment]
Try uninstalling Logi Options, worked for me.

**Comment by noah-nuebling** [comment]
Hi there! I suggest you try version 3.0.0 - it allows you to assign Click and Scroll to zooming - or try @homeclubbers suggestion.
