### ISSUE TITLE
Invert Direction Issue [other]

### ISSUE THREAD

**Issue by arkoxco** [noah-nuebling/Mac-Mouse-Fix#544]
The Invert Direction function is not functioning properly. I have even attempted to use the new beta version, but the issue persists. Could you please address this and provide a solution?
I'm using MacOS Ventura 13.2.1

**Comment by noah-nuebling** [comment]
Hey there @arkbabayan21, please let me know what mouse you're using and if [UnnaturalScrollWheels](https://github.com/ther0n/UnnaturalScrollWheels) works for you if you turn on "Alternate detection method".

**Comment by noah-nuebling** [comment]
Also please let me know if the other scroll options and buttons options work. Thank you.

**Comment by noah-nuebling** [comment]
I'll close this issue now to keep things organized. Please open a new issue if you would like to add more info.

**Comment by noah-nuebling** [comment]
Ah I just saw your other issue https://github.com/noah-nuebling/mac-mouse-fix/issues/545 contains the mouse model so nevermind what I said, I'll write my comments again there to keep things organized, I hope it's not annoying.
