### ISSUE TITLE
Invert Direction issue [bug]

### ISSUE THREAD

**Issue by arkoxco** [noah-nuebling/Mac-Mouse-Fix#545]
## Description

The Invert Direction function is not functioning properly. I have even attempted to use the new beta version, but the issue persists. Using MacOS Ventura 13.2.1 and Mac Mouse Fix Version 2.2.3 (7603).

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 13.2.1
Mouse Model: Razer Orochi V2

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there, thanks for your feedback, please let me know what mouse you're using and if [UnnaturalScrollWheels](https://github.com/ther0n/UnnaturalScrollWheels) works for you if you turn on "Alternate detection method".

Also please let me know if smooth scrolling and click and drag gestures work. 

Please open a new issue with that info if you want to provide it. This will help me keep track of all the issues. Thank you.
