### ISSUE TITLE
Stop working after switch user. [bug]

### ISSUE THREAD

**Issue by pasyuk** [noah-nuebling/Mac-Mouse-Fix#550]
## Description

Hello,

Here is a bug: when you switch between users. Mouse scroll and additional buttons stop working at all until you disable and re-enable the Mac Mouse Fix

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6 (21668)
macOS Version: 13.2.1 (22D68)
Mouse Model: A4tech FB35C

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by AstroEngineeer** [comment]
Same problem. 
When you switch between users. Mouse scroll stop working until you disable and re-enable the Mac Mouse Fix.

**Comment by noah-nuebling** [comment]
Hey guys thanks for your feedback. I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1).

Let me know if you have any more questions.
