### ISSUE TITLE
Scrolling smoothness - Scrolling doesn't work [bug]

### ISSUE THREAD

**Issue by adamkiss** [noah-nuebling/Mac-Mouse-Fix#553]
## Description

After updating to MacOS Ventura 13.3, scrolling with MX Master 3 doesn't work if smoothness is set to anything other than "off". If it's off, I can scroll stuff (apps, safari websites, etc), but if I switch the dropdown to regular or high, scrolling doesn't work

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 13.3
Mouse Model: Logitech MX Master 3

## Additional Comments

Notebook is macbook 14 m1

---

### Console Logs

https://pastebin.com/vyCT4sN5

Logs:
- start streaming with debug
- scroll a bit with smoothing "off"
- switch to "regular"
- try to scroll
- switch back to "off"
- scroll

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there @adamkiss thanks for your feedback! Does this still happen under Mac Mouse Fix 3?

**Comment by adamkiss** [comment]
It seems to work now, yes!
