### ISSUE TITLE
Menu bar icon [enhancement]

### ISSUE THREAD

**Issue by aalek-k** [noah-nuebling/Mac-Mouse-Fix#559]
## Description
Please provide an option to turn on menu bar icon just to know if the app is active or not. 

## Rationale
I have to different setups of mouse functions on Mouse Fix and Karabiner Elements app, I'd like to have an option to quickly see which of these apps is active.

## Additional info
Love your app! Will try to support you the next month. Broke for now LOL

**Comment by noah-nuebling** [comment]
Hey there, I'm sorry for the late reply. Mac Mouse Fix 3, which is currently in Beta, but pretty much finalized features a menu bar icon! See [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). 3.0.0 costs a few dollars. I'm sorry about your financial troubles. If you shoot me an email I might be able to help out with that.
