### ISSUE TITLE
Invert side buttons "move between spaces" function [enhancement]

### ISSUE THREAD

**Issue by AndriyBalakalchuk** [noah-nuebling/mac-mouse-fix#56]
## Description
It Will be really great to get all same but with inverted or with the possibility to invert the linked side buttons move space right and move space left

## Rationale
first of all I really like your mousefix!!! I have Bluetooth mouse Razer Atheris and native driver (synapse 2) after installing macOS Big Sur was lost (don't work)

Your decision is great and the best that I found on the web, my mouse side buttons alive now!

And only one little part made me sad - is when I press the first side button I do the step right (see case 1 button 1 on the image below) and when I press the second side button I do the step left (see case 1 button 2 on the image below), I only want to invert this to that  - when I press the first side button I do the step left (see case 2 button 1 on the image below) and when I press the second side button I do the step right (see case 2 button 2 on the image below)
image: [https://i.ibb.co/58m8mt0/description.jpg]

## Additional info
I want to say that I don't try to add you more work and I was really trying to find at your files and code where I can rewrite button remap to my (inverted) variant, but I don't know how it works and can't find right file and code part... 

If you give me info where I can find rows to swap them it will be the end of my issue

**Comment by noah-nuebling** [comment]
Wow @AndriyBalakalchuk thanks for your awesome feedback, as well as your kind words! @divadretlaw 's pull request has been implemented in [Mac Mouse Fix 1.0.0](mousefix.org)

Hope you're having a great time mate!

Noah
