### ISSUE TITLE
Match scrolling animation to refresh rate. [enhancement]

### ISSUE THREAD

**Issue by GavBeats** [noah-nuebling/Mac-Mouse-Fix#560]
## Description
I could be wrong but it looks like the scrolling animation is only locked to 60 Hz even when a external display is above the value. I am not entirely sure if it is possible to match the animation to the external display refresh rate but it would be a great feature.

## Rationale
Animation is choppy on display higher than 60 fps.

## Additional info
Thank you

**Comment by noah-nuebling** [comment]
Hi @GavBeats thanks for reaching out!

Does this choppiness also occur when you use the [latest Mac Mouse Fix 3.0.0 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases)?

The app does have code that is supposed to match the scrolling animation refresh rate to the current display, but I haven't had the opportunity to test these capabilities, so it might not be working properly at the moment.

**Comment by GavBeats** [comment]
After testing it, it only happens when I first plug the monitor in. If I quit mouse fix and open it again it seems the issue goes away. Not a huge deal. I’ve also had issues before were the monitor acts funny when I first plug it in so it may not even be your app that’s causing the issue.

Thanks for replying. :)
________________________________

**Comment by noah-nuebling** [comment]
Thanks for your reply :)
