### ISSUE TITLE
Switching the account on macOS [bug]

### ISSUE THREAD

**Issue by awesem-szymon** [noah-nuebling/mac-mouse-fix#565]
## Description

Hi, your app is great!

I have a small issue. I use 2 accounts on my mac, and when I switch the account I have problems with scrolling... is this sth you can reproduce and fix?

Thanks!

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 13.3.1 (a) (22E772610a)
Mouse Model: Evoluent VMDS Vertical Mouse D Small

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there thanks for your feedback, I'm glad you enjoy the app! I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1).

Let me know if you have any more questions.
