### ISSUE TITLE
MarginNote3 horizontally scrolling not work. [bug]

### ISSUE THREAD

**Issue by tignioj** [noah-nuebling/Mac-Mouse-Fix#569]
## Description

MarginNote3 horizontally scrolling not work.

## Steps to reproduce

shift scroll not work.

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 13.3 (22E252)
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there @tignioj, thanks for your feedback!

I tested this with MMF 3.0.1 and it seems to work well on my end. If this is still a problem, please open a new issue. Thanks!
