### ISSUE TITLE
Button action - reverse direction options [enhancement]

### ISSUE THREAD

**Issue by kecinzer** [noah-nuebling/Mac-Mouse-Fix#570]
## Description
I start using version 3.0.0 Beta 6 and it's almost perfect. Great work. Only thing that I miss from version 2.x is invert direction for buttons gestures. Like button click and drag for Spaces @ Mission control.

## Rationale
Can you please add option for reverse direction for this gestures?
- Spaces & Mission Control
- Scroll & Navigate
- Zoom In or Out

And may be more features that make sense to add this option.

Thank you.

## Additional info
–

**Comment by sevtdy** [comment]
Same, for me I use click and drag for switching windows, I also reverse scroll direction. 

I think when someone choose reverse scroll direction, they expect the same behavior for switching windows:
scroll down page go down, drag left switch to left side window.
It makes more sense to me.

for reference: 
I also using Logitech master 3s, the window navigation setting will automatically match the scroll direction setting like I mention before

**Comment by noah-nuebling** [comment]
Hey guys, thanks for your feedback! The click and drag direction should match the trackpad swipe direction in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). 

@sevtdy I don't think I want the click and drag direction to depend on the scroll direction. Currently it depends on the trackpad swipe direction. I might introduce a separate toggle to invert the click and drag direction at some point. 

If you have other questions, objections, or probems you want addressed please open new issue. Thank you.
