### ISSUE TITLE
External display seems not supported [bug]

### ISSUE THREAD

**Issue by filibie** [noah-nuebling/Mac-Mouse-Fix#572]
## Description

When external display (Samsung M7 4k resolution) is connected via Thunderbolt 3 cable, Mac Mouse Fix just doesn't seem to work when switching spaces with middle mouse button gesture. It start switching, but just seems to latch to this mode, and makes very little movement of spaces with lots of travel on the mouse itself. I have troubles exiting space-switching mode, clicking the middle mouse button few times seems to do it. Mac Mouse Fix seems to work fine on internal display on MacBook Pro 13-inch 2017 while external display is still connected. I can attach logs but i would need to know how to capture them.

## Steps to reproduce

1. Install and enable Mac Mouse Fix,
2. Connect mouse,
3. Connect external display via thunderbolt 3 cable,
4. Try to use space switching gesture on external display

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Ventura 13.3.1 (a)
Mouse Model: Logitech G502 Hero 

## Additional Comments

Other gestures seem to be affected as well, although Mission Control (MMB+up) works almost good, but requires lots of mouse travel. This issue might have to do with hard-coded pixel distance values for gesture detection tuned for internal display resolution, and when a display with much bigger resolution is connected, more mouse distance is needed and also releasing middle mouse button doesn't exit the gesture.

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @archloner, thanks for reaching out!

Can you share a screen recording of the issue? Thank you!

**Comment by filibie** [comment]
https://github.com/noah-nuebling/mac-mouse-fix/assets/40185072/795e3f79-c8da-4e44-b49d-865ebc05c93f

Sure @noah-nuebling, hope this screen capture shows the issue well

I'm trying to go through all 3 spaces with mouse gestures, when I can't change the space anymore I click middle mouse button few times which brings me back to the starting space, and I end the screen recording.

**Comment by noah-nuebling** [comment]
Thanks for that @archloner. Does this also happen, when you use the [latest 3.0.0 Beta 6](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-6)?

**Comment by filibie** [comment]
@noah-nuebling 
With latest build installed `3.0.0 Beta 6`, changing spaces feature works on external monitor but takes substantially longer time to complete the animation, than on a built-in screen. Animation takes longer to complete and there are some stutters along the way, now, I'm not really sure how much of this is caused by my machine being a bit old for 4k monitor, as i experience few performance issues with this display connected anyway, but changing spaces with control+arrow is much more instant and fluid so i guess there's still some animation performance issue on the `mac-mouse-fix` side.

Another issue with this beta version i noticed is that the meta key is no longer a middle mouse button but rather i need to use 'back' button on the mouse for the gesture to register, it seems like some mapping issue. I tested on Logitech G502 Hero.

I can attach application logs if you need them and can tell me where to find them/how to capture them.


**Edit:** I noticed the first half of the animation is slow, second half is quick and fine. I mean, when the display is half-way to the next space, it starts to move fast.

**Comment by noah-nuebling** [comment]
Hey there @phillyb33, thanks a lot for getting back. I'm really sorry for the late reply.

It does sound like there are some performance issues there which I might be able to do something about in Mac Mouse Fix. 

If you still have these issues in the latest 3.0.1 release and want them to be addressed, please open a new Issue. Thank you.

It sort of seems like when system is under heavy load it deprioritizes Mac Mouse Fix to be able to run the OS animations faster, but because Mac Mouse Fix drives the OS animations, it ends up being stuttery. But this is just a an idea, I'm not sure.
