### ISSUE TITLE
Fast User Switching [bug]

### ISSUE THREAD

**Issue by ghost** [noah-nuebling/Mac-Mouse-Fix#574]
## Description

If you use fast user switching on the Mac, Mac Mouse Fix stop working between login's. You have to run the program again, disable then re-enable to get it to work. Thank you.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Ventura 13.4
Mouse Model: Logitech MX Master 3 for Mac

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.
