### ISSUE TITLE
建议增加“按住并滚动”的“桌面切换“功能。 [enhancement]

### ISSUE THREAD

**Issue by ghost** [noah-nuebling/Mac-Mouse-Fix#575]
## Description
建议增加“按住并滚动”的桌面切换功能，感觉更方便使用。

## Rationale
软件版本：Mac mouse fix 3.0.0 beta 6
我的鼠标：微软简约精简鼠标

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi there! Thanks for your feedback. This was added back in in a later release, so I'll close this. Let me know if you have any more questions or concerns.
