### ISSUE TITLE
Beta does not allow Mission Control to be assigned to a click [bug]

### ISSUE THREAD

**Issue by develand-acams** [noah-nuebling/Mac-Mouse-Fix#580]
## Description

In 2.0 you can assign Mission Control to a button. I use that a lot. Love it.

## Steps to reproduce

1. Install beta.
2. Try and assign Mission Control to a click.

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 13.4 (M2 Pro)
Mouse Model: Evoluent VerticalMouse VMDL Large, Right Hand Ergonomic Mouse, Wired

## Additional Comments

Love the app. Bought a license for the beta. This is the best in category for sure!

---

### Console Logs

–

### Crash Reports

–

**Comment by amadav** [comment]
Possibly related to - https://github.com/noah-nuebling/mac-mouse-fix/issues/479

**Comment by noah-nuebling** [comment]
Hey there, thanksf or reaching out! This feature is back in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). Let me know if you have more questions.
