### ISSUE TITLE
Add app specific side button settings [enhancement]

### ISSUE THREAD

**Issue by stevenguh** [noah-nuebling/mac-mouse-fix#59]
## Description
Add the same side button config dropdown in the app specific menu.

## Rationale
Currently, the back and forward mouse button doesn't work with Microsoft RDP when Mac Mouse Fix is on and the side button option is set to Back and Forward.

To get around this, either set the side buttons to Side buttons globally when using RDP or turn off Mac Mouse Fix entirely.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey there Steven, thank you for your feedback!

If I get around to working on a big update for Mac Mouse Fix in the future, the first thing I'd like to do is include a more advanced remapping engine, which let's you remap your buttons however you want in an easy way.

That would make app specific settings for just the side buttons obsolete, so I don't plan on working on this. 

However, I will note this as an example for why app specific overrides for buttons are very important and it got me thinking about how to implement them.

**Comment by stevenguh** [comment]
Thank you for putting this on your radar :)
