### ISSUE TITLE
Hope to add more functions to the button click [enhancement]

### ISSUE THREAD

**Issue by gee1k** [noah-nuebling/Mac-Mouse-Fix#591]
## Description
There are too few functions available in the existing button click, and many of them are put into click and drag. Can you add Launchpad, Mission Control, and exposé to the click options?

Will the other buttons on the Logitech MX Master 3s be supported? It has more than two extension buttons

## Rationale
I could never get used to the tap-and-drag and tap-and-scroll methods and felt awkward using them. So I just want to use the click method

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey there, thanks for reaching out!

Those click actions you requested are available in MMF 3.0.0. Let me know if you have more questions or ideas!
