### ISSUE TITLE
cursor drifts [other]

### ISSUE THREAD

**Issue by huanghh66** [noah-nuebling/Mac-Mouse-Fix#593]
Sometimes the cursor drifts when moving the mouse

**Comment by noah-nuebling** [comment]
Hi there @huanghh66, thanks for reaching out!

Mac Mouse Fix doesn't affect how the cursor works currently, so I assume this must be a hardware issue.

If you do think this should be addressed in MMF, please open a new issue and let me know why you think it should be addressed in MMF. Thank you.
