### ISSUE TITLE
Random Freeze of Mac Mouse 3.0.0 Beta 6 [bug]

### ISSUE THREAD

**Issue by pkb351** [noah-nuebling/Mac-Mouse-Fix#595]
## Description

After using Mac Mouse 3.0.0 Beta 6 for a while the cursor will freeze. I have to been able to determine what the cause of the freeze is.  The mouse freezes at random intervals.

## Steps to reproduce

1. Boot up the computer.
2. Launch any program.
3. Use Mac Mouse Fix and eventually the pointer will freeze.

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: Ventura 13.4 (M1 chip)
Mouse Model: Logitech M-U0007 (5 button corded usb)

## Additional Comments

If I unplug and replug the usb connection Mac Mouse will unfreeze and function normally until the next freeze.  I suspect that the longer I use the computer, the more likely Mac Mouse will freeze.  This is simply a hunch/ guess as to what may trigger a freeze.

---

### Console Logs

–

### Crash Reports

–

**Comment by imraan-go** [comment]
+1, facing the same issue for the last few days. Scrolling stops working for a 5-10 secs and then starts working again.

**Comment by noah-nuebling** [comment]
Does the pointer freeze happen specifically when you use the "Click and Drag" for "Scroll & Navigate" feature? That's the only time that MMF should be interfering with the pointer movements at all.

**Comment by noah-nuebling** [comment]
Also this never happens for me, so if you guys have any other ideas what might be causing this or what might be similar between your guys' setups, please let me know. Thanks!

**Comment by noah-nuebling** [comment]
Hey guys, I'll close this now assuming that the issues didn't stem from Mac Mouse Fix. If you still would like to see this addressed, please open a new issue and link this one. Thanks.
