### ISSUE TITLE
Scrolling not working after user switch - Necessity to disable and reenable mac mouse fix - macOS 12 Monterey [bug]

### ISSUE THREAD

**Issue by man00ka** [noah-nuebling/Mac-Mouse-Fix#596]
## Description

When switching between Users I need to open mac mouse fix and hit the checkbox for enabling/disabling to make scrolling work again. This does not seem to happen when switching to a different user for the first time but only when switching back and forth between already logged in users. 

It also seems like it only happens when enabling mac mouse fix for the other user; so when I switch back to user A where scrolling worked prior switching to user B and I do not do the disable/reenable, scrolling still works for user B. Only when I do the disable/reeneble for user A scrolling for user B won't work.. and vice versa. 

So it seems like mac mouse fix can only be enabled for one user at a time?

kind regards!

## Steps to reproduce

1. Start and enable mac mouse fix for user A
2. Switch to user B
3. Start and enable mac mouse fix for user B
4. Switch back to user A
→ Result: Scrolling for user A not working.

> [!NOTE] Note
> Step 2: Sometimes scrolling already works for user B and I don't need to enable mac mouse fix. However, switching back and forth one more time seems to provoke scrolling not to work for user B.

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: macOS 12.6.6 (21G646)
Mouse Model: Logitech M-100 (M/N: M-U0026)

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.
