### ISSUE TITLE
Аpp exclusion feature!!! [other]

### ISSUE THREAD

**Issue by kostazzz** [noah-nuebling/Mac-Mouse-Fix#597]
Damn, why can't the app exclusion feature be added! Adobe Illustrator cannot be configured. INFURIATING!

**Comment by noah-nuebling** [comment]
Hey there I'm sorry about the troubles. Mac Mouse Fix 2 has an exclusion feature, or maybe you'll find toggling off scroll enhancements from the menubar in Mac Mouse Fix 3 sufficient. You might also find different scroll settings that will work better with Illustrator. At some point I want to add more in-depth app-specific settings but probably won't be able to release that any time soon. I hope that helps a little.
