### ISSUE TITLE
1.0.0 Release does not run on macOS 10.15 [bug]

### ISSUE THREAD

**Issue by DrJume** [noah-nuebling/mac-mouse-fix#60]
## Description

Just downloaded the new release. Unzipped it, and tried to run it. But the app is not supported on non macOS 11 systems.

![image](https://user-images.githubusercontent.com/12785972/109521202-593c7f80-7aad-11eb-8c49-45c880fd0b33.png)

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 1.0.0
macOS Version: 10.15.7
Mouse Model: –

**Comment by DrJume** [comment]
Did not realize there is an extra bug report tool. I clicked on the link in the release it it did not show me the Issue templates (links to external tools).

**Comment by noah-nuebling** [comment]
Ohh whoops! I'm on it. Thank you for your feedback!

**Comment by noah-nuebling** [comment]
Does this work for you?

[MacMouseFixApp.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/6063116/MacMouseFixApp.zip)

Xcode seems to have set the build target from macOS 10.11 to 11 at some point and I didn't notice. It should work under this version though

**Comment by DrJume** [comment]
Yes, it works! 

Thank you so much for maintaining mac-mouse-fix. I love the macOS app ecosystem because apps like yours exist.

**Comment by noah-nuebling** [comment]
Thank you that's nice to hear! And thanks for providing feedback quickly, it's great that I got made aware of the issue right after the release.
