### ISSUE TITLE
Mouse scroll doesn't work while logged in in 2 macOS accounts [bug]

### ISSUE THREAD

**Issue by awesem-szymon** [noah-nuebling/Mac-Mouse-Fix#600]
## Description

Hi,
I love your app. However, I have an issue, if I'm logged in on both macOS accounts (switching accounts), my Evoluent mouse scroll doesn't work.

## Steps to reproduce

1. Log in to one macOS account
2. Switch user to another account without logging in from the 1st account
3. Try using scroll on your mouse

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 13.4 (22F66)
Mouse Model: Evoluent VMDS Vertical Mouse D Small

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by thenktor** [comment]
Same issue here. When two users are logged in the scroll wheel repeatedly stops working when switching between the two accounts.
I'm fixing this by opening Mac Mouse Fix and toggling the "Enable Mac Mouse Fix" checkbox twice. 

Mac Mouse Fix Version: 2.2.3 (7603)
macOS Version: 13.4.1
Mouse Model: Logitech M590

**Comment by Pogimon3** [comment]
Same issue with me and I have been toggling enable mouse fix every time I switch user accounts

**Comment by ghost** [comment]
please fix this!

**Comment by Vikingama** [comment]
same with 3.0.0 Beta 5 (19739)

**Comment by noah-nuebling** [comment]
Hey guys, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.
