### ISSUE TITLE
Please add customization to the horizontal scroll that some mice have [enhancement]

### ISSUE THREAD

**Issue by horstck12** [noah-nuebling/Mac-Mouse-Fix#603]
## Description
Some mice have and additional scroll wheel for horizontal scrolling. It would be nice to be able to configure it as volume control, brightness control, or even for normal scrolling

## Rationale
After working so many hours with so many scrolling, sometimes it hurts the arm to scroll using the middle finger.

Some mice have a scroll wheel for the thumb, it would be nice to use this side scroll as a normal scroll for when the arm is tired 

## Additional info
Thanks for your time

**Comment by kanshurichard** [comment]
+1

**Comment by noah-nuebling** [comment]
Hi guys, thanks for reaching out!

If you would still like to see this addressed, please open a new issue and specify which mouse model you are using. You can link this issue for context so you don't have to write the description and stuff.

Thanks!
