### ISSUE TITLE
How to make the pointer more smooth? [other]

### ISSUE THREAD

**Issue by helloyes3993** [noah-nuebling/Mac-Mouse-Fix#606]
Hi, I was wondering how do I make the pointer more smooth? It's nowhere near as smooth as using the built-in trackpad.

**Comment by noah-nuebling** [comment]
Hey there, thanks for reaching out @helloyes3993! I'm not totally sure what you mean by 'smooth'. If you still want this addressed, please open a new issue and elaborate more on what you would like to see enhanced. Thank you.
