### ISSUE TITLE
Slow mouse wheel scrolling is not reliable/translated correctly [bug]

### ISSUE THREAD

**Issue by DrJume** [noah-nuebling/mac-mouse-fix#61]
## Description

**Side note:**

> I mainly use mac-mouse-fix for using my mouse side buttons to get around quickly and inverting the scroll direction, so I have natural scrolling on a trackpad and regular scrolling with a mouse.
> 
> Because I enjoy macOS' default scrolling behaviour, especially the scroll acceleration (I can't live without it anymore), I leave smooth scrolling disabled. (Now with app specific settings I might give it a try!)

**Problem:**
When scrolling slowly in iTerm2, the scrolling is not translated correctly. 

In these two screen recordings I scrolled _slowly_ then _fast_ and then _slowly_ again.

<details>
  <summary><i>Old:</i> (this is how it should be)</summary>
  
  https://user-images.githubusercontent.com/12785972/109546965-23a68f00-7acb-11eb-8c8a-65336d6babeb.mov
</details>

<details>
  <summary><i>New:</i> (not working correctly 😢 )</summary>
  
  https://user-images.githubusercontent.com/12785972/109547035-3751f580-7acb-11eb-807f-076c27e64f9d.mov
</details>

<br>

<details>
  <summary>Btw, these are my system mouse settings:</summary>
  
  ![macOSMouseSettings](https://user-images.githubusercontent.com/12785972/109547070-40db5d80-7acb-11eb-8b9e-f75f28c0c70e.png)
</details>

## Steps to reproduce

1. Download MacMouseFix 0.9.1 (PrefPane)
2. Scroll slowly in iTerm2

**Result:** Lines are scrolled one by one.

<br>

3. Download MacMouseFix 1.0.0
4. Scroll slowly in iTerm2
 
**Result:** Some scrolling steps are ignored; lines are not scrolled one by one &rarr; no reliable/linear scrolling.

## Context

Mac Mouse Fix Version: 1.0.0
macOS Version: 10.15.7
Mouse Model: Roccat Kone Pure (Polar Blue)

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey Jume thanks for this great feedback! You really know your markdown!

I haven't tested this but I think it might be due to 1.0.0 not scrolling quite as far from single mouse ticks compared to 0.9.1 by default. 
I just played around with iTerm on my MacBook and it seems to swallow small scrolls when using a trackpad, too.

Can you get similar behaviour between the versions by adjusting the Scrolling Speed sliders?

Does the scrolling seem fine for your if you turn smooth scrolling off for iTerm?

I'll look into this more soon.

**Comment by noah-nuebling** [comment]
Oh sorry I was very tired yesterday, and somehow missed that your problem wasn't with smooth scrolling. I'm looking into into it now

**Comment by therain7** [comment]
I have similar issue. Enabling app (without smooth scrolling) makes usual scrolling slower.

**Comment by noah-nuebling** [comment]
Does this work for you guys? 

[1.0.1 Beta 1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/1.0.1-Beta-1)

**Comment by therain7** [comment]
@noah-nuebling fixed the issue for me, it seems. Mac mouse fix doesn't seem to affect usual scrolling anymore. Thanks)

**Comment by noah-nuebling** [comment]
Awesome! If you're having any other troubles with it let me know, I worry that the change I made might cause Scrolling to stop working entirely sometimes but I'm not sure.

**Comment by noah-nuebling** [comment]
The fix seems to work fine, and I assume I'll hear about it if it does turn out to cause issues, so I'm closing this now

**Comment by DrJume** [comment]
Sorry for answering so late!
It works fine again for me. Thank you!

P.S. btw, you can write #61 anywhere in GitHub and commit messages and it will automatically link to an issue. (noticed you manually linked it in the release notes of 1.0.1 Beta 1)

**Comment by noah-nuebling** [comment]
No worries at all! It takes me months :'D and thanks for the heads up! :)
