### ISSUE TITLE
Mouse randomly slows down [bug]

### ISSUE THREAD

**Issue by voltangle** [noah-nuebling/Mac-Mouse-Fix#617]
## Description

When I use this app (btw it's great), sometimes I start experiencing an interesting behavior of the mouse, when it randomly slows down for a split second and then continues going. Idk why it does that

## Steps to reproduce

1. Enable Mac Mouse Fix
2. Use it
3. See the mouse slow down for no apparent reason

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 13.4
Mouse Model: Eternico MV200 (a generic 5 button mouse)

## Additional Comments

–

---

### Console Logs

https://pastebin.com/1p9xvHG9

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there, Mac Mouse Fix shouldn't affect the mouse pointer movement at all wxcept while using Click and Drag gestures.

I'm not aware of any code that could be causing this. 

I only took a short look at the console logs you shared and couldn't see antything relevant. If you think I should take a longer look, let me know.

I'm closing this now, assuming that these issues are unrelated to MMF. If you do think this should be addressed in MMF, please open a new issue and let me know why you think this should be addressed in MMF. Thanks.
