### ISSUE TITLE
Does not work with multiple Users

### ISSUE THREAD

**Issue by daletman** [noah-nuebling/Mac-Mouse-Fix#622]
## Description

Scrolling doesn't work when two users are logged in and both use the app

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 12.6.7 (21G651)
Mouse Model: Logitech MX Master 2S

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by Pogimon3** [comment]
Same issue here. Temporary fix while this gets addressed in the code: You can disable mac mouse fix and re-enable it every time you switch user account to make it work.

**Comment by daletman** [comment]
> Same issue here. Temporary fix while this gets addressed in the code: You can disable mac mouse fix and re-enable it every time you switch user account to make it work.

Didn't work when I tried it

**Comment by thenktor** [comment]
duplicate of #600

**Comment by noah-nuebling** [comment]
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.
