### ISSUE TITLE
Scroll stops working when switching user account [bug]

### ISSUE THREAD

**Issue by Pogimon3** [noah-nuebling/Mac-Mouse-Fix#624]
## Description

Every time I switch users on my mac, macmousefix stops working. I need to disable it and re-enable it to make my mouse scroll working again

## Steps to reproduce

1. Lock the mac
2. Switch user account

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Sonoma Developer Beta 3
Mouse Model: Logitech M650

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by muzzakus** [comment]
This is the only issue stopping me from using and recommending this. No go on a family Mac.

**Comment by thenktor** [comment]
duplicate of #600

**Comment by ghost** [comment]
even happens on latest beta build for Mac mouse fix

**Comment by noah-nuebling** [comment]
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.
