### ISSUE TITLE
Support for DPI Button [enhancement]

### ISSUE THREAD

**Issue by abegehr** [noah-nuebling/Mac-Mouse-Fix#627]
## Description
I have a cheap ISY IMW-502 mouse that has an DPI button on top which I would like to re-program to open mission control. Mac Mouse Fix works great for the scroll wheel button but doesn't seem to recognise clicks on the DPI button.

## Rationale
I would like to see Mac Mouse Fix support reprogramming the DPI button on my mouse.

## Additional info
–

**Comment by abegehr** [comment]
Researching this a bit more, it seems that the DPI key is mouse-internal and events are not sent to the computer. If this is the case, no luck in reprogramming SW-side.

**Comment by noah-nuebling** [comment]
Hey there @abegehr, thanks for your feedback. 

I think it probably depends on the mouse model whether it's theoretically possible to reprogram the DPI button. Where did you read that the DPI key is mouse internal?
