### ISSUE TITLE
Side scroll with MX masters [enhancement]

### ISSUE THREAD

**Issue by puzzledyk** [noah-nuebling/Mac-Mouse-Fix#628]
## Description
As we all know this tool is superior to Logitech own tools. Its perfect in every way, but i cant use side scroll wheel without logi options software - which breaks MMF.

## Rationale
If you could catch the input from the side scroll wheel then it would work as expected. Right now the side scroll wheel is not doing anything as the mac cant understand it i guess. This change would improve this mouse so much, and it would be the standard software to make the mouse work as expected. 

## Additional info

**Comment by noah-nuebling** [comment]
Hi there! This should be fixed in the latest release. Let me know if you have more suggestions or questions.
