### ISSUE TITLE
滚动与导航功能 [enhancement]

### ISSUE THREAD

**Issue by 645916017** [noah-nuebling/Mac-Mouse-Fix#629]
## Description
希望的滚动与导航能够加入方向反向控制，目前的方向感是反的。

## Rationale
例如试用无边记 ipad上控制内容的位置可以用手之际触摸屏幕拖拽，mac上就只能用滚轮和键盘协同步。滚动与导航功能正好模拟了ipad的触摸，但是目前方向是反的。

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi there, thanks for reaching out! This should be resolved in the latest release. Let me know if you have more questions.
