### ISSUE TITLE
v2 & v3 broken on Ventura OCLP [bug]

### ISSUE THREAD

**Issue by wander3** [noah-nuebling/Mac-Mouse-Fix#634]
## Description

Checking the box for smooth scrolling does nothing after granting accessibility permissions. Alternative app Mos does work. OCLP 0.6.8 on MBP11,2

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 13.5
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there @wander3, I think this might have been resolved in a recent release. If you would still like to see this adressed, please open a new issue and link this one. Thank you.
