### ISSUE TITLE
MacMouseFix crashes with TripleTap-MiddleClick apps [bug]

### ISSUE THREAD

**Issue by khesed** [noah-nuebling/Mac-Mouse-Fix#641]
## Description

Apps that add the feature to tap with 3 fingers on trackpad to middle click cause MacMouseFix to crash. If you cannot fix the crashing with the other apps, please consider adding this feature to your app.

Thank you.

## Steps to reproduce

1. Download and launch Three-Touch MiddleClick for the ability to middle-click with a trackpad: https://github.com/artginzburg/MiddleClick-Ventura/issues

2. Tap with three fingers

3. MacMouseFix crashes on Beta 5 and Beta 6

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: Ventura 13

**Comment by noah-nuebling** [comment]
Hey Jeremia, thanks for reaching out! I fixed the bug in this commit: 0e60c71df6dd3af69957376b765946076a18a911

Not sure when I'll be able to release the fix though, sorry.
