### ISSUE TITLE
ARC browser: scrolling is chunky and really unsatisfying [bug]

### ISSUE THREAD

**Issue by neel04** [noah-nuebling/Mac-Mouse-Fix#643]
## Description

On VSCode, as well as iTerm and other apps the scroll works perfectly. But on ARC, it seems that each discrete scroll wheel tick is counted and the experience in NOT smooth at all.

Tested in Firefox, and can confirm it works amazing as well. Its weird that its not working in ARC. I'm not sure what this "Feedback Assistant" page is, but I suspect its using a browser too because the scroll here is also very jank.

Please fix. This is a really annoying issue for me.

## Steps to reproduce

1. Download ARC
2. Scroll a webpage
3. Cry.

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 13.5.1 (22G90)
Mouse Model: Microsoft (bluetooth) ergonomic mouse

## Additional Comments

Please update on progress. For now, I'll hunt for a different application....

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there @neel04, thanks for the feedback!

Wow Arc is super polished! I just tested it and scrolling seems to work perfectly with the lastest Mac Mouse Fix 3.0.1.

I'll close this now, if you still experience issues, let me know and I'll look into it.
