### ISSUE TITLE
Disabling and re-enabling MMF slows mouse [bug]

### ISSUE THREAD

**Issue by Th3o4oR** [noah-nuebling/Mac-Mouse-Fix#645]
## Description

When disabling MMF my tracking speed reduced noticeably, and didn't increase again even after re-enabling MMF. I had to unplug the dongle for my mouse and reinsert for it to go back to normal. 

The mouse has both dongle and Bluetooth: same issue happens with Bluetooth, and is also fixed by disconnecting and reconnecting.

## Steps to reproduce

Disable MMF: mouse tracking speed should slow noticeably.
Re-enable MMF: mouse stays slow.

To fix:
If Bluetooth: disconnect and reconnect. 
If USB: unplug and reinsert. 

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: Sonoma 14.0
Mouse Model: Logitech MX Master 3S

**Comment by noah-nuebling** [comment]
Hi there @Th3o4oR, thanks for your feedback. 

I'll close this now, assuming it's been resolved. Please open a new Issue if this problem still occurs. Thank you.
