### ISSUE TITLE
`Control + Down` is missing in Space & Misson Control [bug]

### ISSUE THREAD

**Issue by BingoKingo** [noah-nuebling/Mac-Mouse-Fix#647]
Thanks for making such awesome app.
All of `Control + Up`, `Control + Left`, `Control + Right` replacement is handy for me. But the function of `Control + Down` to show current focused app windows is missing in *Space & Misson Control* on 3.0 Beta 6.
Could you done it for us?

**Comment by noah-nuebling** [comment]
This is implemented in MMF, but it only works if the swipe down with 3 / 4 fingers for App Exposé is enabled in the Trackpad settings.

If you need more info let me know.

**Comment by BingoKingo** [comment]
Hi, is it possible to enable it without a real Magic Trackpad? Or execute what from `defaults write` command?

**Comment by noah-nuebling** [comment]
Yes, try this Terminal command:

```
defaults write com.apple.Dock showAppExposeGestureEnabled -bool TRUE; killall Dock
```

MMF should probably do this automatically, or at least offer to do it for you, or at least there should be a guide documenting this method.

**Comment by BingoKingo** [comment]
Thanks for your reply, but my control+left and control+right is missing as well, could you give me a tip?
Maybe you could add a guide in README for users who want to manually enable these features :)

**Comment by noah-nuebling** [comment]
Hey there, I definitely agree there should be a guide at least. 

On my side the "Click and Drag" for "Mission Control & Spaces" feature always allows you to move between Spaces, regardless of the trackpad settings. 

Maybe you don't have have more than one space opened? That's the only thing I can think of right now.

**Comment by BingoKingo** [comment]
After reset my mouse setting in driver software, it works. Thank you. Btw, I'd like to suggest using Paddle or Alipay for payment in China.

**Comment by kekexiaoai** [comment]
> Yes, try this Terminal command:
> 
> ```
> defaults write com.apple.Dock showAppExposeGestureEnabled -bool TRUE; killall Dock
> ```
> 
> MMF should probably do this automatically, or at least offer to do it for you, or at least there should be a guide documenting this method.

thanks， it works
