### ISSUE TITLE
Smooth scrolling not working [bug]

### ISSUE THREAD

**Issue by avocadoattack** [noah-nuebling/mac-mouse-fix#65]
## Description

I've been using Mac Mouse Fix for a while as the Pref Pane extension and everyitng worked except the Smooth Scrolling feature. I have now downloaded from Git the official app version, and it still does not work. Any help would be appreciated! Also, can this app interfere with Better Touch Tool?

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 1.0.1
macOS Version: macOS Big Sur 11.2.2
Mouse Model: Logitech Vertical Ergo

## Additional Comments

The version of the Pref Pane extension is 0.9.1. (243)

---

### Console Logs

–

### Crash Reports

Looked but none existed

**Comment by noah-nuebling** [comment]
Hey there @lucsan111, thanks for your feedback! 

I can think of two possible kinds of reasons behind your problem:
- BetterTouchTool or some other software could be interfering with Mac Mouse Fix, as you also speculated
- Your Mouse might be sending non-standard scroll events which Mac Mouse Fix doesn’t pick up on

It’s hard to diagnose this from afar, and I don’t want to promise anything, but if you or someone with a similar problem could give me some more information on the issue, that could help diagnose it. Here are some ideas for information that might help pin down the problem:

- Elaborate on how exactly smooth scrolling fails. Does it not scroll at all when it’s enabled, or does it not change the scrolling behavior, or something else entirely?
- Find Console Logs occurring while scrolling with smooth scrolling enabled, and post them here
- Check if smooth scrolling works on your system when using another mouse
- Check if smooth scrolling works when using your mouse with Mac Mouse Fix on another system

Again, I have no real idea what might be causing this, so please don’t hold your breath for a fix. But if you do find out anything else, I’ll be sure to look into it when I have time. Thanks for your contribution!

**Comment by noah-nuebling** [comment]
Hey there! I'm closing this now assuming it's not an issue anymore. Let me know it it's still a problem for you.
