### ISSUE TITLE
An Thien [enhancement]

### ISSUE THREAD

**Issue by ghost** [noah-nuebling/Mac-Mouse-Fix#652]
## Description
Upgrade for button section

## Rationale
I think you need to update more for the button section, because this part is too missing for some types of mouse with many buttons

## Additional info
Please consider this idea, I think it's really necessary. Please consider this idea, I think it's really necessary. In addition, I can't use your app at the same time as Logitech Options  , which makes me unable to use multi -button and use smooth scrolls at the same time.

**Comment by noah-nuebling** [comment]
Hey there, thanks for reaching out. Mac Mouse Fix does support multiple buttons. Try using the '+' button, or the '+' field if you're on the Mac Mouse Fix 3.0.0 Beta. I hope that helps. If you have more questions, please open a new issue. Thank you.
