### ISSUE TITLE
Click and Drag Action for Space and Missions Direction is inverted [bug]

### ISSUE THREAD

**Issue by woody1122001** [noah-nuebling/Mac-Mouse-Fix#654]
## Description

Click and Drag Action for Space and Missions Direction is inverted compared to v2. Would be great to revert back or add a customisation on the space direction

## Steps to reproduce

1. Set any buttons to Click and Drag
2. Switch between different Spaces with the action

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: Ventura
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by fnschmidt** [comment]
I believe this is a bug. You can fix it (permanently) by toggling "natural scrolling" twice inside the System Settings

**Comment by noah-nuebling** [comment]
Hey there! @greybaron is correct. See [this answer](https://github.com/noah-nuebling/mac-mouse-fix/issues/541#issuecomment-1701556131) for more details.

**Comment by noah-nuebling** [comment]
Hey guys, the drag direction should be fixed in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). If you have more questions let me know.
