### ISSUE TITLE
Support of click and drag with reversed direction [enhancement]

### ISSUE THREAD

**Issue by HoweChen** [noah-nuebling/Mac-Mouse-Fix#661]
## Description
Hi, this is a letter from the huge fan of the app. 

I just wanna say thank you for your efforts and work! I am totally fine with current features, but just a little suggestion, can we make click and drag support reversed direction option on the beta version? Right now I am using beta 6 version, I found there is beta version which is better then the release, but that drag direction thing is different from what I am used to.

## Rationale
Because sometimes the drag direction are different based on user's habit.

Say some one is used to the apple's natural direction(like me), and some one is used to Windows direction setting.

## Additional info
–

**Comment by davidisaaclee** [comment]
Adding to this request: On my Macbook, I switch between built-in trackpad and a trackball. I want the trackpad to use natural scrolling, and – when scrolling – I want to treat the trackball like a classic mouse wheel. I can't have both of these if the trackpad shares scroll direction with click hold. (I think this is the same issue, although maybe there's a simpler config in here than "natural scrolling (i.e. invert scroll)" + an additional invert scroll.)

**Comment by noah-nuebling** [comment]
Hi guys, thanks so much for your feedback and the kind words! The click and drag direction should be correctly matching the trackpad swipe direction in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). If you still want a separate option for changing the click and drag direction please open a new issue. Sorry for the hassle and thanks.
