### ISSUE TITLE
Program functions are not activated [bug]

### ISSUE THREAD

**Issue by illmano** [noah-nuebling/Mac-Mouse-Fix#663]
## Description

After starting the program, I try to enable its functions, but nothing happens. https://share.cleanshot.com/bFl2nzv4

## Steps to reproduce

1. I launch the program
2. I'm trying to enable functions (move the toggle switch)

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 13.5.2 (22G91)
Mouse Model: mi dual mode wireless mouse silent edition

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Does the following help:

1. Find any other copies of MMF on your computer. Move them all to the bin. 
2. Empty the bin
3. Restart your computer
4. Try enabling MMF again

**Comment by illmano** [comment]
Thank you! It worked.

**Comment by noah-nuebling** [comment]
Glad it worked! Thanks for getting back. I'm reopening the issue so other people with the same issue can see this.

**Comment by noah-nuebling** [comment]
Hey guys,

I'll close this issue now to move all the conversion around the problem to #648.
