### ISSUE TITLE
Accessibility Option not asked [bug]

### ISSUE THREAD

**Issue by LordAmit** [noah-nuebling/mac-mouse-fix#67]
## Description

Hi!

Thanks for creating this awesome software! I used to use the prefpane version of this software, and today upgraded to the app version.

However, things did not seem to work even after removing the prefpane version and starting the app, and checking the `Enable Mac Mouse Fix`. I also changed the settings (i.e., enable and disable inverted direction, swap side buttons, changing the Click action for middle mouse button, etc). So I restarted the machine.

After restarting, it still did not work - so I unchecked and checked `Enable Mac Mouse Fix`, and only after that it said that I need to give access to accessibility.

I understand that this is a weird bug, and might be hard to reproduce; but it might be a good idea to check whether the app has accessibility privilege when trying to run it. Or maybe talk about this step a bit more in the Home page.

Once again, thank you for this amazing software!

## Steps to reproduce

– N/A

## Context

Mac Mouse Fix Version: 1.0.1
macOS Version: 11.2.3
Mouse Model: SteelSeries Rival 110

## Additional Comments

– N/A

---

### Console Logs

– N/A

### Crash Reports

– N/A

**Comment by noah-nuebling** [comment]
Hey there @LordAmit, thanks for taking the time to write a bug report, and for letting me know your like the software :)

I'm not sure how to fix this problem, but I'll definitely keep it in mind and I'll spend some time trying to figure it out soon.

**Comment by noah-nuebling** [comment]
I think I figured it out and this should be fixed in version 1.0.3 and later. Thanks again for he heads up!

**Comment by antoniomcr96** [comment]
@noah-nuebling I tried this method and it doesn't work. I had the prefpane and I removed, then I installed the app. It doesn't ask for accessibility permission so it doesn't work. Reinstalling the panel does not work, too. So, basically, I'm without the service

**Comment by LordAmit** [comment]
Glad to know! Thanks for making this awesome software!
