### ISSUE TITLE
New macOS Sonoma 14.0 RC broke the scroll [bug]

### ISSUE THREAD

**Issue by olivergiangvu** [noah-nuebling/Mac-Mouse-Fix#670]
## Description

No more scrolling on new Sonoma update. Disable the Scrolling option and the mouse can scroll again

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: Sonoma 14.0 Beta RC
Mouse Model: Logitech G502X

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by Maxxxxyu** [comment]
Same problem for MacOS 13.6

**Comment by shpirt** [comment]
Same here. I re-enabled it and the problem was resolved. I tried to reproduce the issue but was unsuccessful.

**Comment by teal024** [comment]
same here for MacOS 13.5.1, has to re-enable it to get it work for many times

**Comment by teal024** [comment]
> same here for MacOS 13.5.1, has to re-enable it to get it work for many times

Update: after updating to 14.0 sonoma, the feature of using cmd + scroll to zoom gets stuck from time to time;

**Comment by noah-nuebling** [comment]
Hey guys thanks for the feedback. I'll assume this was fixed in a later Sonoma release. If you still have troubles please open a new issue. Thank you.

**Comment by ggogel** [comment]
@noah-nuebling 
Hello, I'm facing this issue every day. It didn't appear right after the update to Sonoma, though. Every morning, the scrolling behaves weirdly. When I'm scrolling in one direction, it scrolls alternately up and down. I have to toggle "Enable Mac Mouse Fix" several times to fix it. Then it works again for hours without any problems.

It first started with version 2.2.3. Then I upgraded to 3.0.1 but it didn't improve.
