### ISSUE TITLE
Keyboard modifiers affect scrolling and other apps when scrolling is OFF [bug]

### ISSUE THREAD

**Issue by HVR88** [noah-nuebling/Mac-Mouse-Fix#679]
## Description

Mac Mouse Fix interferes with the scrolling of other mouse apps using modifier keys even when its own scroll feature is disabled.

## Steps to reproduce

Even when the scrolling feature is disabled, Mac Mouse Fix causes other mouse apps like Mos to behave oddly when modifiers are held down, such as Cmd.

1. Install and configure Mos to perform super fast scrolling when CMD is held
2. Test that Mos is working as expected and CMD dramatically increases scrolling rate by scrolling a long web page in Safari or Firefox
3. Install and configure Mac Mouse Fix by turning OFF its scroll support
4. Test the CMD key to scroll again on the same long web page - scrolling speed is slow

## Context

Mac Mouse Fix Version: 2.2.3
macOS Version: 14
Mouse Model: Pulsar XLite v2

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there, thanks for reaching out!

Does this still happen under Mac Mouse Fix 3?

I plan to keep supporting MMF 2, but this is probably a more deep rooted issue that would need some architectural changes in MMF to Fix. So I'm closing this now. If this still happens under MMF 3, please open a new issue. Thank you.
