### ISSUE TITLE
Invert scrolling always re-enables [bug]

### ISSUE THREAD

**Issue by airjohnpro** [noah-nuebling/mac-mouse-fix#68]
## Description

Invert scrolling gets checked (enabled) every time the app is launched. It should keep its last set state. 

## Steps to reproduce

Uncheck invert scrolling
Close the app
Open the app
Invert scrolling gets checked automatically 

## Context

Mac Mouse Fix Version: 1.0.1
macOS Version: 11.2.3
Mouse Model: Logitech M590, Microsoft Ergonomic Bluetooth

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey @jwiskowski thanks for the heads up! I'm on it.

**Comment by noah-nuebling** [comment]
I just published an [update which fixes your issue](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/1.0.2). I hope that works for you! Let me know if you have any more troubles.

**Comment by airjohnpro** [comment]
Launched the app, it detected the new version and installed. Invert direction remained un-checked. Issue resolved. Thank you!

**Comment by noah-nuebling** [comment]
Awesome, you're welcome! :)
