### ISSUE TITLE
Click & Drag gestures are reversed [enhancement]

### ISSUE THREAD

**Issue by philippedcote** [noah-nuebling/Mac-Mouse-Fix#680]
## Description
Would it be possible to add a checkbox to reverse the direction of all Trackpad simulaition gestures please? It would feel more natural. Thanks!

## Rationale
The gesture is currently reversed from the intended behavior. On the trackpad, you have to move your fingers to the left to access the space located to the right. The trackpad simulation should have an option to reverse this logic.

## Additional info
Using version 3.0.0 Beta 6.

**Comment by noah-nuebling** [comment]
Hi, thanks for your feedback! The drag direction should be fixed in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). If you have any more questions let me know.

**Comment by abjugard** [comment]
@noah-nuebling So... could you implement a checkbox to un-reverse the drag direction? 😅
