### ISSUE TITLE
When restarting my mac, Mac Mouse Fix has to be re-enabled. [bug]

### ISSUE THREAD

**Issue by wjwyatt** [noah-nuebling/Mac-Mouse-Fix#681]
## Description

When restarting my mac, Mac Mouse Fix has to be re-enabled.

## Steps to reproduce

1. Restart mac
2. Notice that the mouse behavior changes
3. Open Mac Mouse Fix - notice that it is not enabled

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 14
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there @wjwyatt, sorry for the late reply. I'll close this now since I answered in #700.
