### ISSUE TITLE
bug: when I login to other account gestures does not work [other]

### ISSUE THREAD

**Issue by suredanish** [noah-nuebling/Mac-Mouse-Fix#686]
when I login to other account gestures does not work, even scrolling does not work.
I disable and enable Mac Mouse Fix. Then every thing works fine.

**Comment by thenktor** [comment]
Duplicate of #600

**Comment by noah-nuebling** [comment]
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.
