### ISSUE TITLE
Additional Functionality Options for Side Buttons [enhancement]

### ISSUE THREAD

**Issue by dmahidashti** [noah-nuebling/mac-mouse-fix#69]
## Description
Create the option for the side buttons to switch functionality, from moving between spaces to moving between pages (backwards/forward). This can be done if the side buttons can be used along with one of the main buttons. For example, left click back button will allow for moving a space, or moving a page (depending one the specified setting). 

## Rationale
Hi! I love using your app to customize the side buttons on the mouse. I usually set them to allow movement between spaces, but in some instances, I need them to allow for backward/forward movement of pages. This would allow for a complete replacement of a trackpad, since trackpads can be used for moving between spaces or pages based on the number of fingers being used for a gesture. I'm not sure if this is possible within the confines of the app, but I think it would be a nice addition. 

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey there @dmahidashti thanks for your feedback!

I think you'll be quite pleased with the new [2.0.0 Beta 1](https://github.com/noah-nuebling/mac-mouse-fix/releases) version I just released :)

**Comment by dmahidashti** [comment]
Hi Noah,

Thank you so much for the follow up! This feature is just amazing, thank you for the wonderful app!

Have a great weekend!

Best,
Daniel

**Comment by noah-nuebling** [comment]
Aw thanks, I hope you have a great week! :)
