### ISSUE TITLE
How do I navigate a Figma file? [other]

### ISSUE THREAD

**Issue by him229** [noah-nuebling/Mac-Mouse-Fix#691]
Largely, how do I enable horizontal scroll?

**Comment by noah-nuebling** [comment]
Hi there @him229, thanks for reaching out, and sorry for the late reply.

By default, you can scroll horizontally by holding Shift on your keyboard or by using the Click and Drag to 'Scroll & Navigate' gesture. 

If this doesn't work, I assume that there's another mouse app that's interfering with Mac Mouse Fix, or that your scroll wheel doesn't send standard scroll-wheel events, such that Mac Mouse Fix isn't handling your scroll wheel at all.

Sorry I can't help more right now.

If you have more questions or any leads as to what's going on, please open a new issue with the additional information or questions. Thank you. Maybe just check if there are any other mouse apps installed or if the other scroll settings in MMF have any effect.
