### ISSUE TITLE
Ripped scrolling with minimized/closed window [bug]

### ISSUE THREAD

**Issue by Galder7** [noah-nuebling/Mac-Mouse-Fix#693]
## Description

It's harder to see on video, but on 165hz display is pretty visible and very annoying. Natively is 3 times laggier than on video.

Video 1:
https://drive.google.com/file/d/1cQuFPko4JoXnFcjxGuJHJrm_Uep5M5zR/view?usp=share_link

Video 2:
https://drive.google.com/file/d/1MQKxHpkYzus_MvCqXslBk8-FDuJvkyd3/view?usp=share_link

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0 Beta 6
macOS Version: 14.0
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey there @Galder7, thanks for reaching out! If this is still happening, please open a new issue saying that it's still happening and just link this issue for context. Thank you.

I'm closing this now, assuming it was an issue in macOS, that has since been resolved.
