### ISSUE TITLE
Fast scroll shortcut (key + mouse scroll)  [enhancement]

### ISSUE THREAD

**Issue by mizzke** [noah-nuebling/Mac-Mouse-Fix#697]
## Description
Hello, 

I'm missing feature that if I want to scroll faster through document lets say or browser I can't do it right now. In browser for example I can't use scroll button to activate fast scroll because it is used by MacMouseFix for mission control (in my case). 

So if there is an option for lets say Option/Control key + scroll for faster scrolling that would solve big problem for me, and I hope so for many other users. 

## Rationale
I would like to see this enhancement because it will speed up my workflow. 

I think this is the core option for this app to be Number 1 app for this kind of purpose (with all other current possible features). 

## Additional info
–

**Comment by 20015jjw** [comment]
Try the beta. It has exactly what you need and a lot more!

**Comment by noah-nuebling** [comment]
Here there thanks for reaching out! This feature is in the latest MMF 3 as @20015jjw mentioned, so I'll close this issue. Let me know if you have more questions or ideas.
