### ISSUE TITLE
Add natural direction option for Spaces and Mission Control [enhancement]

### ISSUE THREAD

**Issue by re1ro** [noah-nuebling/Mac-Mouse-Fix#707]
## Description
When I configure:
`Click and Drag: Spaces and Mission Control` 

Current behavior:
Click and drag to the right: switching to right space
Click and drag to the left: switching to left space

Desired behavior:
Click and drag to the right: switching to left space
Click and drag to the left: switching to right space

## Rationale
Current  click and drag works by switching spaces in the same direction as mouse moves. I think moving through spaces in the opposite direction would make this feature to feel more natural.

I want to switch my spaces by middle clicking and dragging the whole desktop. This will allow the drag and drop feeling of this feature. Imaging the wallpaper to be a canvas in an image editing software and to be able to click and drag the canvas.

## Additional info
<img width="557" alt="Screenshot 2023-11-14 at 6 25 47 PM" src="https://github.com/noah-nuebling/mac-mouse-fix/assets/470292/ef1a3a1d-5d56-4760-9348-a7b9b16a6343">

**Comment by re1ro** [comment]
Related to #661

**Comment by 20015jjw** [comment]
Building on this, I'd love to see finer control over click and drag behavior:
- separate sensitivity (crucial for trackball user)
- direction setting (disable/enable, customized behavior (reverse exposé and mission control potentially, even different vertical / horizontal sensitivity?)
- whether the cursor moves when in click and drag mode is engaged (the trackpad doesn't move the cursor when in 3/4 finger mode)

I love the changes in mac mouse fix 3! The ability to mimic trackpad zoom is amazing for my custom keyboard with a trackball. If the author doesn't think this is timeworthy, I'd love to help build out these finer control settings.

**Comment by 20015jjw** [comment]
> whether the cursor moves when in click and drag mode is engaged (the trackpad doesn't move the cursor when in 3/4 finger mode) 

apparently this is already available. it's under the option menu in the button tab listed as Locked Mouse Pointer During 'Click and Drag' Gestures.

**Comment by noah-nuebling** [comment]
Hey there! The drag direction should be fixed in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7). If you have other probems you want addressed please open new issue for that. Thank you.
