### ISSUE TITLE
Addition of UI images on Website [enhancement]

### ISSUE THREAD

**Issue by wakmail** [noah-nuebling/Mac-Mouse-Fix#715]
## Description
Update the website so it shows the UI of Mac-Mouse-Fix; otherwise, people don't really know what they're getting besides smoother scrolling.

## Rationale
People want to know what the product looks like and what functions it has before they get it. When choosing between Mac Mouse Fix and MOS, I didn't really know what Mac Mouse Fix had to offer besides smoother scrolling.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hey @wakmail, thanks for your feedback! What do you think of the [new website](macmousefix.com)?

**Comment by noah-nuebling** [comment]
I'll close this now. Thanks again for your feedback, if you have more feeback regarding the new website, let me know!
