### ISSUE TITLE
Add option to inverse click and drag spaces [enhancement]

### ISSUE THREAD

**Issue by CamilleScholtz** [noah-nuebling/Mac-Mouse-Fix#718]
## Description

An option to make swiping to the left go to the right space, aka inverse

## Rationale

It feels more natural to me, mimicking the trackpad, an option is always nice

## Additional info

I'm using the beta.

**Comment by noah-nuebling** [comment]
Hi there, thanks for reaching out! This should be fixed in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7), let me know if you have any more troubles.
