### ISSUE TITLE
allow to hide dock icon and make it a menubar app [enhancement]

### ISSUE THREAD

**Issue by Alessandrx204** [noah-nuebling/Mac-Mouse-Fix#721]
## Description
it's annoyng to see this appdisappear whenever i close settings
many other 3rd party mouse enchaser apps are only shown in the menu bar without being obstuctive and easy to reach.

this app is amazing, it does alone what i needed 2 apps for before, and it's much more customizable.
so this feature would make mac mousefix the best mouse fixer app oth there

## Rationale
i' would like to have the mac mouse fix app only in the menu bar, without needing torecall it everytime i need to change a setting

## Additional info
i love this app <3

**Comment by noah-nuebling** [comment]
Hi there @Alessandro15204, if you simply "Enable" the app, you can then close it and it will keep working in the background. Even after you restart your computer!

I tried to make this behaviour more clear in MMF 3 which released around a month ago.

If you have more questions or suggestions, let me know!

**Comment by noah-nuebling** [comment]
I'll close this now, assuming the problem has been resolved under MMF 3.
