### ISSUE TITLE
I want the redundant options back! [enhancement]

### ISSUE THREAD

**Issue by wakmail** [noah-nuebling/Mac-Mouse-Fix#725]
## Description
I'm Complaining
Removed several options from the "Click", "Click and Hold" and "Click and Scroll" Actions because I thought they were redundant since the same functionality can be achieved otherwise and since this cleans up the menus a lot. Will bring those options back if people complain. So if you miss those options - please complain.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi thanks for reaching out! Redundant options are now back in [3.0.0 Beta 7](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.0-Beta-7)
