### ISSUE TITLE
The application crashes if you switch to the "Buttons" or "Scrolling" tab of an inactive window while holding down the Cmd key [bug]

### ISSUE THREAD

**Issue by V-Coba** [noah-nuebling/Mac-Mouse-Fix#735]
## Description

1. Open the MMF window and switch to the "General" or "About" tab
2. Click on the MMF icon in the global menu bar and disable "Buttons" and "Scrolling"
3. Move the focus from the MMF window to something else, such as the Desktop
4. Hold down the Cmd key and click on the "Buttons" or "Scrolling" tab

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0 Beta 7
macOS Version: 14.2 (23C64)
Mouse Model: Logitech G903 Lightspeed

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

https://pastebin.com/ifnUayif

**Comment by noah-nuebling** [comment]
Hey there @V-Coba, interesting find, that's a super weird bug. 

I think there's something wrong in macOS that causes this. When reproducing the bug, `NSApp.mainWindow` is randomly nil and the position of the window seems to be reported wrong, too. 

I fixed the crash but the wrong window position is still causing a bit of weirdness. Will ship in the next update.

Might wanna file a bug report with Apple but I'll probably be too lazy.

Thanks!

**Comment by V-Coba** [comment]
When MMF crashed, a window appeared asking you to send a bug report to Apple and describe the problem. In the field where you need to enter your comment, I wrote the following:

> "This happens in the "Mac Mouse Fix" utility. I described detailed steps to reproduce this bug on the GitHub of this utility: https://github.com/noah-nuebling/mac-mouse-fix/issues/735
> 
> The author of this utility wrote that the problem is probably in macOS itself."

Let's hope Apple will pay attention to this bug report 🙏
