### ISSUE TITLE
I find some bug in your app [bug]

### ISSUE THREAD

**Issue by lotusk08** [noah-nuebling/Mac-Mouse-Fix#745]
## Description

Hi,
I'm Steve; I have some keynote for you:
1. This app doesn't save the purchased code.
2. Active license buttons aren't auto-hidden after the active license key.
[Screenshort](https://www.dropbox.com/scl/fo/t1z9fgpt89tot02vqmqqo/h?rlkey=yg345e588rh7k1aw39wt3g2oz&dl=0)
3. Setting profile can not be reused after updating the newest version.
4. I saw your profile and got your support with the best prices (discount of 40%) in Vietnam.
So, if you need a Vietnamese language version, I can help you to do this and provide your app with some community using macOS in Vietnam.
Thank you for taking the time to create a fantastic app.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: 12.7.2
Mouse Model: Razer Pro Click

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there, thanks for your feedback @lotusk08!

1. If you still experience this problem, please open a new issue. Thank you.
2. This is intended I think. The "Activate License..." lets you see your license key if you ever need to look it up.
3. Future updates, starting with 3.0.1, should keep your settings.
4. Someone already translated the app to Vietnamese. But thanks a lot! You could double check the Vietnamese translations if you want. 

I'll close this issue now. If you still have problems, please open a new issue for each of the problems you'd' like to see adressed. Thank you.
