### ISSUE TITLE
Latest beta 3.0.0 (22033) middle mouse button bug [bug]

### ISSUE THREAD

**Issue by AjianNie** [noah-nuebling/mac-mouse-fix#748]
## Description

In the previous version, the middle mouse button has always been the default Cmd W of the macOS system, which is to close the tab of any software; but in the latest beta 3.0.0.0 (22033), the middle mouse button always fails intermittently - it takes multiple times Press - easy to accidentally press multiple times

## Steps to reproduce

1. beta 3.0.0.0 (22030)
2. Logitech mouse middle button
3. Press the middle button on a software tab such as Safari

## Context

Mac Mouse Fix Version: 3.0.0 (22030)
macOS Version: 13.6
Mouse Model: Logitech mouse M585/M590

## Additional Comments

Maybe it would be a good idea if the middle button could be recognized and customized like the other buttons.

---

### Console Logs

–

### Crash Reports

–

**Comment by LouieMjr** [comment]
Having the same issue with a different mouse. Almost like its barely recognized. It wont even function as a middle click for me anymore since version 3.0.0.0

**Comment by noah-nuebling** [comment]
Hey guys, thanks for reaching out.

This sounds like an issue with your hardware buttons.

Try disabling Mac Mouse Fix and using this website (https://www.onlinemictest.com/mouse-test/) to see if your buttons work correctly.

**Comment by AjianNie** [comment]
> Hey guys, thanks for reaching out.
> 
> This sounds like an issue with your hardware buttons.
> 
> Try disabling Mac Mouse Fix and using this website (https://www.onlinemictest.com/mouse-test/) to see if your buttons work correctly.

Thx, I used this website to test that the mouse works fine. In addition, I closed this issue because I later found the middle button returned to normal, may be related to the multiple restarts of the system.
