### ISSUE TITLE
[bug] MMF overrides native keyboard shortcuts

### ISSUE THREAD

**Issue by Laicure** [noah-nuebling/Mac-Mouse-Fix#749]
## Description

It just overrides my Mac's native keyboard settings. I don't have any other apps like karabiner/logioptions or any keyboard shortcut manager.

## Steps to reproduce

See gif below, note that I'm only using my mouse.
![ss 2023-12-27 at 11 05 55 AM](https://github.com/noah-nuebling/mac-mouse-fix/assets/8619566/9116abf3-fe93-4189-8470-7fcafaeb5032)

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: 13.6.3
Mouse Model: Razer Basilisk Hyperspeed (connected via bluetooth)

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi! Thanks for your feedback.

As long as it restores the keyboard shortcut after a split second, this is expected behaviour. Overriding the keyboard shortcuts in this way is the only way that I know of to programmatically trigger some of these actions such as Mission Control and Launchpad.

**Comment by Laicure** [comment]
I see, thanks for the info! Very nice app, btw 👌

**Comment by noah-nuebling** [comment]
Great, thanks!
