### ISSUE TITLE
Add Trackpad n-finger drag and pinch actions [enhancement]

### ISSUE THREAD

**Issue by DrJume** [noah-nuebling/mac-mouse-fix#75]
## Description
When adding a Click & Drag mapping, have the option for a Trackpad 1/2/3/4-finger drag or an inward/outward pinch as action.

## Rationale
I really like the Mac App [Swish](https://highlyopinionated.co/swish/) which enables a very intuitive window management for power users.

It allows you to move/hide/close/quit windows/applications with Trackpad gestures while the mouse is over a corresponding window or Dock icon.

Sadly it only works with a Trackpad. And I think it's not the only great app limited to this.

## Additional info
–

**Comment by noah-nuebling** [comment]
Swish is really cool, thanks for the heads up! 

As far as I understand swish uses scroll swipes (2 finger swipes) as well as pinch gestures to work.

You can already use pinch gestures with Mac Mouse Fix by holding Control while scrolling. 
However, testing this with Swish it worked a little but not properly.

I also already tried to implement scroll-swipes in Mac Mouse Fix, too, but scroll swipes are very complex and I haven't quite reverse engineered the way they work, yet, I've also some other troubles implementing them in a great way so I decided to focus on building the remapping engine first.

I definitely want to work on those features more at some point in the future though, and I'll keep an eye on Swish and try to support it well.

**Comment by noah-nuebling** [comment]
Hey @DrJume, pleased to inform you that 2-finger-swipe simulation is a feature in the latest [MMF 3 Beta](https://github.com/noah-nuebling/mac-mouse-fix/releases) and it works great with Swish!

**Comment by DrJume** [comment]
That's awesome! Thank you so much! I will give it a try 😊
