### ISSUE TITLE
Can't capture screenshot (Cmd+Shift+4) Keyboard Shortcut [bug]

### ISSUE THREAD

**Issue by cdcharlebois** [noah-nuebling/Mac-Mouse-Fix#756]
## Description

I recently upgraded to 3.0.0 and I can't capture the keyboard shortcut for screenshot. The keyboard shortcut triggers the actual "take screenshot" function instead of being caught by Mac Mouse Fix. I have the MX Master 3S mouse and the button is identified as "Button 6"

## Steps to reproduce

1. Go to the Buttons tab on Mac Mouse Fix
2. Click Button 6 with the cursor in the "+" field
3. (see the click event show up for the events below)
4. Change the dropdown value to "Keyboard Shortcut"
5. Enter the command (Cmd+Shift+4) 
6. (See the screenshot cursor show up, instead of the key combination captured in Mac Mouse Fix)

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: 14.2.1 (23C71)
Mouse Model: Logitech MX Master 3S

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by wakmail** [comment]
Hmm, it seems to work for me. Does it work for other buttons?

**Comment by noah-nuebling** [comment]
Hey, thanks for reaching out! 

Are you using any third-party apps that might affect how the screenshot shortcuts work? Maybe Cleanshot?

**Comment by cdcharlebois** [comment]
No third party tools, tested again this morning and the behavior is still happening

**Comment by cdcharlebois** [comment]
https://github.com/noah-nuebling/mac-mouse-fix/assets/2905603/78de4644-322f-4e65-ad9a-f5e673b0593c

**Comment by noah-nuebling** [comment]
Very weird. On my end it works just fine. 

I don't really know where to start when it comes to debugging this since I can't reproduce this at all, so I'm unfortunately just as clueless as anyone when it comes to fixing this.

But I'll keep this in the back of my mind, and hopefully I'll come up with some idea why this might be happening.  If you find out anything more, please also let me know. Thank you.

**Comment by noah-nuebling** [comment]
@cdcharlebois do you have Logitech Options installed?

**Comment by cdcharlebois** [comment]
Hi @noah-nuebling, thanks for the response. I don't have that app installed, no. It seemed to not work with my version of macOS at the time and MacMouseFix provides a nicer experience for what I need :)

**Comment by cdcharlebois** [comment]
Upgraded to Mac OS 14.3.1 (23D60) and the issue is resolved now!
