### ISSUE TITLE
Mac Mouse fix einschalten nicht möglich [bug]

### ISSUE THREAD

**Issue by entoryFB** [noah-nuebling/Mac-Mouse-Fix#758]
## Description

Programm installiert
aufgerufen
und hier lässt sich der Schieberegler nicht auf einschalten stellen

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: 13.6.3 (22G436)
Mouse Model: Logitech mx Mater

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi @entoryFB, danke für dein Feedback!

Versuche mal die folgenden Schritte:

1. Lösche jegliche Kopien von der "Mac Mouse Fix" app von deinem Computer
2. Leere den Papierkorb
3. Starte den Computer neu
4. Versuche Mac Mouse Fix einzuschalten

Lass mich wissen wie es läuft oder wenn du mehr Fragen hast.

**Comment by noah-nuebling** [comment]
Hallo! Im Issue https://github.com/noah-nuebling/mac-mouse-fix/issues/648 findest du noch mehr Ideen für das beheben des Problems. 

Wenn du mehr rausfindest antworte am besten dort, damit alles an einem Platz ist. Dankeschön!
