### ISSUE TITLE
It is worth reference [enhancement]

### ISSUE THREAD

**Issue by sogoo** [noah-nuebling/Mac-Mouse-Fix#760]
## Description
More gestures and key combinations

## Rationale
Better And Better 2.0
https://www.better365.cn/bab2.html

It is worth reference.

**Comment by noah-nuebling** [comment]
Hey there @sogoo, 

Thanks for sharing, that's an interesting app!

I don't think I'll ever do complex Gestures like this app, where you draw letters and stuff, but I do plan to add some more simpler Gestures in the future. 

Thanks again for sharing, but can you please tell me how to uninstall it? I don't speak Chinese unfortunately. Thank you very much.

**Comment by sogoo** [comment]
> Thanks again for sharing, but can you please tell me how to uninstall it? 

https://apps.apple.com/us/app/id6473684385

**Comment by noah-nuebling** [comment]
Thank you very much haha.

**Comment by noah-nuebling** [comment]
Are there any specific Gestures and key combinations you'd like to use with Mac Mouse Fix?

**Comment by noah-nuebling** [comment]
I'll close this issue now. Thanks again for sharing, if you have a specific feature you'd like to see, please open a new issue. Thanks!
