### ISSUE TITLE
Even faster scrolling duration/less smooth scrolling [enhancement]

### ISSUE THREAD

**Issue by merlinaudio** [noah-nuebling/Mac-Mouse-Fix#766]
## Description
I'd love for there to be a scrolling "smoothness" setting that closely mimics Chrome's scrolling

## Rationale
The lowest-smoothness setting still takes pretty long to scroll

## Additional info
Maybe allowing to set a duration (and potentially easing curve) would be even better?

**Comment by Mrtenz** [comment]
I have smoothness set to regular and speed set to high, and I agree it's still a bit too slow.

**Comment by noah-nuebling** [comment]
Hey guys, thanks for reaching out! I made the scrolling a bit more responsive in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1).

What do you think?

**Comment by merlinaudio** [comment]
Hi, just came here after installing 3.0.1 to comment that this issue can be closed IMO, then saw your comment :D @noah-nuebling 

Additionally, scrolling used to be a little laggy sometimes (skipping frames on high-refresh rate screens). I don't notice this at all anymore with 3.0.1! I assume this is because of the "under the hood improvements" mentioned at the very end of the release notes?

Awesome update, scrolling feels SO GOOD now. Thank you so much. Keep up the great work :)

**Comment by noah-nuebling** [comment]
Hey @merlindru, I'm so glad you like it!

I think frame skips might just be less noticable, since the animations are shorter now. I didn't implement any specific optimization aimed at preventing frame skips. If you still experience lagginess, let me know!
