### ISSUE TITLE
MacMouseFix not working after user switch [bug]

### ISSUE THREAD

**Issue by Raphzen** [noah-nuebling/Mac-Mouse-Fix#769]
## Description

I have two users on my Mac (work and private) using Mac Mouse Fix. Everytime I switch user, I need to disable and enable Mac Mouse Fix for it to work again.

## Steps to reproduce

1. Have Mac Mouse Fix enabled
2. Switch to another user, also using Mac Mouse Fix -> Not working directly

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: 14.2
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi! You can work around this by logging out of the first user before logging in with the second user. 

Proper fix coming at some point.

I hope this helps a little!

**Comment by noah-nuebling** [comment]
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.
