### ISSUE TITLE
Switching users disables even scrolling for the mouse [bug]

### ISSUE THREAD

**Issue by karim-halayqa** [noah-nuebling/Mac-Mouse-Fix#773]
## Description

When switching from one user to another, the mouse stopped scrolling for me. I had to install mouse fix for the other user. Even then, when switching users it would still stop working until i disable it and enable it back.
That requires opening the application on each switch, and i switch from personal to work users frequently.
at least for now maybe "enable mouse fix" can be added to the menu bar tab so that you don't have to open the application each time?
Thank you, and I appreciate the work that's been made on this awesome app.

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: 14.12.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi! You can work around this by logging out of the first user before logging in with the second user.

Proper fix coming at some point.

I hope this helps a little! Let me know if you have more questions.

**Comment by noah-nuebling** [comment]
Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!

Let me know if you have any more questions.

**Comment by karim-halayqa** [comment]
> Hey there, I just fixed the issue in the latest release [3.0.1](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.1)!
> 
> Let me know if you have any more questions.

works perfectly, thank you:)
