### ISSUE TITLE
Great release! [other]

### ISSUE THREAD

**Issue by minimum91** [noah-nuebling/Mac-Mouse-Fix#774]
I used the 3.0.0 beta 7 on my Mac Pro running Mojave and even though it is not officially supported I was able to set up all the settings on a newer MacBook I have running Monterey and then just copy the plist over. Same with this official 3.0.0 release - updated and no issues, everything is still working. For a non-supported app, this is still one of the most essential  ones I have on this legacy system. Thank you Noah!

**Comment by noah-nuebling** [comment]
I’m glad you like the app! Thanks for sharing I appreciate it!! :)
