### ISSUE TITLE
Enable button does not do anything [bug]

### ISSUE THREAD

**Issue by coneypylon** [noah-nuebling/Mac-Mouse-Fix#776]
https://github.com/noah-nuebling/mac-mouse-fix/assets/14968474/df62b815-441b-4fe9-be25-1a924493d4ca

## Description

When I click the enable button, it does not enable.

## Steps to reproduce

1. Open Mac Mouse Fix
2. Click Enable Mac Mouse Fix

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: Sonoma 14.2.1

**Comment by noah-nuebling** [comment]
Hi there, thanks for reaching out! Please check out this issue for solution steps: https://github.com/noah-nuebling/mac-mouse-fix/issues/648

Try the “Theory 1” steps. That stuff has been the culprit for all the other users I talked to who had the same issues.

**Comment by coneypylon** [comment]
This was it! Thanks!
