### ISSUE TITLE
Reverse scrolling doesn't work [bug]

### ISSUE THREAD

**Issue by sausagehands** [noah-nuebling/Mac-Mouse-Fix#782]
## Description

* reverse scrolling doesn't work
* application does not appear in console.app

## Steps to reproduce

1. enable reverse scrolling → does not work
2. try restarting computer to see if that allows changes to take place → does not work
3. reinstalled using homebrew → still doesn't work

almost certain this was working yesterday before updating. 

## Context

Mac Mouse Fix Version: 3.0.0
macOS Version: 14.1.2 Sonoma M1
Mouse Model: Logi M650

## Additional Comments

almost certain this was working yesterday before updating. 

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there, @sausagehands, thanks for your feedback!

If you still have these problems, please open a new Issue and provie the the following info:

1. Do the smooth scrolling settings do anything?
2. Can you remap buttons?
3. Can you use keyboard modifiers to affect scrolling?

Also, what do you mean by 'it doesn't show up in Console.app? Where do you expect it to show up exactly?

Please also check if there are any other mouse apps installed that might be interfering with MMF.

Thanks!
