### ISSUE TITLE
Support Simulation of Pressing Modifier Keys (e.g., cmd, ctrl) with Mouse Buttons [enhancement]

### ISSUE THREAD

**Issue by zzzchuu** [noah-nuebling/Mac-Mouse-Fix#786]
## Description
The current Keyboard Shortcut feature only supports combinations like ctrl+cmd+C, but does not support standalone combinations like ctrl+cmd. Is it possible to simulate the pressing of ctrl+cmd when a mouse button is pressed?

## Rationale
For example, on macOS we can use Ctrl + Cmd + Left Mouse Button to drag windows by clicking on any part(see top 2 answers in [this discussion](https://apple.stackexchange.com/questions/321918/move-window-by-clicking-on-any-part-as-on-linux) ). 
With Mac Mouse Fix, I really want use my mouse side button instead of the keyboard combination for this.

## Additional info
–

**Comment by rabomen** [comment]
Resolved using Karabiner-Elements to implement this. Closing the issue now. Thanks!
