### ISSUE TITLE
Remapping Left-Middle-Scroll-Right buttons on a 3 button scroll mouse like a Evoluent Vertical Mouse 4 [enhancement]

### ISSUE THREAD

**Issue by llavalle** [noah-nuebling/mac-mouse-fix#79]
## Description
The output from the console is the following (index starts at Zero for the mouse buttons)
Left Click : buttonNumber=0
Wheel Click : buttonNumber=4 (wheel is between first and second mouse buttons)
Middle Click : buttonNumber=2
Right Click : buttonNumber=1
First Side Button (top one which is usually back) : buttonNumber=3
2nd Side (usually forward) : buttonNumber=5

## Rationale
What I'm trying to do : 
-Get the left click to left click
-->That obviously works

-Get the wheel click to do a wheel click (closing tab in chrome and the like)
--> This is a "Click Button 5" in the UI but I can't map it to a scroll click that could close tabs in chrome for example.

-Get the middle mouse button to right click
--> When you rest your finger on a mouse like that, the button that's to the right of the scroll wheel is the right click.  Right now I can map it to "missing Control ans Spaces" which is awesome but I'd like that on the actual 3rd button, the "right" one

-Add the new awesome "click and drag" to work on the rightmost button (see line above)

I was able to do something like that using Evoluent software but apparently the new restrictions from MacOS are problematic.  They recommend using USB Overdrive but it seems overkill (see the 10.15 section in here : https://evoluent.com/support/download/)

## Additional info
–

**Comment by noah-nuebling** [comment]
> -Get the wheel click to do a wheel click (closing tab in chrome and the like)
> --> This is a "Click Button 5" in the UI but I can't map it to a scroll click that could close tabs in chrome for example.

You should be able to map to wheel click by choosing the "Open Link in new Tab" option in 2.0.0 Beta 1 or the "Middle Button Click" option in [2.0.0 Beta 2](https://github.com/noah-nuebling/mac-mouse-fix/releases). I know this is somewhat confusing, if you have any input on how to design this better, I'd really appreciate that!

> -Get the middle mouse button to right click
> --> When you rest your finger on a mouse like that, the button that's to the right of the scroll wheel is the right click. Right now I can map it to "missing Control ans Spaces" which is awesome but I'd like that on the actual 3rd button, the "right" one

If I understand correctly, you want to be able to map to a Secondary Mouse Button click (aka a Right Click). I've given this some thought, and while it would be relatively easy to implement on the technical side, it would require some new UI which might be a considerable amount of work. Also this is not a super high priority and I don't have too much time to work on Mac Mouse Fix, so please don't expect this feature coming any time soon. I'm definitely taking your request into consideration though and I'll think about it more in the future.

> -Add the new awesome "click and drag" to work on the rightmost button (see line above)

Hey I'm glad you like it :)
You should be able to add click and drag on any button that is not the Primary or Secondary Mouse Button (buttonNumbers 0 and 1). To use it with a different button, you can simply click and drag that button over the "+"-field. 

I hope this helps, and let me know if you have any more questions or feedback!

**Comment by llavalle** [comment]
Awesome ;)

Upgraded to Beta 3 ;).  Was able to get the wheel click to do a "middle button click".

Got it for the right click!

Works awesome now!

**Comment by noah-nuebling** [comment]
Great stuff! :) I'm glad you like it.

I just released [Beta 4](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0-Beta-4) if you're interested in checking it out.

Let me know when you need help with anything else or have any feedback!
