### ISSUE TITLE
After version 3.0.1 (22148) was released, scrolling became worse :( [other]

### ISSUE THREAD

**Issue by V-Coba** [noah-nuebling/Mac-Mouse-Fix#795]
In version 3.0.0 it was much nicer and more convenient to scroll through content than in version 3.0.1. It feels like scrolling has become more sticky, slower, and more annoying. I can't help but feel as if something is blocking the scrolling. Especially if you turn on "Precision". I began to notice that even my hand using the mouse began to become more tense and painful.
Please bring back the scrolling that was in version 3.0.0. This was the perfect implementation of smooth scrolling! The only thing that really annoyed me about the previous implementation of smooth scrolling was the lack of an option to disable acceleration, which prevents me from using the wheel on my G903 when I put it in free rotation mode. That is, I simply don’t need acceleration, because my mouse wheel can spin freely, without steps, at any speed! And because of this stupid acceleration, I can’t use this wheel mode on my mouse =(
Why touch something that worked perfectly?! As you know, the best is the enemy of the good!

P. S. I use "Regular" scrolling.

**Comment by merlinaudio** [comment]
Hm, I feel like there should really be settings for this

IMO the scrolling implementation of 3.0.1 is perfect, it's quite literally the best I've ever used. I love the easing and the fact that it goes faster, to me it was too smooth before

Maybe there could be a third setting? A way to choose between different easings?

#766 is related

**Comment by V-Coba** [comment]
I was talking about the "Smoothness: Regular" setting. You are apparently using "Smoothness: High". If you, like me, use the "Smoothness: Regular" setting, then it is possible that you simply do not enable the "Precision" option… Please take a screenshot of your settings from the "Scrolling" tab.

**Comment by merlinaudio** [comment]
Maybe I misspoke in #766 but I am using these settings:

![Smoothness: Regular, Speed: High](https://github.com/noah-nuebling/mac-mouse-fix/assets/85179170/82e55fc9-16ef-4a0e-9059-6fcbb0954f99)

I personally like the new behavior with these much, much better. But I can see that not everybody might like it, so IMO exposing a setting to toggle between different easings would be the best since it's most flexible

**Comment by V-Coba** [comment]
The thing that bothers me the most about version 3.0.1 is scrolling if you enable the "Precision" option.

**Comment by V-Coba** [comment]
The main problem with the new smooth scrolling implementation for the "Regular" setting is that the shorter animation makes the scrolling itself slower. That is, you need to turn the mouse wheel more, especially if you set the speed to “Low”. You can, of course, set the speed to "Medium", but then the scrolling becomes too fast and inaccurate.

**Comment by merlinaudio** [comment]
@V-Coba For now you should be able to downgrade to 3.0.0 right? https://github.com/noah-nuebling/mac-mouse-fix/releases/download/3.0.0/MacMouseFixApp.zip

**Comment by V-Coba** [comment]
I don't like and try not to use old versions of programs.

**Comment by kecinzer** [comment]
Same issue here. In version 3.0.0 scrolling was nice and fast. Now in 3.0.1. everything is slower and laggy.
May be I will try to downgrade.

**Comment by merlinaudio** [comment]
@kecinzer What are your settings?

**Comment by kecinzer** [comment]
After switch to older version 3.0.0 it works like a charm.
Here is my settings...
<img width="323" alt="Snímek obrazovky 2024-02-07 v 7 31 35" src="https://github.com/noah-nuebling/mac-mouse-fix/assets/1541555/2647f58f-00eb-4cf9-bcf2-b5b82218e075">

**Comment by noah-nuebling** [comment]
Hey there guys, thanks for the feedback! 

I tried to address these issues in the latest release [3.0.2](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.2). Let me know if you like the scrolling experience it provides or have any further wishes for improvements.

**Comment by noah-nuebling** [comment]
Oh @merlindru I hope you still like the scrolling in 3.0.2, the animations are a bit slower now. My goal was to still provide a really 'direct' and immediate feel for the scrolling while making it slower such that the scrolling is relatively easy to follow with your eyes at all times.

It's noticably slower than Chrome though, which you mentioned was your preference, so I'm not sure you'll like it. If you have any feedback, I'd be very interested to hear it.

**Comment by merlinaudio** [comment]
@noah-nuebling Scrolling is still awesome! Thank you for making & maintaining MMF :)

much love

**Comment by noah-nuebling** [comment]
Great I'm glad to hear that!! Thanks for getting back.

**Comment by kecinzer** [comment]
> Hey there guys, thanks for the feedback!
> 
> I tried to address these issues in the latest release [3.0.2](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.2). Let me know if you like the scrolling experience it provides or have any further wishes for improvements.

It seems much better with 3.0.2. Thank you. Great work.

**Comment by V-Coba** [comment]
> Hey there guys, thanks for the feedback!
> 
> I tried to address these issues in the latest release [3.0.2](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.2). Let me know if you like the scrolling experience it provides or have any further wishes for improvements.

Yes, it got much better! Thank you very much!!! It's nice to see that this is the second time I've been mentioned in the changelog :)

**Comment by V-Coba** [comment]
> Hey there guys, thanks for the feedback!
> 
> I tried to address these issues in the latest release [3.0.2](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/3.0.2). Let me know if you like the scrolling experience it provides or have any further wishes for improvements.

However, the lack of an option to disable scrolling acceleration is still very annoying 😡 I have a Logitech G903, which has a special button that allows you to switch the wheel to free spin mode, so I can enable scroll acceleration on the mouse itself at any time. When I switch the wheel to free spin mode by pressing a special button on the mouse itself, the scrolling becomes completely uncontrollable! 😵‍💫 🤪 🤯 That is, because of Mac Mouse Fix, I can’t properly use the free wheel mode on my expensive gaming mouse! I need consistent scrolling without any acceleration 🙏

**Comment by kecinzer** [comment]
After few days of testing. Version 3.0.0 still has the best and fluid scrolling for me. With v.3.0.2 I can see lags.

**Comment by kil0ba** [comment]
I started to see scrolling bugs after I bought the license. I always worked with 3.0.2 and when it was a trial, it worked perfectly, but right after I entered the activation code, the scroll started to freeze sometimes. @noah-nuebling I hope that this will help
