### ISSUE TITLE
[alt]-scrolling does not work with "Smooth scrolling" enabled

### ISSUE THREAD

**Issue by marchein** [noah-nuebling/mac-mouse-fix#8]
I am not able to press [alt] and scroll, which resizes the canvas in adobe apps for example when Smooth scrolling in enabled. With it disabled it actually works fine. 

Edit: with [alt] I mean the alt key on a Windows keyboard. On a Mac keyboard it should be the option key which causes the issues. 

Mac Mouse Fix Version 0.9 (50)
macOS 10.15 Beta 10 (19A578c)
Photoshop 20.0.0.6

**Comment by noah-nuebling** [comment]
Hi there marchein thanks for the feedback.
Unfortunately, I can't promise you that I'll be able to fix this issue in the near future.

However, there is a list of feature ideas for v2.0 here on GitHub and one important one is to let the user zoom by scrolling while holding down the command key, by sending artificial trackpad events to the UI. This should allow you to zoom with your mouse, whenever you can zoom by doing a pinch gesture on the trackpad. I don't know how easy this is to implement though. If anyone here on GitHub is interested in implementing this, you might want to check out this [repo](https://github.com/calftrail/Touch) by calftrail who reverse-engineered macOS touch events.

If alt-scrolling to zoom in Photoshop works when scrolling on a trackpad, then it might also be possible to get alt-scrolling to zoom to work with Mac Mouse Fix's Smooth Scrolling by changing the parameters of the artificial scroll events that Mouse Fix sends to make them closer to the events that a real trackpad sends.
I've played around with this a little bit and got some interesting results by setting the value fields 'kCGScrollWheelEventScrollPhase' and 'kCGScrollWheelEventMomentumPhase' dynamically.

**Comment by noah-nuebling** [comment]
I just fixed this! :)
Will push an update in the next few days.

I simply disabled smooth scroll for all adobe apps, and it works great as far as I can tell. I made it work with Pixelmator, too, by adding some additional data to the artificial scroll events.
