### ISSUE TITLE
Feature for controlling mouse tracking acceleration [enhancement]

### ISSUE THREAD

**Issue by huntedmunkie77** [noah-nuebling/Mac-Mouse-Fix#819]
## Description
Settings to be able to override the OS default mouse pointer acceleration values, to enable users to control the level of acceleration to better match what they prefer.

## Rationale
The mac mouse pointer acceleration is annoying. Many want/prefer more linear tracking. I used to use Steermouse to adjust both pointer acceleration and trackwheel scrolling. Your app would be killer if it could also include tracking acceleration.

## Additional info
–

**Comment by starquake** [comment]
Just wanted to let you know this is now implemented in macOS:
https://github.com/noah-nuebling/mac-mouse-fix/issues/14#issuecomment-1722334566
