### ISSUE TITLE
Adjust mouse sensitivity [enhancement]

### ISSUE THREAD

**Issue by bynickrich** [noah-nuebling/Mac-Mouse-Fix#827]
## Description
Hello,
Loving the app, it's working perfectly with my new Pulsar Xlite 3. It would be super sweet if there was an option to adjust the sensitivity of the mouse itself.

## Rationale
As of right now the app for sure fixes after marketing mouse scrolling to be buttery smooth. However, I find interesting that you have a great deal of control over the scrolling behavior and more advanced options such as binding the mouse buttons but have no option to adjust the cursor sensitivity itself outside of native macOS settings.

Mac Mouse Fix would truly be an all in one solution if it had a sensitivity and acceleration options for the cursor its self and I believe it feels fitting since the title of the software is "Mac Mouse Fix" why not encompass this behavior of the mouse as well.

## Additional info
–

**Comment by starquake** [comment]
Just wanted to let you know this is now implemented in macOS:
https://github.com/noah-nuebling/mac-mouse-fix/issues/14#issuecomment-1722334566

**Comment by bynickrich** [comment]
Thank you closing the issue!
