### ISSUE TITLE
(2.0.0 Beta 2) Mac Mouse Fix Helper quit unexpectedly when pressing a button [bug]

### ISSUE THREAD

**Issue by hacker1024** [noah-nuebling/mac-mouse-fix#83]
## Description

Whenever Mac Mouse Fix is monitoring mouse input (when it's enabled, or when I add a new button), pressing a button crashes the Mac Mouse Fix Helper app. Furthermore, no input is received by Mac Mouse Fix.

The crash report is included, but the significant line is as follows:

```
Application Specific Information:
Assertion failed: (false), function getActiveModifiersForDeviceWithPressedButtons, file /Users/Noah/Documents/Projekte/Programmieren/Xcode/Xcode Projekte/Mac Mouse Fix/mac-mouse-fix/Helper/InputTransformation/Modifiers/ModifierManager.m, line 101.
```

## Steps to reproduce

1) Enable Mac Mouse Fix, or try to add a new button
2) Press a button

## Context

Mac Mouse Fix Version: 2.0.0 Beta 2
macOS Version: 11.2.3 (20D91)
Mouse Model: [Acer Predator SM-9627](https://community.acer.com/en/discussion/620695/predator-gaming-mouse-sm-9627-dpi)

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

https://pastebin.com/NGRk37Dc

**Comment by hacker1024** [comment]
The issue doesn't appear when using the latest commit. My bad.

**Comment by noah-nuebling** [comment]
Thanks anyways for your great feedback @hacker1024! If you have any more troubles let me know.
