### ISSUE TITLE
The vertical drag behavior is different from v2 [bug]

### ISSUE THREAD

**Issue by fang2hou** [noah-nuebling/Mac-Mouse-Fix#854]
## Description

I've noticed that when I try to switch spaces by dragging, the movement is reversed compared to v2.

## Steps to reproduce

1. Install Logi Options+. (I Installed it before using v2, and it is the latest version)
2. Do some settings in Logi Options+, something like standard scrolling.
3. Set `Middle Button`'s `Click and Drag` action to `Spaces & Mission Control`.
4. Click and move the mouse to the left.
5. Switched to the left space.

## Context

Mac Mouse Fix Version: 3.0.1
macOS Version: 14.3.1 (23D60)
Mouse Model: MX Anywhere 3

## Additional Comments

Every software I used are latest version.
Actually I tried change the settings of Logi Options+, but nothing helped.

---

### Console Logs

–

### Crash Reports

–

**Comment by georgesolomos** [comment]
I've also just noticed the Click and Drag is reversed from before

**Comment by JanPokorny** [comment]
WORKAROUND: In Mac Settings, go to "Mouse" and enable "Natural Scrolling". Then, in Mac Mouse Fix, enable "Reverse Direction".

**Comment by fang2hou** [comment]
@JanPokorny 
Thanks! It works on my Mac
