### ISSUE TITLE
MacMouse Fix stopped working after 3.0.2 update! [bug]

### ISSUE THREAD

**Issue by Cipri84** [noah-nuebling/Mac-Mouse-Fix#871]
## Description

The app stopped working after the update to 3.0.2! It doesn't work on any website and you can't even open the app, every time I try to open the app it gives me an error saying it can't be opened.

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: Sonoma 14.4 RC 
Mouse Model: It Works Vertical Mouse

**Comment by nilsborg** [comment]
Jep same here

**Comment by noah-nuebling** [comment]
Hey guys, thanks for the quick feedback! It works on my end so this is weird. 

I exported the app again with Xcode using a different method:

[MacMouseFixApp.zip](https://github.com/noah-nuebling/mac-mouse-fix/files/14500422/MacMouseFixApp.zip)

Does this work better?

**Comment by nilsborg** [comment]
It does! 🙌  Thank you :)

**Comment by noah-nuebling** [comment]
Ok great! Thanks for getting back quickly.

**Comment by Cipri84** [comment]
It´s working now! Thank you!
