### ISSUE TITLE
Side buttons and middle click doesn't work on G603 [other]

### ISSUE THREAD

**Issue by cja-smith** [noah-nuebling/mac-mouse-fix#88]
Hi there, been using this app for a while now for my G400, and it works really well! I've just upgraded to a wireless mouse (G603) and I'm connecting to the Mac through Bluetooth. The app works for fixing scroll issues, but the mouse buttons don't seem to be customisable through it.

I've tested the buttons on https://www.onlinemictest.com/mouse-test/ and it recognises all the affected buttons (mouse3/4/5), so I know the OS can see there are buttons there.

**Comment by cja-smith** [comment]
Issue appears to have resolved itself somehow

**Comment by noah-nuebling** [comment]
Hey there Charles I'm glad to hear that. 
Thanks for the report and for getting back about the resolution.
