### ISSUE TITLE
How to kill Mac Mouse Fix via terminal [enhancement]

### ISSUE THREAD

**Issue by lywlywly** [noah-nuebling/Mac-Mouse-Fix#897]
## Description
Many other 3rd party tools on macOS have a daemon process running in the background, while it seems that Mac Mouse Fix does not. Is there a way to stop Mac Mouse Fix via terminal?

## Rationale
I experienced strange behavior of mouse freezing and I want to check if it is the problem of Mac Mouse Fix. I was still able to use keyboard, but I cannot find the process for Mac Mouse Fix background service.

## Additional info
–

**Comment by noah-nuebling** [comment]
Hi, thanks for your feedback!

Try this command:

```
launchctl remove com.nuebling.mac-mouse-fix.helper
```
