### ISSUE TITLE
Scrolling not working in Terminal.app if 'Smooth scrolling' is enabled

### ISSUE THREAD

**Issue by josser** [noah-nuebling/mac-mouse-fix#9]
Happens only in Terminal.app

Btw, app is fantastic! thank you! )

**Comment by noah-nuebling** [comment]
Hi there Josser, thank you for your kind words! I just wrote a quick fix for this. You can download a version of Mac Mouse Fix with the fix [here](https://drive.google.com/open?id=1-j1fQEnUa714oHTT3OSGgiKzgLP27lhI). Let me know if you have any issues with it.
