### ISSUE TITLE
I'm being asked to pay even though I donated back in September 😢 [bug]

### ISSUE THREAD

**Issue by SamCrispBox** [noah-nuebling/Mac-Mouse-Fix#916]
## Description

Hi Noah,

I've just had an alert that I need to pay for Mac Mouse Fix which I wouldn't mind doing but I did donate back in September via paypal (transaction 6E281902U13561847).  I don't mind topping it up (it's really useful) but would prefer not to end up doing that repeatedly.  

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: 14.4.1
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi Sam, thanks for your donation! And I'm glad you're enjoying the app.

Just shoot me an email and I'll send you a free license.

**Comment by SamCrispBox** [comment]
All good- sorry, couldn't find your address on the webpage- thanks Noah!
