### ISSUE TITLE
Can't select certain apps for app specific settings 

### ISSUE THREAD

**Issue by reeceicles** [noah-nuebling/mac-mouse-fix#92]
I want to disable smooth scrolling for Minecraft, which runs through java, a Unix executable file. I'm not sure if it's possible to allow exec files to be selected as an application in this way, but it would be useful so I don't need to disable and enable smooth scrolling every time I want to play the game.

**Comment by noah-nuebling** [comment]
Hey @reeceicles, thanks for your feedback!

Currently, you can unfortunately only add app bundles to the app-specific settings.

Re-engineering things to support executables is definitely something I want to work on at some point, but it's not at the top of the agenda, yet, so please don't expect any improvements on this soon.

In the mean time, I recommend you check out [SteerMouse](http://plentycom.jp/en/steermouse/) to replace the button mapping and [MOS](https://mos.caldis.me/) to replace the smooth scrolling features of Mac Mouse Fix. MOS supports app-specific settings for executables as far as I know.

**Comment by noah-nuebling** [comment]
There is already an issue at #55 about the same topic, if you have any more thoughts or feedback on this, it's probably best if you post it there so it's all in one place

**Comment by noah-nuebling** [comment]
I'll close this issue now, so it's all concentrated in #55
