### ISSUE TITLE
Looks like reopens when scrolling  [bug]

### ISSUE THREAD

**Issue by serhiyeniavl** [noah-nuebling/Mac-Mouse-Fix#934]
## Description

When I scroll with medium/intense speed sometimes it stops working for a sec and Mac Mouse Fix window pops up (feels like reopens but it doesn't) - this is very annoying, I have to switch to my working app back. This behaviour I've spotted only when updated my MacOS version to Sonoma

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: 14.4.1 (23E224)
Mouse Model: Redragon Enlightment M991-RGB

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hi there @serhiyeniavl thanks for the feedback! This should be fixed in 3.0.3, so I'm going to close this issue. If you still experience any problems, let me know.
