### ISSUE TITLE
Activate my purchase [bug]

### ISSUE THREAD

**Issue by melodyrw** [noah-nuebling/Mac-Mouse-Fix#937]
## Description

Hi! I have my activation key, but I cannot get the right place to open to put it in. I tried it inside the app and through the website after my purchase- see screen recording linked below
https://www.loom.com/share/8b3417f9805e4b1e97e1b56c3b78d1ee

## Steps to reproduce

1. https://www.loom.com/share/8b3417f9805e4b1e97e1b56c3b78d1ee

## Context

Mac Mouse Fix Version: 3.0.2
macOS Version: Sonoma 14.3
Mouse Model: –

## Additional Comments

–

---

### Console Logs

–

### Crash Reports

–

**Comment by melodyrw** [comment]
Well, it worked for me just now. Nevermind!

**Comment by noah-nuebling** [comment]
Hi @melodyrw thanks for the feedback and sorry for the trouble.

Have you moved the app out of the Downloads folder?

Also, if you you shoot me an email and include the email address you bought the app with I'll gladly give you a refund.

**Comment by noah-nuebling** [comment]
> Well, it worked for me just now. Nevermind!

Oh nice! Do you have any idea what could have made a difference?

**Comment by melodyrw** [comment]
I think you were right about moving it out of downloads- I did that
coincidentally before seeing your response, so maybe that was the trick. I
also had issues Enabling, but was able to find answers here, so now all is
working perfectly. Thanks for this app- I love my mouse and am so happy to
still be able to use it to its fullest extent even after migrating to Apple
from PC. Huzzah!

**Comment by noah-nuebling** [comment]
Great thanks for sharing! This should help me give other ppl better support / make the experience better. 

Hope you enjoy the app! :)
