### ISSUE TITLE
Cannot use after upgrading to macOS 11.3.1 [other]

### ISSUE THREAD

**Issue by kockok** [noah-nuebling/mac-mouse-fix#94]
The prompts keep popping up and I had to move this app to trash as stipulated by Apple.

![Screen Shot 2021-05-05 at 3 25 24 PM](https://user-images.githubusercontent.com/232541/117108938-7b58c380-adb6-11eb-9497-b4503161249b.png)

**Comment by islavstan** [comment]
I have the same error on 11.2.2

**Comment by vruffer** [comment]
Same for me on 10.15.7

**Comment by shammu2bd** [comment]
Same here for 11.2.3

**Comment by noah-nuebling** [comment]
Hey guys thanks for reaching out about this!

New versions of the app which should fix these error messages are now available:

- [1.0.4](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/1.0.4)
- [2.0.0 Beta 8](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0-Beta-8)

I hope these work for everyone. If not be sure to let me know.

For more info on what's going on, see https://github.com/noah-nuebling/mac-mouse-fix/issues/95
