### ISSUE TITLE
Mac mouse closed unexpectedly [bug]

### ISSUE THREAD

**Issue by carlosrh2** [noah-nuebling/mac-mouse-fix#98]
## Description

Mac mouse closed unexpectedly... I don't open the app =(

## Steps to reproduce

–

## Context

Mac Mouse Fix Version: 1.0.3
macOS Version: Mojave 10.14.6
Mouse Model: Wheel Optical Mouse 

## Additional Comments

–

---

### Console Logs

https://pastebin.com/iji5diqZ

### Crash Reports

https://pastebin.com/crqd1ptz

**Comment by emailjough** [comment]
I have same issue as of today. Also was using MM v1.0.3 and Catalina 10.15.7 on 2012 MBP. 

Then came here and tried using 2.0.7. App no longer quits on launch but could not get past Accessibility authorization despite having granted accessibility and rebooting.

**Comment by noah-nuebling** [comment]
Hi @carlosrh2, thanks for filing a report and for taking the time to attach some console logs and bug reports!

New versions of the app which should fix your issue are now available:

- [1.0.4](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/1.0.4)
- [2.0.0 Beta 8](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0-Beta-8)

Let me know if you have any more troubles with these.

For more info on what's going on see https://github.com/noah-nuebling/mac-mouse-fix/issues/95

**Comment by carlosrh2** [comment]
Hi @noah-nuebling ,
Thanks for that answer, I was very happy! I appreciate the work you do with this app. Thanks again!

**Comment by noah-nuebling** [comment]
Cool, glad to help :)
