### ISSUE TITLE
Mouse cursor locked at one point and fidgets when scrolling without smooth scrolling [bug]

### ISSUE THREAD

**Issue by keikhcheung** [noah-nuebling/mac-mouse-fix#99]
## Description

When I use Mac Mouse Fix beta 2.0.0 Beta 7 without smooth scrolling and inverted scroll, it locks my cursor at one point and fidget. The only way to stop that is to hold Cmd or quit Mac Mouse Fix.

## Steps to reproduce

1. Go to Mac Mouse Fix settings.
2. Disable invert direction.
3. Disable smooth scrolling.
4. Switch to some other application, e.g. Firefox. Start scrolling.
5. Wait and see the flickering mouse cursor.

## Context

Mac Mouse Fix Version: 2.0.0 Beta 7
macOS Version: 11.3.1
Mouse Model: CSL vertical mouse 303887

## Additional Comments

<img width="692" alt="image" src="https://user-images.githubusercontent.com/22561336/117189352-655ef900-adde-11eb-8ac0-8831e8c2cbe3.png">

---

### Console Logs

–

### Crash Reports

–

**Comment by noah-nuebling** [comment]
Hey kei, thanks for filing a report!

This issue should be gone in [2.0.0 Beta 8](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0-Beta-8).

I changed some stuff in Beta 7 in attempts to fix https://github.com/noah-nuebling/mac-mouse-fix/issues/93, but that lead to the issues which you were experiencing, so I reverted them in Beta 8.
In case you're interested, I'll eventually answer https://github.com/noah-nuebling/mac-mouse-fix/issues/93 and add a more detailed explanation there when I have time.

**Comment by CavalloneChen** [comment]
This issue arises when I open a PDF with Preview. In my case, smooth scrolling and inverted scrolling work fine with other apps.

**Comment by noah-nuebling** [comment]
@CavalloneChen Oh that's interesting, it could be because smooth scrolling is disabled for Preview by default. (Go to 'More...' > 'App-specific settings' to change this.)

Do you still experience the issue on [2.0.0 Beta 8](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0-Beta-8)?

**Comment by CavalloneChen** [comment]
> @CavalloneChen Oh that's interesting, it could be because smooth scrolling is disabled for Preview by default. (Go to 'More...' > 'App-specific settings' to change this.)
> 
> Do you still experience the issue on [2.0.0 Beta 8](https://github.com/noah-nuebling/mac-mouse-fix/releases/tag/2.0.0-Beta-8)?

It is resolved! Thanks! @noah-nuebling

**Comment by noah-nuebling** [comment]
Awesome, thanks for getting back!
